import { PARTICLE_TYPES } from './particles.js';

export const GOALS = [
  { name: 'Synthesize a Proton', type: PARTICLE_TYPES.PROTON },
  { name: 'Synthesize a Neutron', type: PARTICLE_TYPES.NEUTRON },
  { name: 'Synthesize a Pion+', type: PARTICLE_TYPES.PION_PLUS },
  { name: 'Form a Hydrogen Atom', type: PARTICLE_TYPES.HYDROGEN },
  { name: 'Form a Deuterium Atom', type: PARTICLE_TYPES.DEUTERIUM },
  { name: 'Form a Helium Atom', type: PARTICLE_TYPES.HELIUM },
  { name: 'Form a Carbon Atom', type: PARTICLE_TYPES.CARBON },
  { name: 'Form a Nitrogen Atom', type: PARTICLE_TYPES.NITROGEN },
  { name: 'Form an Oxygen Atom', type: PARTICLE_TYPES.OXYGEN },
  { name: 'Form a Neon Atom', type: PARTICLE_TYPES.NEON },
  { name: 'Form a Sodium Atom', type: PARTICLE_TYPES.SODIUM },
  { name: 'Form a Silicon Atom', type: PARTICLE_TYPES.SILICON },
  { name: 'Form an Argon Atom', type: PARTICLE_TYPES.ARGON },
  { name: 'Induce Neutron Decay', type: PARTICLE_TYPES.DECAYING_NEUTRON },
  { name: 'Create an Excited Electron', type: PARTICLE_TYPES.EXCITED_ELECTRON },
  { name: 'Synthesize a Water Molecule', type: PARTICLE_TYPES.WATER },
  { name: 'Synthesize a Methane Molecule', type: PARTICLE_TYPES.METHANE },
  { name: 'Synthesize an Ammonia Molecule', type: PARTICLE_TYPES.AMMONIA },
  { name: 'Synthesize Carbon Dioxide', type: PARTICLE_TYPES.CARBON_DIOXIDE },
  { name: 'Synthesize Salt (NaCl)', type: PARTICLE_TYPES.SODIUM_CHLORIDE },
  { name: 'Synthesize a Lambda Baryon', type: PARTICLE_TYPES.LAMBDA_BARYON },
  { name: 'Synthesize a J/ψ Meson', type: PARTICLE_TYPES.J_PSI_MESON },
];
