// Centralized constants for particle types, colors and names.
// Extracted from your original file for easy maintenance.

export const PARTICLE_TYPES = {
  UP_QUARK: 'up-quark',
  DOWN_QUARK: 'down-quark',
  CHARM_QUARK: 'charm-quark',
  STRANGE_QUARK: 'strange-quark',
  TOP_QUARK: 'top-quark',
  BOTTOM_QUARK: 'bottom-quark',
  ELECTRON: 'electron',
  ELECTRON_NEUTRINO: 'electron-neutrino',
  PHOTON: 'photon',
  GLUON: 'gluon',
  W_BOSON: 'w-boson',
  Z_BOSON: 'z-boson',
  PROTON: 'proton',
  NEUTRON: 'neutron',
  HYDROGEN: 'hydrogen',
  DEUTERIUM: 'deuterium',
  TRITIUM: 'tritium',
  HELIUM: 'helium',
  LITHIUM: 'lithium',
  BERYLLIUM: 'beryllium',
  BORON: 'boron',
  CARBON: 'carbon',
  NITROGEN: 'nitrogen',
  OXYGEN: 'oxygen',
};

export const PARTICLE_COLORS = {
  [PARTICLE_TYPES.UP_QUARK]: 'bg-yellow-400',
  [PARTICLE_TYPES.DOWN_QUARK]: 'bg-indigo-400',
  [PARTICLE_TYPES.CHARM_QUARK]: 'bg-purple-500',
  [PARTICLE_TYPES.STRANGE_QUARK]: 'bg-green-500',
  [PARTICLE_TYPES.TOP_QUARK]: 'bg-cyan-500',
  [PARTICLE_TYPES.BOTTOM_QUARK]: 'bg-gray-700',
  [PARTICLE_TYPES.ELECTRON]: 'bg-blue-600',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: 'bg-gray-400',
  [PARTICLE_TYPES.PHOTON]: 'bg-yellow-300',
  [PARTICLE_TYPES.GLUON]: 'bg-black',
  [PARTICLE_TYPES.W_BOSON]: 'bg-orange-500',
  [PARTICLE_TYPES.Z_BOSON]: 'bg-red-700',
  [PARTICLE_TYPES.PROTON]: 'bg-red-500',
  [PARTICLE_TYPES.NEUTRON]: 'bg-pink-500',
  [PARTICLE_TYPES.HYDROGEN]: 'bg-teal-500',
  [PARTICLE_TYPES.DEUTERIUM]: 'bg-sky-600',
  [PARTICLE_TYPES.TRITIUM]: 'bg-violet-600',
  [PARTICLE_TYPES.HELIUM]: 'bg-orange-300',
  [PARTICLE_TYPES.LITHIUM]: 'bg-fuchsia-500',
  [PARTICLE_TYPES.BERYLLIUM]: 'bg-lime-500',
  [PARTICLE_TYPES.BORON]: 'bg-rose-500',
  [PARTICLE_TYPES.CARBON]: 'bg-gray-800',
  [PARTICLE_TYPES.NITROGEN]: 'bg-sky-500',
  [PARTICLE_TYPES.OXYGEN]: 'bg-red-600',
};

export const PARTICLE_NAMES = {
  [PARTICLE_TYPES.UP_QUARK]: 'Up',
  [PARTICLE_TYPES.DOWN_QUARK]: 'Down',
  [PARTICLE_TYPES.CHARM_QUARK]: 'Charm',
  [PARTICLE_TYPES.STRANGE_QUARK]: 'Strange',
  [PARTICLE_TYPES.TOP_QUARK]: 'Top',
  [PARTICLE_TYPES.BOTTOM_QUARK]: 'Bottom',
  [PARTICLE_TYPES.ELECTRON]: 'Electron',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: 'e-Neutrino',
  [PARTICLE_TYPES.PHOTON]: 'Photon',
  [PARTICLE_TYPES.GLUON]: 'Gluon',
  [PARTICLE_TYPES.W_BOSON]: 'W Boson',
  [PARTICLE_TYPES.Z_BOSON]: 'Z Boson',
  [PARTICLE_TYPES.PROTON]: 'Proton',
  [PARTICLE_TYPES.NEUTRON]: 'Neutron',
  [PARTICLE_TYPES.HYDROGEN]: 'Hydrogen',
  [PARTICLE_TYPES.DEUTERIUM]: 'Deuterium',
  [PARTICLE_TYPES.TRITIUM]: 'Tritium',
  [PARTICLE_TYPES.HELIUM]: 'Helium',
  [PARTICLE_TYPES.LITHIUM]: 'Lithium',
  [PARTICLE_TYPES.BERYLLIUM]: 'Beryllium',
  [PARTICLE_TYPES.BORON]: 'Boron',
  [PARTICLE_TYPES.CARBON]: 'Carbon',
  [PARTICLE_TYPES.NITROGEN]: 'Nitrogen',
  [PARTICLE_TYPES.OXYGEN]: 'Oxygen',
};

