// Centralized constants for particle types, colors and names.
// Extracted from your original file for easy maintenance.

export const PARTICLE_TYPES = {
  UP_QUARK: 'up-quark',
  DOWN_QUARK: 'down-quark',
  CHARM_QUARK: 'charm-quark',
  STRANGE_QUARK: 'strange-quark',
  TOP_QUARK: 'top-quark',
  BOTTOM_QUARK: 'bottom-quark',
  ELECTRON: 'electron',
  ELECTRON_NEUTRINO: 'electron-neutrino',
  PHOTON: 'photon',
  GLUON: 'gluon',
  W_BOSON: 'w-boson',
  Z_BOSON: 'z-boson',
  PROTON: 'proton',
  NEUTRON: 'neutron',
  HYDROGEN: 'hydrogen',
  DEUTERIUM: 'deuterium',
  TRITIUM: 'tritium',
  HELIUM: 'helium',
  LITHIUM: 'lithium',
  BERYLLIUM: 'beryllium',
  BORON: 'boron',
  CARBON: 'carbon',
  NITROGEN: 'nitrogen',
  OXYGEN: 'oxygen',
  FLUORINE: 'fluorine',
  NEON: 'neon',
  SODIUM: 'sodium',
  MAGNESIUM: 'magnesium',
  ALUMINIUM: 'aluminium',
  SILICON: 'silicon',
  PHOSPHORUS: 'phosphorus',
  SULFUR: 'sulfur',
  CHLORINE: 'chlorine',
  ARGON: 'argon',
  ANTI_UP_QUARK: 'anti-up-quark',
  ANTI_DOWN_QUARK: 'anti-down-quark',
  PION_PLUS: 'pion-plus',
  PION_MINUS: 'pion-minus',
  WATER: 'water',
  METHANE: 'methane',
  AMMONIA: 'ammonia',
  EXCITED_ELECTRON: 'excited-electron',
  ELECTRON_ANTINEUTRINO: 'electron-antineutrino',
  DECAYING_NEUTRON: 'decaying-neutron',
  CARBON_DIOXIDE: 'carbon-dioxide',
  SODIUM_CHLORIDE: 'sodium-chloride',
  HYDROCHLORIC_ACID: 'hydrochloric-acid',
  CARBON_MONOXIDE: 'carbon-monoxide',
  HYDROGEN_SULFIDE: 'hydrogen-sulfide',
  HYDROGEN_PEROXIDE: 'hydrogen-peroxide',
  ANTI_CHARM_QUARK: 'anti-charm-quark',
  LAMBDA_BARYON: 'lambda-baryon',
  J_PSI_MESON: 'j-psi-meson',
};

export const PARTICLE_COLORS = {
  [PARTICLE_TYPES.UP_QUARK]: 'bg-yellow-400',
  [PARTICLE_TYPES.DOWN_QUARK]: 'bg-indigo-400',
  [PARTICLE_TYPES.CHARM_QUARK]: 'bg-purple-500',
  [PARTICLE_TYPES.STRANGE_QUARK]: 'bg-green-500',
  [PARTICLE_TYPES.TOP_QUARK]: 'bg-cyan-500',
  [PARTICLE_TYPES.BOTTOM_QUARK]: 'bg-gray-700',
  [PARTICLE_TYPES.ELECTRON]: 'bg-blue-600',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: 'bg-gray-400',
  [PARTICLE_TYPES.PHOTON]: 'bg-yellow-300',
  [PARTICLE_TYPES.GLUON]: 'bg-black',
  [PARTICLE_TYPES.W_BOSON]: 'bg-orange-500',
  [PARTICLE_TYPES.Z_BOSON]: 'bg-red-700',
  [PARTICLE_TYPES.PROTON]: 'bg-red-500',
  [PARTICLE_TYPES.NEUTRON]: 'bg-pink-500',
  [PARTICLE_TYPES.HYDROGEN]: 'bg-teal-500',
  [PARTICLE_TYPES.DEUTERIUM]: 'bg-sky-600',
  [PARTICLE_TYPES.TRITIUM]: 'bg-violet-600',
  [PARTICLE_TYPES.HELIUM]: 'bg-orange-300',
  [PARTICLE_TYPES.LITHIUM]: 'bg-fuchsia-500',
  [PARTICLE_TYPES.BERYLLIUM]: 'bg-lime-500',
  [PARTICLE_TYPES.BORON]: 'bg-rose-500',
  [PARTICLE_TYPES.CARBON]: 'bg-gray-800',
  [PARTICLE_TYPES.NITROGEN]: 'bg-sky-500',
  [PARTICLE_TYPES.OXYGEN]: 'bg-red-600',
  [PARTICLE_TYPES.FLUORINE]: 'bg-emerald-500',
  [PARTICLE_TYPES.NEON]: 'bg-orange-600',
  [PARTICLE_TYPES.SODIUM]: 'bg-violet-500',
  [PARTICLE_TYPES.MAGNESIUM]: 'bg-lime-400',
  [PARTICLE_TYPES.ALUMINIUM]: 'bg-slate-400',
  [PARTICLE_TYPES.SILICON]: 'bg-stone-500',
  [PARTICLE_TYPES.PHOSPHORUS]: 'bg-red-400',
  [PARTICLE_TYPES.SULFUR]: 'bg-yellow-500',
  [PARTICLE_TYPES.CHLORINE]: 'bg-green-400',
  [PARTICLE_TYPES.ARGON]: 'bg-cyan-400',
  [PARTICLE_TYPES.ANTI_UP_QUARK]: 'bg-yellow-600',
  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: 'bg-indigo-600',
  [PARTICLE_TYPES.PION_PLUS]: 'bg-rose-400',
  [PARTICLE_TYPES.PION_MINUS]: 'bg-rose-600',
  [PARTICLE_TYPES.WATER]: 'bg-sky-400',
  [PARTICLE_TYPES.METHANE]: 'bg-cyan-600',
  [PARTICLE_TYPES.AMMONIA]: 'bg-slate-300',
  [PARTICLE_TYPES.EXCITED_ELECTRON]: 'bg-blue-400',
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: 'bg-gray-500',
  [PARTICLE_TYPES.DECAYING_NEUTRON]: 'bg-pink-400',
  [PARTICLE_TYPES.CARBON_DIOXIDE]: 'bg-gray-400',
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: 'bg-gray-200',
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: 'bg-cyan-200',
  [PARTICLE_TYPES.CARBON_MONOXIDE]: 'bg-gray-600',
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: 'bg-lime-300',
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: 'bg-sky-200',
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: 'bg-purple-700',
  [PARTICLE_TYPES.LAMBDA_BARYON]: 'bg-green-700',
  [PARTICLE_TYPES.J_PSI_MESON]: 'bg-violet-700',
};

export const PARTICLE_NAMES = {
  [PARTICLE_TYPES.UP_QUARK]: 'Up',
  [PARTICLE_TYPES.DOWN_QUARK]: 'Down',
  [PARTICLE_TYPES.CHARM_QUARK]: 'Charm',
  [PARTICLE_TYPES.STRANGE_QUARK]: 'Strange',
  [PARTICLE_TYPES.TOP_QUARK]: 'Top',
  [PARTICLE_TYPES.BOTTOM_QUARK]: 'Bottom',
  [PARTICLE_TYPES.ELECTRON]: 'Electron',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: 'e-Neutrino',
  [PARTICLE_TYPES.PHOTON]: 'Photon',
  [PARTICLE_TYPES.GLUON]: 'Gluon',
  [PARTICLE_TYPES.W_BOSON]: 'W Boson',
  [PARTICLE_TYPES.Z_BOSON]: 'Z Boson',
  [PARTICLE_TYPES.PROTON]: 'Proton',
  [PARTICLE_TYPES.NEUTRON]: 'Neutron',
  [PARTICLE_TYPES.HYDROGEN]: 'Hydrogen',
  [PARTICLE_TYPES.DEUTERIUM]: 'Deuterium',
  [PARTICLE_TYPES.TRITIUM]: 'Tritium',
  [PARTICLE_TYPES.HELIUM]: 'Helium',
  [PARTICLE_TYPES.LITHIUM]: 'Lithium',
  [PARTICLE_TYPES.BERYLLIUM]: 'Beryllium',
  [PARTICLE_TYPES.BORON]: 'Boron',
  [PARTICLE_TYPES.CARBON]: 'Carbon',
  [PARTICLE_TYPES.NITROGEN]: 'Nitrogen',
  [PARTICLE_TYPES.OXYGEN]: 'Oxygen',
  [PARTICLE_TYPES.FLUORINE]: 'Fluorine',
  [PARTICLE_TYPES.NEON]: 'Neon',
  [PARTICLE_TYPES.SODIUM]: 'Sodium',
  [PARTICLE_TYPES.MAGNESIUM]: 'Magnesium',
  [PARTICLE_TYPES.ALUMINIUM]: 'Aluminium',
  [PARTICLE_TYPES.SILICON]: 'Silicon',
  [PARTICLE_TYPES.PHOSPHORUS]: 'Phosphorus',
  [PARTICLE_TYPES.SULFUR]: 'Sulfur',
  [PARTICLE_TYPES.CHLORINE]: 'Chlorine',
  [PARTICLE_TYPES.ARGON]: 'Argon',
  [PARTICLE_TYPES.ANTI_UP_QUARK]: 'Anti-Up',
  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: 'Anti-Down',
  [PARTICLE_TYPES.PION_PLUS]: 'Pion+',
  [PARTICLE_TYPES.PION_MINUS]: 'Pion-',
  [PARTICLE_TYPES.WATER]: 'Water',
  [PARTICLE_TYPES.METHANE]: 'Methane',
  [PARTICLE_TYPES.AMMONIA]: 'Ammonia',
  [PARTICLE_TYPES.EXCITED_ELECTRON]: 'Excited e⁻',
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: 'e-Antineutrino',
  [PARTICLE_TYPES.DECAYING_NEUTRON]: 'Decaying Neutron',
  [PARTICLE_TYPES.CARBON_DIOXIDE]: 'Carbon Dioxide',
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: 'Salt (NaCl)',
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: 'HCl',
  [PARTICLE_TYPES.CARBON_MONOXIDE]: 'Carbon Monoxide',
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: 'H₂S',
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: 'H₂O₂',
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: 'Anti-Charm',
  [PARTICLE_TYPES.LAMBDA_BARYON]: 'Lambda (Λ)',
  [PARTICLE_TYPES.J_PSI_MESON]: 'J/ψ Meson',
};

export const PARTICLE_COLOR_MAP = {
  'yellow-400': '#fbbf24',
  'indigo-400': '#818cf8',
  'purple-500': '#a855f7',
  'green-500': '#22c55e',
  'cyan-500': '#06b6d4',
  'gray-700': '#374151',
  'blue-600': '#2563eb',
  'gray-400': '#9ca3af',
  'yellow-300': '#fde047',
  'black': '#000000',
  'orange-500': '#f97316',
  'red-700': '#b91c1c',
  'red-500': '#ef4444',
  'pink-500': '#ec4899',
  'teal-500': '#14b8a6',
  'sky-600': '#0284c7',
  'violet-600': '#7c3aed',
  'orange-300': '#fdba74',
  'fuchsia-500': '#d946ef',
  'lime-500': '#84cc16',
  'rose-500': '#f43f5e',
  'gray-800': '#1f2937',
  'sky-500': '#0ea5e9',
  'red-600': '#dc2626',
  'emerald-500': '#10b981',
  'orange-600': '#ea580c',
  'violet-500': '#8b5cf6',
  'lime-400': '#a3e635',
  'slate-400': '#94a3b8',
  'stone-500': '#78716c',
  'red-400': '#f87171',
  'yellow-500': '#eab308',
  'green-400': '#4ade80',
  'cyan-400': '#22d3ee',
  'yellow-600': '#d97706',
  'indigo-600': '#4f46e5',
  'rose-400': '#fb7185',
  'rose-600': '#e11d48',
  'orange-700': '#c2410c',
  'gray-600': '#4b5563',
  'sky-400': '#38bdf8',
  'cyan-600': '#0891b2',
  'slate-300': '#cbd5e1',
  'blue-400': '#60a5fa',
  'gray-500': '#6b7280',
  'pink-400': '#f472b6',
  'gray-200': '#e5e7eb',
  'cyan-200': '#a5f3fc',
  'lime-300': '#bef264',
  'sky-200': '#bae6fd',
  'purple-700': '#7e22ce',
  'green-700': '#15803d',
  'violet-700': '#6d28d9',
};
