// Centralized constants for particle types, colors and names.
// Extracted from your original file for easy maintenance.

export const PARTICLE_TYPES = {
  UP_QUARK: 'up-quark',
  DOWN_QUARK: 'down-quark',
  CHARM_QUARK: 'charm-quark',
  STRANGE_QUARK: 'strange-quark',
  TOP_QUARK: 'top-quark',
  BOTTOM_QUARK: 'bottom-quark',
  ELECTRON: 'electron',
  ELECTRON_NEUTRINO: 'electron-neutrino',
  PHOTON: 'photon',
  GLUON: 'gluon',
  W_BOSON: 'w-boson',
  Z_BOSON: 'z-boson',
  PROTON: 'proton',
  NEUTRON: 'neutron',
  HYDROGEN: 'hydrogen',
  DEUTERIUM: 'deuterium',
  TRITIUM: 'tritium',
  HELIUM: 'helium',
  LITHIUM: 'lithium',
  BERYLLIUM: 'beryllium',
  BORON: 'boron',
  CARBON: 'carbon',
  NITROGEN: 'nitrogen',
  OXYGEN: 'oxygen',
  FLUORINE: 'fluorine',
  NEON: 'neon',
  SODIUM: 'sodium',
  MAGNESIUM: 'magnesium',
  ALUMINIUM: 'aluminium',
  SILICON: 'silicon',
  PHOSPHORUS: 'phosphorus',
  SULFUR: 'sulfur',
  CHLORINE: 'chlorine',
  ARGON: 'argon',
  POTASSIUM: 'potassium',
  CALCIUM: 'calcium',
  SCANDIUM: 'scandium',
  TITANIUM: 'titanium',
  VANADIUM: 'vanadium',
  CHROMIUM: 'chromium',
  MANGANESE: 'manganese',
  IRON: 'iron',
  COBALT: 'cobalt',
  NICKEL: 'nickel',
  COPPER: 'copper',
  ZINC: 'zinc',
  GALLIUM: 'gallium',
  GERMANIUM: 'germanium',
  ARSENIC: 'arsenic',
  SELENIUM: 'selenium',
  BROMINE: 'bromine',
  KRYPTON: 'krypton',
  ANTI_UP_QUARK: 'anti-up-quark',
  ANTI_DOWN_QUARK: 'anti-down-quark',
  PION_PLUS: 'pion-plus',
  PION_MINUS: 'pion-minus',
  WATER: 'water',
  METHANE: 'methane',
  AMMONIA: 'ammonia',
  EXCITED_ELECTRON: 'excited-electron',
  ELECTRON_ANTINEUTRINO: 'electron-antineutrino',
  DECAYING_NEUTRON: 'decaying-neutron',
  CARBON_DIOXIDE: 'carbon-dioxide',
  SODIUM_CHLORIDE: 'sodium-chloride',
  HYDROCHLORIC_ACID: 'hydrochloric-acid',
  CARBON_MONOXIDE: 'carbon-monoxide',
  HYDROGEN_SULFIDE: 'hydrogen-sulfide',
  HYDROGEN_PEROXIDE: 'hydrogen-peroxide',
  ANTI_CHARM_QUARK: 'anti-charm-quark',
  LAMBDA_BARYON: 'lambda-baryon',
  J_PSI_MESON: 'j-psi-meson',
  OZONE: 'ozone',
  NITROUS_OXIDE: 'nitrous-oxide',
  SILICON_DIOXIDE: 'silicon-dioxide',
  GLYCINE: 'glycine',
  AYOUB: 'ayoub',
  GLYCYLGLYCINE: 'glycylglycine',
  SERINE: 'serine',
  ALANINE: 'alanine',
  GLYCYL_ALANINE: 'glycyl-alanine',
  ETHANOL: 'ethanol',
  SULFURIC_ACID: 'sulfuric-acid',
  ADENINE: 'adenine',
  GUANINE: 'guanine',
  CYTOSINE: 'cytosine',
  THYMINE: 'thymine',
  NITROGEN_GAS: 'nitrogen-gas',
  OXYGEN_GAS: 'oxygen-gas',
  ACETIC_ACID: 'acetic-acid',
  GLUCOSE: 'glucose',
  URACIL: 'uracil',
  VALINE: 'valine',
  LEUCINE: 'leucine',
  DNA: 'dna',
  RNA: 'rna',
  DEOXYRIBOSE: 'deoxyribose',
  RIBOSE: 'ribose',
  PHOSPHATE: 'phosphate',
  NUCLEOTIDE_A: 'nucleotide-a',
  NUCLEOTIDE_T: 'nucleotide-t',
  NUCLEOTIDE_G: 'nucleotide-g',
  NUCLEOTIDE_C: 'nucleotide-c',
  NUCLEOTIDE_U: 'nucleotide-u',
  ATP: 'atp',
  GLYCEROL: 'glycerol',
  FATTY_ACID: 'fatty-acid',
  LIPID: 'lipid',
};

export const PARTICLE_COLORS = {
  [PARTICLE_TYPES.UP_QUARK]: 'bg-cyan-400',
  [PARTICLE_TYPES.DOWN_QUARK]: 'bg-purple-500',
  [PARTICLE_TYPES.CHARM_QUARK]: 'bg-green-400',
  [PARTICLE_TYPES.STRANGE_QUARK]: 'bg-yellow-400',
  [PARTICLE_TYPES.TOP_QUARK]: 'bg-red-500',
  [PARTICLE_TYPES.BOTTOM_QUARK]: 'bg-blue-500',
  [PARTICLE_TYPES.ELECTRON]: 'bg-blue-600',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: 'bg-gray-400',
  [PARTICLE_TYPES.PHOTON]: 'bg-yellow-300',
  [PARTICLE_TYPES.GLUON]: 'bg-black',
  [PARTICLE_TYPES.W_BOSON]: 'bg-orange-500',
  [PARTICLE_TYPES.Z_BOSON]: 'bg-red-700',
  [PARTICLE_TYPES.PROTON]: 'bg-red-500',
  [PARTICLE_TYPES.NEUTRON]: 'bg-pink-500',
  [PARTICLE_TYPES.HYDROGEN]: 'bg-teal-500',
  [PARTICLE_TYPES.DEUTERIUM]: 'bg-sky-600',
  [PARTICLE_TYPES.TRITIUM]: 'bg-violet-600',
  [PARTICLE_TYPES.HELIUM]: 'bg-orange-300',
  [PARTICLE_TYPES.LITHIUM]: 'bg-fuchsia-500',
  [PARTICLE_TYPES.BERYLLIUM]: 'bg-lime-500',
  [PARTICLE_TYPES.BORON]: 'bg-rose-500',
  [PARTICLE_TYPES.CARBON]: 'bg-gray-800',
  [PARTICLE_TYPES.NITROGEN]: 'bg-sky-500',
  [PARTICLE_TYPES.OXYGEN]: 'bg-red-600',
  [PARTICLE_TYPES.FLUORINE]: 'bg-emerald-500',
  [PARTICLE_TYPES.NEON]: 'bg-orange-600',
  [PARTICLE_TYPES.SODIUM]: 'bg-violet-500',
  [PARTICLE_TYPES.MAGNESIUM]: 'bg-lime-400',
  [PARTICLE_TYPES.ALUMINIUM]: 'bg-slate-400',
  [PARTICLE_TYPES.SILICON]: 'bg-stone-500',
  [PARTICLE_TYPES.PHOSPHORUS]: 'bg-red-400',
  [PARTICLE_TYPES.SULFUR]: 'bg-yellow-500',
  [PARTICLE_TYPES.CHLORINE]: 'bg-green-400',
  [PARTICLE_TYPES.ARGON]: 'bg-cyan-400',
  [PARTICLE_TYPES.POTASSIUM]: 'bg-violet-400',
  [PARTICLE_TYPES.CALCIUM]: 'bg-slate-200',
  [PARTICLE_TYPES.SCANDIUM]: 'bg-cyan-300',
  [PARTICLE_TYPES.TITANIUM]: 'bg-slate-500',
  [PARTICLE_TYPES.VANADIUM]: 'bg-gray-400',
  [PARTICLE_TYPES.CHROMIUM]: 'bg-blue-300',
  [PARTICLE_TYPES.MANGANESE]: 'bg-rose-300',
  [PARTICLE_TYPES.IRON]: 'bg-orange-900',
  [PARTICLE_TYPES.COBALT]: 'bg-blue-800',
  [PARTICLE_TYPES.NICKEL]: 'bg-lime-300',
  [PARTICLE_TYPES.COPPER]: 'bg-orange-400',
  [PARTICLE_TYPES.ZINC]: 'bg-sky-200',
  [PARTICLE_TYPES.GALLIUM]: 'bg-fuchsia-400',
  [PARTICLE_TYPES.GERMANIUM]: 'bg-stone-400',
    [PARTICLE_TYPES.ARSENIC]: { size: 80, name: 'Arsenic', category: 'Atom', atomicNumber: 33, mass: '74.922 u', charge: '0 e', composition: '33 Protons, 42 Neutrons, 33 Electrons', description: 'A toxic metalloid. In biological systems, it disrupts ATP production by mimicking phosphate, causing cell death.' },
  [PARTICLE_TYPES.SELENIUM]: 'bg-slate-300',
  [PARTICLE_TYPES.BROMINE]: 'bg-red-800',
  [PARTICLE_TYPES.KRYPTON]: 'bg-violet-300',
  [PARTICLE_TYPES.ANTI_UP_QUARK]: 'bg-cyan-600',
  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: 'bg-purple-700',
  [PARTICLE_TYPES.PION_PLUS]: 'bg-rose-400',
  [PARTICLE_TYPES.PION_MINUS]: 'bg-rose-600',
  [PARTICLE_TYPES.WATER]: 'bg-sky-400',
  [PARTICLE_TYPES.METHANE]: 'bg-cyan-600',
  [PARTICLE_TYPES.AMMONIA]: 'bg-slate-300',
  [PARTICLE_TYPES.EXCITED_ELECTRON]: 'bg-blue-400',
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: 'bg-gray-500',
  [PARTICLE_TYPES.DECAYING_NEUTRON]: 'bg-pink-400',
  [PARTICLE_TYPES.CARBON_DIOXIDE]: 'bg-gray-400',
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: 'bg-gray-200',
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: 'bg-cyan-200',
  [PARTICLE_TYPES.CARBON_MONOXIDE]: 'bg-gray-600',
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: 'bg-lime-300',
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: 'bg-sky-200',
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: 'bg-purple-700',
  [PARTICLE_TYPES.LAMBDA_BARYON]: 'bg-green-700',
  [PARTICLE_TYPES.J_PSI_MESON]: 'bg-violet-700',
  [PARTICLE_TYPES.OZONE]: 'bg-sky-300',
  [PARTICLE_TYPES.NITROUS_OXIDE]: 'bg-indigo-300',
  [PARTICLE_TYPES.SILICON_DIOXIDE]: 'bg-stone-300',
  [PARTICLE_TYPES.GLYCINE]: 'bg-purple-600',
  [PARTICLE_TYPES.AYOUB]: 'bg-teal-500',
  [PARTICLE_TYPES.GLYCYLGLYCINE]: 'bg-fuchsia-700',
  [PARTICLE_TYPES.SERINE]: 'bg-pink-600',
  [PARTICLE_TYPES.ALANINE]: 'bg-green-600',
  [PARTICLE_TYPES.GLYCYL_ALANINE]: 'bg-rose-700',
  [PARTICLE_TYPES.ETHANOL]: 'bg-sky-300',
  [PARTICLE_TYPES.SULFURIC_ACID]: 'bg-yellow-700',
  [PARTICLE_TYPES.GLUCOSE]: 'bg-orange-400',
  [PARTICLE_TYPES.ADENINE]: 'bg-blue-400',
  [PARTICLE_TYPES.GUANINE]: 'bg-green-400',
  [PARTICLE_TYPES.CYTOSINE]: 'bg-orange-500',
  [PARTICLE_TYPES.THYMINE]: 'bg-red-400',
  [PARTICLE_TYPES.NITROGEN_GAS]: 'bg-sky-700',
  [PARTICLE_TYPES.OXYGEN_GAS]: 'bg-red-800',
  [PARTICLE_TYPES.ACETIC_ACID]: 'bg-stone-400',
  [PARTICLE_TYPES.VALINE]: 'bg-orange-600',
  [PARTICLE_TYPES.LEUCINE]: 'bg-yellow-600', // This was the duplicate color entry
  [PARTICLE_TYPES.URACIL]: 'bg-teal-400',
  [PARTICLE_TYPES.DNA]: 'bg-gradient-to-br from-blue-500 to-purple-600',
  [PARTICLE_TYPES.RNA]: 'bg-gradient-to-br from-orange-500 to-red-600',
  [PARTICLE_TYPES.DEOXYRIBOSE]: 'bg-amber-200',
  [PARTICLE_TYPES.RIBOSE]: 'bg-amber-300',
  [PARTICLE_TYPES.PHOSPHATE]: 'bg-orange-500',
  [PARTICLE_TYPES.NUCLEOTIDE_A]: 'bg-blue-500',
  [PARTICLE_TYPES.NUCLEOTIDE_T]: 'bg-red-500',
  [PARTICLE_TYPES.NUCLEOTIDE_G]: 'bg-green-500',
  [PARTICLE_TYPES.NUCLEOTIDE_C]: 'bg-orange-500',
  [PARTICLE_TYPES.NUCLEOTIDE_U]: 'bg-teal-500',
  [PARTICLE_TYPES.ATP]: 'bg-yellow-400',
  [PARTICLE_TYPES.GLYCEROL]: 'bg-cyan-200',
  [PARTICLE_TYPES.FATTY_ACID]: 'bg-stone-400',
  [PARTICLE_TYPES.LIPID]: 'bg-orange-300',
};

export const PARTICLE_NAMES = {
  [PARTICLE_TYPES.UP_QUARK]: 'Up',
  [PARTICLE_TYPES.DOWN_QUARK]: 'Down',
  [PARTICLE_TYPES.CHARM_QUARK]: 'Charm',
  [PARTICLE_TYPES.STRANGE_QUARK]: 'Strange',
  [PARTICLE_TYPES.TOP_QUARK]: 'Top',
  [PARTICLE_TYPES.BOTTOM_QUARK]: 'Bottom',
  [PARTICLE_TYPES.ELECTRON]: 'Electron',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: 'e-Neutrino',
  [PARTICLE_TYPES.PHOTON]: 'Photon',
  [PARTICLE_TYPES.GLUON]: 'Gluon',
  [PARTICLE_TYPES.W_BOSON]: 'W Boson',
  [PARTICLE_TYPES.Z_BOSON]: 'Z Boson',
  [PARTICLE_TYPES.PROTON]: 'Proton',
  [PARTICLE_TYPES.NEUTRON]: 'Neutron',
  [PARTICLE_TYPES.HYDROGEN]: 'Hydrogen',
  [PARTICLE_TYPES.DEUTERIUM]: 'Deuterium',
  [PARTICLE_TYPES.TRITIUM]: 'Tritium',
  [PARTICLE_TYPES.HELIUM]: 'Helium',
  [PARTICLE_TYPES.LITHIUM]: 'Lithium',
  [PARTICLE_TYPES.BERYLLIUM]: 'Beryllium',
  [PARTICLE_TYPES.BORON]: 'Boron',
  [PARTICLE_TYPES.CARBON]: 'Carbon',
  [PARTICLE_TYPES.NITROGEN]: 'Nitrogen',
  [PARTICLE_TYPES.OXYGEN]: 'Oxygen',
  [PARTICLE_TYPES.FLUORINE]: 'Fluorine',
  [PARTICLE_TYPES.NEON]: 'Neon',
  [PARTICLE_TYPES.SODIUM]: 'Sodium',
  [PARTICLE_TYPES.MAGNESIUM]: 'Magnesium',
  [PARTICLE_TYPES.ALUMINIUM]: 'Aluminium',
  [PARTICLE_TYPES.SILICON]: 'Silicon',
  [PARTICLE_TYPES.PHOSPHORUS]: 'Phosphorus',
  [PARTICLE_TYPES.SULFUR]: 'Sulfur',
  [PARTICLE_TYPES.CHLORINE]: 'Chlorine',
  [PARTICLE_TYPES.ARGON]: 'Argon',
  [PARTICLE_TYPES.POTASSIUM]: 'Potassium',
  [PARTICLE_TYPES.CALCIUM]: 'Calcium',
  [PARTICLE_TYPES.SCANDIUM]: 'Scandium',
  [PARTICLE_TYPES.TITANIUM]: 'Titanium',
  [PARTICLE_TYPES.VANADIUM]: 'Vanadium',
  [PARTICLE_TYPES.CHROMIUM]: 'Chromium',
  [PARTICLE_TYPES.MANGANESE]: 'Manganese',
  [PARTICLE_TYPES.IRON]: 'Iron',
  [PARTICLE_TYPES.COBALT]: 'Cobalt',
  [PARTICLE_TYPES.NICKEL]: 'Nickel',
  [PARTICLE_TYPES.COPPER]: 'Copper',
  [PARTICLE_TYPES.ZINC]: 'Zinc',
  [PARTICLE_TYPES.GALLIUM]: 'Gallium',
    [PARTICLE_TYPES.GERMANIUM]: 'Germanium',
    [PARTICLE_TYPES.ARSENIC]: 'Arsenic',
    [PARTICLE_TYPES.SELENIUM]: 'Selenium',  [PARTICLE_TYPES.BROMINE]: 'Bromine',
  [PARTICLE_TYPES.KRYPTON]: 'Krypton',
  [PARTICLE_TYPES.ANTI_UP_QUARK]: 'Anti-Up',
  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: 'Anti-Down',
  [PARTICLE_TYPES.PION_PLUS]: 'Pion+',
  [PARTICLE_TYPES.PION_MINUS]: 'Pion-',
  [PARTICLE_TYPES.WATER]: 'Water',
  [PARTICLE_TYPES.METHANE]: 'Methane',
  [PARTICLE_TYPES.AMMONIA]: 'Ammonia',
  [PARTICLE_TYPES.EXCITED_ELECTRON]: 'Excited e⁻',
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: 'e-Antineutrino',
  [PARTICLE_TYPES.DECAYING_NEUTRON]: 'Decaying Neutron',
  [PARTICLE_TYPES.CARBON_DIOXIDE]: 'Carbon Dioxide',
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: 'Salt (NaCl)',
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: 'HCl',
  [PARTICLE_TYPES.CARBON_MONOXIDE]: 'Carbon Monoxide',
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: 'H₂S',
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: 'H₂O₂',
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: 'Anti-Charm',
  [PARTICLE_TYPES.LAMBDA_BARYON]: 'Lambda (Λ)',
  [PARTICLE_TYPES.J_PSI_MESON]: 'J/ψ Meson',
  [PARTICLE_TYPES.OZONE]: 'Ozone',
  [PARTICLE_TYPES.NITROUS_OXIDE]: 'Nitrous Oxide',
  [PARTICLE_TYPES.SILICON_DIOXIDE]: 'Silica (SiO₂)',
  [PARTICLE_TYPES.GLYCINE]: 'Glycine',
  [PARTICLE_TYPES.AYOUB]: 'Ayoub',
  [PARTICLE_TYPES.GLYCYLGLYCINE]: 'Glycylglycine',
  [PARTICLE_TYPES.SERINE]: 'Serine',
  [PARTICLE_TYPES.ALANINE]: 'Alanine',
  [PARTICLE_TYPES.GLYCYL_ALANINE]: 'Glycyl-Alanine',
  [PARTICLE_TYPES.ETHANOL]: 'Ethanol',
  [PARTICLE_TYPES.SULFURIC_ACID]: 'Sulfuric Acid',
  [PARTICLE_TYPES.GLUCOSE]: 'Glucose',
  [PARTICLE_TYPES.ADENINE]: 'Adenine',
  [PARTICLE_TYPES.GUANINE]: 'Guanine',
  [PARTICLE_TYPES.CYTOSINE]: 'Cytosine',
  [PARTICLE_TYPES.THYMINE]: 'Thymine',
  [PARTICLE_TYPES.NITROGEN_GAS]: 'Nitrogen Gas',
  [PARTICLE_TYPES.OXYGEN_GAS]: 'Oxygen Gas',
  [PARTICLE_TYPES.ACETIC_ACID]: 'Acetic Acid',
  [PARTICLE_TYPES.VALINE]: 'Valine',
  [PARTICLE_TYPES.LEUCINE]: 'Leucine', // This was the duplicate name entry
  [PARTICLE_TYPES.URACIL]: 'Uracil',
  [PARTICLE_TYPES.DNA]: 'DNA',
  [PARTICLE_TYPES.RNA]: 'RNA',
  [PARTICLE_TYPES.DEOXYRIBOSE]: 'Deoxyribose',
  [PARTICLE_TYPES.RIBOSE]: 'Ribose',
  [PARTICLE_TYPES.PHOSPHATE]: 'Phosphate',
  [PARTICLE_TYPES.NUCLEOTIDE_A]: 'dAMP (Adenine Nuc.)',
  [PARTICLE_TYPES.NUCLEOTIDE_T]: 'dTMP (Thymine Nuc.)',
  [PARTICLE_TYPES.NUCLEOTIDE_G]: 'dGMP (Guanine Nuc.)',
  [PARTICLE_TYPES.NUCLEOTIDE_C]: 'dCMP (Cytosine Nuc.)',
  [PARTICLE_TYPES.NUCLEOTIDE_U]: 'UMP (Uracil Nuc.)',
  [PARTICLE_TYPES.ATP]: 'ATP (Energy)',
  [PARTICLE_TYPES.GLYCEROL]: 'Glycerol',
  [PARTICLE_TYPES.FATTY_ACID]: 'Fatty Acid',
  [PARTICLE_TYPES.LIPID]: 'Lipid (Fat)',
};

export const PARTICLE_INFO = {
  [PARTICLE_TYPES.UP_QUARK]: { size: 35, name: 'Up Quark', category: 'Quark (Fermion)', mass: '2.2 MeV/c²', charge: '+2/3 e', spin: '1/2', description: 'One of the fundamental building blocks of matter. Up quarks combine with down quarks to form protons and neutrons.' },
  [PARTICLE_TYPES.DOWN_QUARK]: { size: 35, name: 'Down Quark', category: 'Quark (Fermion)', mass: '4.7 MeV/c²', charge: '-1/3 e', spin: '1/2', description: 'Along with the up quark, it is a primary constituent of protons and neutrons.' },
  [PARTICLE_TYPES.CHARM_QUARK]: { size: 35, name: 'Charm Quark', category: 'Quark (Fermion)', mass: '1.27 GeV/c²', charge: '+2/3 e', spin: '1/2', description: 'A heavier type of quark. Particles containing charm quarks are called "charmed" particles. The J/ψ meson is a famous example.' },
  [PARTICLE_TYPES.STRANGE_QUARK]: { size: 35, name: 'Strange Quark', category: 'Quark (Fermion)', mass: '95 MeV/c²', charge: '-1/3 e', spin: '1/2', description: 'A third type of quark. Particles containing it are called "strange" particles because they had unexpectedly long lifetimes when first discovered. The Lambda baryon is a strange particle.' },
  [PARTICLE_TYPES.TOP_QUARK]: { size: 35, name: 'Top Quark', category: 'Quark (Fermion)', mass: '173.1 GeV/c²', charge: '+2/3 e', spin: '1/2', description: 'The most massive of all observed elementary particles. It is so heavy it decays almost instantly and does not form hadrons.' },
  [PARTICLE_TYPES.BOTTOM_QUARK]: { size: 35, name: 'Bottom Quark', category: 'Quark (Fermion)', mass: '4.18 GeV/c²', charge: '-1/3 e', spin: '1/2', description: 'The second-heaviest quark. It is a key component of bottomonium mesons and is studied in B-factories to understand CP violation.' },
  [PARTICLE_TYPES.ELECTRON]: { size: 60, name: 'Electron', category: 'Lepton (Fermion)', mass: '0.511 MeV/c²', charge: '-1 e', spin: '1/2', description: 'A stable elementary particle that orbits the nucleus of an atom. Its negative charge balances the positive charge of the protons.' },
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: { size: 60, name: 'Electron Neutrino', category: 'Lepton (Fermion)', mass: '< 1 eV/c²', charge: '0 e', spin: '1/2', description: 'A very light, neutral particle that interacts only through the weak force. Millions pass through you every second.' },
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: { size: 60, name: 'Electron Antineutrino', category: 'Lepton (Fermion)', mass: '< 1 eV/c²', charge: '0 e', spin: '1/2', description: 'The antimatter counterpart of the electron neutrino. It is produced in beta decay when a neutron turns into a proton.' },
  [PARTICLE_TYPES.EXCITED_ELECTRON]: { size: 60, name: 'Excited Electron', category: 'Excited State', charge: '-1 e', spin: '1/2', composition: 'Electron + Photon', description: 'An electron that has absorbed a photon and jumped to a higher energy level. This state is unstable and will quickly decay back to a stable state by emitting a photon.' },
  [PARTICLE_TYPES.ANTI_UP_QUARK]: { size: 35, name: 'Anti-Up Quark', category: 'Antiquark (Fermion)', mass: '2.2 MeV/c²', charge: '-2/3 e', spin: '1/2', description: 'The antimatter counterpart of the up quark. When a quark and its antiquark meet, they annihilate into energy.' },
  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: { size: 35, name: 'Anti-Down Quark', category: 'Antiquark (Fermion)', mass: '4.7 MeV/c²', charge: '+1/3 e', spin: '1/2', description: 'The antimatter counterpart of the down quark. It combines with quarks to form exotic particles like mesons.' },
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: { size: 35, name: 'Anti-Charm Quark', category: 'Antiquark (Fermion)', mass: '1.27 GeV/c²', charge: '-2/3 e', spin: '1/2', description: 'The antimatter counterpart of the charm quark. A charm and anti-charm quark pair can bind together to form "charmonium" states like the J/ψ meson.' },
  [PARTICLE_TYPES.PHOTON]: { size: 60, name: 'Photon', category: 'Gauge Boson', mass: '0', charge: '0 e', spin: '1', description: 'The quantum of the electromagnetic field, including light. It is the force carrier for the electromagnetic force, responsible for all electric and magnetic phenomena.' },
  [PARTICLE_TYPES.PROTON]: { size: 50, name: 'Proton', category: 'Baryon (Hadron)', mass: '938.3 MeV/c²', charge: '+1 e', spin: '1/2', composition: '2 Up Quarks, 1 Down Quark', description: 'A stable particle found in the nucleus of every atom. The number of protons determines an element\'s atomic number.' },
  [PARTICLE_TYPES.NEUTRON]: { size: 50, name: 'Neutron', category: 'Baryon (Hadron)', mass: '939.6 MeV/c²', charge: '0 e', spin: '1/2', composition: '1 Up Quark, 2 Down Quarks', description: 'A neutral particle found in the nucleus of most atoms. Neutrons contribute to atomic mass and nuclear stability.' },
  [PARTICLE_TYPES.DECAYING_NEUTRON]: { size: 50, name: 'Decaying Neutron', category: 'Unstable State', charge: '0 e', spin: '1/2', composition: 'Neutron + W Boson', description: 'A temporary, high-energy state created when a neutron interacts with a W boson. It rapidly undergoes beta decay, transforming into a proton, an electron, and an electron antineutrino.' },
  [PARTICLE_TYPES.PION_PLUS]: { size: 50, name: 'Pion+', category: 'Meson', mass: '139.6 MeV/c²', charge: '+1 e', spin: '0', composition: '1 Up Quark, 1 Anti-Down Quark', description: 'A type of meson, composed of a quark and an antiquark. Pions are the lightest mesons and play an important role in explaining the strong nuclear force at low energies.' },
  [PARTICLE_TYPES.PION_MINUS]: { size: 50, name: 'Pion-', category: 'Meson', mass: '139.6 MeV/c²', charge: '-1 e', spin: '0', composition: '1 Down Quark, 1 Anti-Up Quark', description: 'The antiparticle of the Pion+. It is also a meson and is involved in strong force interactions.' },
  [PARTICLE_TYPES.LAMBDA_BARYON]: { size: 50, name: 'Lambda (Λ) Baryon', category: 'Baryon (Hadron)', mass: '1115.7 MeV/c²', charge: '0 e', spin: '1/2', composition: '1 Up, 1 Down, 1 Strange Quark', description: 'An uncharged, strange baryon that is slightly more massive than a proton or neutron. It was one of the first "strange" particles to be discovered.' },
  [PARTICLE_TYPES.J_PSI_MESON]: { size: 50, name: 'J/ψ Meson', category: 'Meson (Quarkonium)', mass: '3096.9 MeV/c²', charge: '0 e', spin: '1', composition: '1 Charm, 1 Anti-Charm Quark', description: 'A flavorless meson whose discovery in 1974, known as the "November Revolution," proved the existence of the charm quark and helped solidify the Standard Model.' },
  [PARTICLE_TYPES.W_BOSON]: { size: 60, name: 'W Boson', category: 'Gauge Boson', mass: '80.4 GeV/c²', charge: '±1 e', spin: '1', description: 'One of the two particles that mediate the weak nuclear force. It is responsible for radioactive decay, such as beta decay, where a neutron turns into a proton.' },
  [PARTICLE_TYPES.GLUON]: { size: 60, name: 'Gluon', category: 'Gauge Boson', mass: '0', charge: '0 e', spin: '1', description: 'The force carrier of the strong nuclear force, which "glues" quarks together inside protons and neutrons. Unlike photons, gluons can interact with each other.' },
  [PARTICLE_TYPES.Z_BOSON]: { size: 60, name: 'Z Boson', category: 'Gauge Boson', mass: '91.2 GeV/c²', charge: '0 e', spin: '1', description: 'A neutral particle that also mediates the weak nuclear force. It is involved in processes where charge is not exchanged, such as neutrino scattering.' },
  [PARTICLE_TYPES.HYDROGEN]: { size: 80, name: 'Hydrogen', category: 'Atom', atomicNumber: 1, mass: '1.008 u', charge: '0 e', composition: '1 Proton, 1 Electron', description: 'The simplest and most abundant element in the universe, consisting of a single proton and a single electron.' },
  [PARTICLE_TYPES.DEUTERIUM]: { size: 80, name: 'Deuterium', category: 'Isotope', atomicNumber: 1, mass: '2.014 u', charge: '0 e', composition: '1 Proton, 1 Neutron, 1 Electron', description: 'A stable isotope of hydrogen, also known as "heavy hydrogen." Its nucleus contains one proton and one neutron. It is a key component in nuclear fusion research.' },
  [PARTICLE_TYPES.TRITIUM]: { size: 80, name: 'Tritium', category: 'Isotope', atomicNumber: 1, mass: '3.016 u', charge: '0 e', composition: '1 Proton, 2 Neutrons, 1 Electron', description: 'A radioactive isotope of hydrogen. Its nucleus contains one proton and two neutrons. It is used in self-powered lighting and as a tracer in biological research.' },
  [PARTICLE_TYPES.HELIUM]: { size: 80, name: 'Helium', category: 'Atom', atomicNumber: 2, mass: '4.0026 u', charge: '0 e', composition: '2 Protons, 2 Neutrons, 2 Electrons', description: 'The second lightest element. It is a noble gas, meaning it is chemically inert. It is the second most abundant element in the observable universe.' },
  [PARTICLE_TYPES.LITHIUM]: { size: 80, name: 'Lithium', category: 'Atom', atomicNumber: 3, mass: '6.94 u', charge: '0 e', composition: '3 Protons, 4 Neutrons, 3 Electrons', description: 'A soft, silvery-white alkali metal. It is the lightest metal and the least dense solid element. It is highly reactive and widely used in rechargeable batteries.' },
  [PARTICLE_TYPES.BERYLLIUM]: { size: 80, name: 'Beryllium', category: 'Atom', atomicNumber: 4, mass: '9.012 u', charge: '0 e', composition: '4 Protons, 5 Neutrons, 4 Electrons', description: 'A relatively rare, lightweight, and strong alkaline earth metal. It is used in alloys to make springs, gears, and high-performance aerospace components.' },
  [PARTICLE_TYPES.BORON]: { size: 80, name: 'Boron', category: 'Atom', atomicNumber: 5, mass: '10.81 u', charge: '0 e', composition: '5 Protons, 6 Neutrons, 5 Electrons', description: 'A metalloid with several forms. Boron filaments are used in high-strength materials for aerospace, and its compounds are found in everything from control rods of nuclear reactors to household cleaners.' },
  [PARTICLE_TYPES.CARBON]: { size: 80, name: 'Carbon', category: 'Atom', atomicNumber: 6, mass: '12.011 u', charge: '0 e', composition: '6 Protons, 6 Neutrons, 6 Electrons', description: 'The basis of all known life on Earth. Its ability to form four stable bonds allows it to create a vast variety of complex organic molecules.' },
  [PARTICLE_TYPES.NITROGEN]: { size: 80, name: 'Nitrogen', category: 'Atom', atomicNumber: 7, mass: '14.007 u', charge: '0 e', composition: '7 Protons, 7 Neutrons, 7 Electrons', description: 'The most abundant gas in Earth\'s atmosphere (about 78%). It is a crucial component of amino acids, and therefore proteins, and nucleic acids like DNA.' },
  [PARTICLE_TYPES.OXYGEN]: { size: 80, name: 'Oxygen', category: 'Atom', atomicNumber: 8, mass: '15.999 u', charge: '0 e', composition: '8 Protons, 8 Neutrons, 8 Electrons', description: 'A highly reactive nonmetal and an oxidizing agent that readily forms oxides with most elements. It is essential for respiration in most terrestrial life.' },
  [PARTICLE_TYPES.FLUORINE]: { size: 80, name: 'Fluorine', category: 'Atom', atomicNumber: 9, mass: '18.998 u', charge: '0 e', composition: '9 Protons, 10 Neutrons, 9 Electrons', description: 'The most electronegative and reactive of all elements. It is a pale yellow-green gas and is used in toothpaste and water supplies to prevent tooth decay.' },
  [PARTICLE_TYPES.NEON]: { size: 80, name: 'Neon', category: 'Atom', atomicNumber: 10, mass: '20.180 u', charge: '0 e', composition: '10 Protons, 10 Neutrons, 10 Electrons', description: 'A noble gas that gives a distinct reddish-orange glow when used in low-voltage neon glow lamps, high-voltage discharge tubes and advertising signs.' },
  [PARTICLE_TYPES.SODIUM]: { size: 80, name: 'Sodium', category: 'Atom', atomicNumber: 11, mass: '22.990 u', charge: '0 e', composition: '11 Protons, 12 Neutrons, 11 Electrons', description: 'A soft, silvery-white, highly reactive alkali metal. It is an essential element for animals for maintaining fluid balance and nerve function.' },
  [PARTICLE_TYPES.MAGNESIUM]: { size: 80, name: 'Magnesium', category: 'Atom', atomicNumber: 12, mass: '24.305 u', charge: '0 e', composition: '12 Protons, 12 Neutrons, 12 Electrons', description: 'An alkaline earth metal and the eighth-most-abundant element in the Earth\'s crust. It is essential for all cells and some 300 enzymes.' },
  [PARTICLE_TYPES.ALUMINIUM]: { size: 80, name: 'Aluminium', category: 'Atom', atomicNumber: 13, mass: '26.982 u', charge: '0 e', composition: '13 Protons, 14 Neutrons, 13 Electrons', description: 'A silvery-white, soft, non-magnetic and ductile metal. It is the third most abundant element in the Earth\'s crust and is widely used in aerospace, construction, and packaging.' },
  [PARTICLE_TYPES.SILICON]: { size: 80, name: 'Silicon', category: 'Atom', atomicNumber: 14, mass: '28.085 u', charge: '0 e', composition: '14 Protons, 14 Neutrons, 14 Electrons', description: 'A metalloid that is the second most abundant element in the Earth\'s crust. It is the basis of modern electronics and semiconductor technology.' },
  [PARTICLE_TYPES.PHOSPHORUS]: { size: 80, name: 'Phosphorus', category: 'Atom', atomicNumber: 15, mass: '30.974 u', charge: '0 e', composition: '15 Protons, 16 Neutrons, 15 Electrons', description: 'A highly reactive nonmetal essential for life. It is a component of DNA, RNA, ATP, and also the phospholipids that form all cell membranes.' },
  [PARTICLE_TYPES.SULFUR]: { size: 80, name: 'Sulfur', category: 'Atom', atomicNumber: 16, mass: '32.06 u', charge: '0 e', composition: '16 Protons, 16 Neutrons, 16 Electrons', description: 'An abundant, multivalent non-metal. Elemental sulfur is a bright yellow, crystalline solid at room temperature. It is an essential element for all life.' },
  [PARTICLE_TYPES.CHLORINE]: { size: 80, name: 'Chlorine', category: 'Atom', atomicNumber: 17, mass: '35.45 u', charge: '0 e', composition: '17 Protons, 18 Neutrons, 17 Electrons', description: 'A halogen that exists as a yellow-green gas at room temperature. It is a strong oxidizing agent used in disinfectants and bleach.' },
  [PARTICLE_TYPES.ARGON]: { size: 80, name: 'Argon', category: 'Atom', atomicNumber: 18, mass: '39.948 u', charge: '0 e', composition: '18 Protons, 22 Neutrons, 18 Electrons', description: 'A noble gas that is the third-most abundant gas in the Earth\'s atmosphere. It is often used in welding and incandescent lighting to provide an inert atmosphere.' },
  [PARTICLE_TYPES.WATER]: { size: 96, name: 'Water', category: 'Molecule', mass: '18.015 u', charge: '0 e', composition: '2 Hydrogen, 1 Oxygen', description: 'A polar molecule essential for all known forms of life. Its unique properties, like high surface tension and solvent capabilities, stem from its bent shape and hydrogen bonds.' },
  [PARTICLE_TYPES.METHANE]: { size: 96, name: 'Methane', category: 'Molecule', mass: '16.04 u', charge: '0 e', composition: '1 Carbon, 4 Hydrogen', description: 'The simplest alkane and the main component of natural gas. It is a potent greenhouse gas with a tetrahedral geometry.' },
  [PARTICLE_TYPES.AMMONIA]: { size: 96, name: 'Ammonia', category: 'Molecule', mass: '17.031 u', charge: '0 e', composition: '1 Nitrogen, 3 Hydrogen', description: 'A pungent gas that is a vital building block for many pharmaceuticals and is a key component in fertilizers. It has a trigonal pyramidal shape.' },
  [PARTICLE_TYPES.CARBON_DIOXIDE]: { size: 96, name: 'Carbon Dioxide', category: 'Molecule', mass: '44.01 u', charge: '0 e', composition: '1 Carbon, 2 Oxygen', description: 'A gas that is a natural part of Earth\'s atmosphere. It is used by plants for photosynthesis and is a major greenhouse gas. It has a linear structure.' },
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: { size: 96, name: 'Sodium Chloride', category: 'Ionic Compound', mass: '58.44 u', charge: '0 e', composition: '1 Sodium, 1 Chlorine', description: 'Commonly known as table salt. It is an ionic compound formed from sodium and chloride ions, held together by ionic bonds in a crystal lattice structure.' },
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: { size: 96, name: 'Hydrochloric Acid', category: 'Molecule / Acid', mass: '36.46 u', charge: '0 e', composition: '1 Hydrogen, 1 Chlorine', description: 'A strong, corrosive acid. It is the main component of gastric acid in the stomach, helping to digest food.' },
  [PARTICLE_TYPES.CARBON_MONOXIDE]: { size: 96, name: 'Carbon Monoxide', category: 'Molecule', mass: '28.01 u', charge: '0 e', composition: '1 Carbon, 1 Oxygen', description: 'A colorless, odorless, and tasteless flammable gas that is slightly less dense than air. It is toxic to humans when encountered in higher concentrations.' },
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: { size: 96, name: 'Hydrogen Sulfide', category: 'Molecule', mass: '34.08 u', charge: '0 e', composition: '2 Hydrogen, 1 Sulfur', description: 'A colorless, flammable gas known for its characteristic foul odor of rotten eggs. It is used as an agricultural disinfectant.' },
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: { size: 96, name: 'Hydrogen Peroxide', category: 'Molecule', mass: '34.01 u', charge: '0 e', composition: '2 Hydrogen, 2 Oxygen', description: 'A simple peroxide, it is a colorless liquid, slightly more viscous than water. It is used as an oxidizer, bleaching agent, and antiseptic.' },
  [PARTICLE_TYPES.OZONE]: { size: 96, name: 'Ozone', category: 'Molecule', mass: '48.00 u', charge: '0 e', composition: '3 Oxygen', description: 'An inorganic molecule with the chemical formula O₃. It is a pale blue gas with a distinctively pungent smell. It is an allotrope of oxygen that is much less stable than the diatomic allotrope O₂. In the stratosphere, it protects Earth from harmful UV radiation.' },
  [PARTICLE_TYPES.NITROUS_OXIDE]: { size: 96, name: 'Nitrous Oxide', category: 'Molecule', mass: '44.013 u', charge: '0 e', composition: '2 Nitrogen, 1 Oxygen', description: 'Commonly known as laughing gas, it is a chemical compound, an oxide of nitrogen with the formula N₂O. At room temperature, it is a colorless non-flammable gas, with a slight metallic scent and taste.' },
  [PARTICLE_TYPES.SILICON_DIOXIDE]: { size: 96, name: 'Silicon Dioxide (Silica)', category: 'Molecule', mass: '60.08 u', charge: '0 e', composition: '1 Silicon, 2 Oxygen', description: 'Also known as silica, it is an oxide of silicon with the chemical formula SiO₂. It is most commonly found in nature as quartz and in various living organisms. It is a principal component of most sand in the world.' },
  [PARTICLE_TYPES.HYDROGEN_FLUORIDE]: { size: 96, name: 'Hydrogen Fluoride', category: 'Molecule / Acid', mass: '20.01 u', charge: '0 e', composition: '1 Hydrogen, 1 Fluorine', description: 'A chemical compound with the chemical formula HF. This colorless gas or liquid is the principal industrial source of fluorine, often as an aqueous solution called hydrofluoric acid. It is an extremely dangerous and corrosive substance.' },
  [PARTICLE_TYPES.GLYCINE]: { size: 112, name: 'Glycine', category: 'Amino Acid', mass: '75.07 g/mol', charge: '0 e', composition: '2 Carbon, 5 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'The simplest amino acid, acting as a fundamental building block for proteins. In the central nervous system, it also functions as an inhibitory neurotransmitter.' },
  [PARTICLE_TYPES.ALANINE]: { size: 112, name: 'Alanine', category: 'Amino Acid', mass: '89.09 g/mol', charge: '0 e', composition: '3 Carbon, 7 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'A non-essential amino acid involved in sugar and acid metabolism, it boosts immunity and provides energy for muscle tissue, brain, and central nervous system.' },
  [PARTICLE_TYPES.SERINE]: { size: 112, name: 'Serine', category: 'Amino Acid', mass: '105.09 g/mol', charge: '0 e', composition: '3 Carbon, 7 Hydrogen, 1 Nitrogen, 3 Oxygen', description: 'A non-essential amino acid that plays a role in metabolism, the function of DNA and RNA, and the formation of phospholipids required for every cell.' },
  [PARTICLE_TYPES.VALINE]: { size: 112, name: 'Valine', category: 'Amino Acid', mass: '117.15 g/mol', charge: '0 e', composition: '5 Carbon, 11 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'An essential amino acid with a branched-chain structure, important for muscle growth, tissue repair, and energy production.' },
  [PARTICLE_TYPES.LEUCINE]: { size: 112, name: 'Leucine', category: 'Amino Acid', mass: '131.17 g/mol', charge: '0 e', composition: '6 Carbon, 13 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'An essential branched-chain amino acid (BCAA) that is critical for protein synthesis and muscle repair. It also helps regulate blood-sugar levels.' },
  [PARTICLE_TYPES.GLYCYLGLYCINE]: { size: 112, name: 'Glycylglycine', category: 'Dipeptide', mass: '132.12 g/mol', charge: '0 e', composition: 'Two Glycine molecules', description: 'The simplest dipeptide, formed from two molecules of glycine joined by a peptide bond. It is a common intermediate in protein metabolism.' },
  [PARTICLE_TYPES.GLYCYL_ALANINE]: { size: 112, name: 'Glycyl-Alanine', category: 'Dipeptide', mass: '146.14 g/mol', charge: '0 e', composition: 'Glycine + Alanine', description: 'A dipeptide formed from glycine and alanine. It serves as a building block for larger proteins and peptides.' },
  [PARTICLE_TYPES.AYOUB]: { size: 96, name: 'Ayoub', category: 'Molecule', mass: '42.0 g/mol', charge: '0 e', composition: '1 Carbon, 1 Nitrogen, 1 Oxygen, 2 Hydrogen', description: 'A special molecule.' },
  [PARTICLE_TYPES.ETHANOL]: { size: 96, name: 'Ethanol', category: 'Molecule / Alcohol', mass: '46.07 g/mol', charge: '0 e', composition: '2 Carbon, 6 Hydrogen, 1 Oxygen', description: 'Also known as drinking alcohol, it is a volatile, flammable, colorless liquid with a slight characteristic odor. It is a psychoactive substance and is the principal type of alcohol found in alcoholic beverages.' },
  [PARTICLE_TYPES.SULFURIC_ACID]: { size: 96, name: 'Sulfuric Acid', category: 'Molecule / Acid', mass: '98.079 g/mol', charge: '0 e', composition: '2 Hydrogen, 1 Sulfur, 4 Oxygen', description: 'A highly corrosive mineral acid, also known as "oil of vitriol". It is a diprotic acid and has a wide range of applications including fertilizer manufacture, ore processing, and as a cleaning agent.' },
  [PARTICLE_TYPES.GLUCOSE]: { size: 96, name: 'Glucose', category: 'Molecule / Carbohydrate', mass: '180.156 g/mol', charge: '0 e', composition: '6 Carbon, 12 Hydrogen, 6 Oxygen', description: 'A simple sugar which is an important energy source in living organisms and is a component of many carbohydrates. It is produced by plants during photosynthesis.' },
  [PARTICLE_TYPES.ADENINE]: { size: 96, name: 'Adenine', category: 'Nucleobase (Purine)', mass: '135.13 g/mol', charge: '0 e', composition: '5 Carbon, 5 Hydrogen, 5 Nitrogen', description: 'A purine nucleobase, one of the four main bases found in DNA and RNA. In DNA, it pairs with thymine.' },
  [PARTICLE_TYPES.GUANINE]: { size: 96, name: 'Guanine', category: 'Nucleobase (Purine)', mass: '151.13 g/mol', charge: '0 e', composition: '5 Carbon, 5 Hydrogen, 5 Nitrogen, 1 Oxygen', description: 'A purine nucleobase, one of the four main bases found in DNA and RNA. In DNA, it pairs with cytosine.' },
  [PARTICLE_TYPES.CYTOSINE]: { size: 96, name: 'Cytosine', category: 'Nucleobase (Pyrimidine)', mass: '111.10 g/mol', charge: '0 e', composition: '4 Carbon, 5 Hydrogen, 3 Nitrogen, 1 Oxygen', description: 'A pyrimidine nucleobase, one of the four main bases found in DNA and RNA. In DNA, it pairs with guanine.' },
  [PARTICLE_TYPES.THYMINE]: { size: 96, name: 'Thymine', category: 'Nucleobase (Pyrimidine)', mass: '126.11 g/mol', charge: '0 e', composition: '5 Carbon, 6 Hydrogen, 2 Nitrogen, 2 Oxygen', description: 'A pyrimidine nucleobase found in DNA, where it pairs with adenine. In RNA, thymine is replaced by uracil.' },
  [PARTICLE_TYPES.NITROGEN_GAS]: { size: 96, name: 'Nitrogen Gas (N₂)', category: 'Diatomic Molecule', mass: '28.014 u', charge: '0 e', composition: '2 Nitrogen', description: 'A colorless, odorless gas that makes up about 78% of Earth\'s atmosphere. The strong triple bond between the two nitrogen atoms makes it relatively inert.' },
  [PARTICLE_TYPES.OXYGEN_GAS]: { size: 96, name: 'Oxygen Gas (O₂)', category: 'Diatomic Molecule', mass: '31.998 u', charge: '0 e', composition: '2 Oxygen', description: 'A highly reactive diatomic molecule that is essential for the respiration of most life on Earth. It makes up about 21% of the atmosphere.' },
  [PARTICLE_TYPES.ACETIC_ACID]: { size: 96, name: 'Acetic Acid (Vinegar)', category: 'Molecule / Carboxylic Acid', mass: '60.052 g/mol', charge: '0 e', composition: '2 Carbon, 4 Hydrogen, 2 Oxygen', description: 'The main component of vinegar, giving it its sour taste and pungent smell. It is a widely used chemical reagent and industrial chemical.' },
  [PARTICLE_TYPES.URACIL]: { size: 96, name: 'Uracil', category: 'Nucleobase (Pyrimidine)', mass: '112.08 g/mol', charge: '0 e', composition: '4 Carbon, 4 Hydrogen, 2 Nitrogen, 2 Oxygen', description: 'A pyrimidine nucleobase found in RNA, where it pairs with adenine. It takes the place of thymine in the genetic code.' },
  [PARTICLE_TYPES.DNA]: { size: 180, name: 'DNA (Deoxyribonucleic Acid)', category: 'Nucleic Acid', mass: 'Variable', charge: 'Negative', composition: 'Adenine, Guanine, Cytosine, Thymine + Sugar-Phosphate Backbone', description: 'A molecule composed of two polynucleotide chains that coil around each other to form a double helix carrying genetic instructions for the development, functioning, growth and reproduction of all known organisms and many viruses.' },
  [PARTICLE_TYPES.RNA]: { size: 180, name: 'RNA (Ribonucleic Acid)', category: 'Nucleic Acid', mass: 'Variable', charge: 'Negative', composition: 'Adenine, Guanine, Cytosine, Uracil + Sugar-Phosphate Backbone', description: 'A nucleic acid present in all living cells. Its principal role is to act as a messenger carrying instructions from DNA for controlling the synthesis of proteins, although in some viruses RNA rather than DNA carries the genetic information.' },
  [PARTICLE_TYPES.DEOXYRIBOSE]: { size: 96, name: 'Deoxyribose', category: 'Sugar', description: 'A pentose sugar derived from ribose by the replacement of a hydroxyl group by hydrogen. It is the sugar component of DNA.' },
  [PARTICLE_TYPES.RIBOSE]: { size: 96, name: 'Ribose', category: 'Sugar', description: 'A pentose sugar occurring in nature as a component of RNA.' },
  [PARTICLE_TYPES.PHOSPHATE]: { size: 96, name: 'Phosphate Group', category: 'Functional Group', description: 'A functional group characterized by a phosphorus atom bonded to four oxygen atoms. It provides the energy for the backbone of DNA and RNA.' },
  [PARTICLE_TYPES.NUCLEOTIDE_A]: { size: 112, name: 'dAMP', category: 'Nucleotide', description: 'Deoxyadenosine monophosphate. A nucleotide found in DNA.' },
  [PARTICLE_TYPES.NUCLEOTIDE_T]: { size: 112, name: 'dTMP', category: 'Nucleotide', description: 'Deoxythymidine monophosphate. A nucleotide found in DNA.' },
  [PARTICLE_TYPES.NUCLEOTIDE_G]: { size: 112, name: 'dGMP', category: 'Nucleotide', description: 'Deoxyguanosine monophosphate. A nucleotide found in DNA.' },
  [PARTICLE_TYPES.NUCLEOTIDE_C]: { size: 112, name: 'dCMP', category: 'Nucleotide', description: 'Deoxycytidine monophosphate. A nucleotide found in DNA.' },
  [PARTICLE_TYPES.NUCLEOTIDE_U]: { size: 112, name: 'UMP', category: 'Nucleotide', description: 'Uridine monophosphate. A nucleotide found in RNA.' },
  [PARTICLE_TYPES.ATP]: { size: 128, name: 'Adenosine Triphosphate', category: 'Energy Carrier', description: 'The primary energy currency of the cell. It releases energy when its phosphate bonds are hydrolyzed.' },
  [PARTICLE_TYPES.GLYCEROL]: { size: 96, name: 'Glycerol', category: 'Polyol', description: 'A simple polyol compound. It is a colorless, odorless, viscous liquid that is sweet-tasting and non-toxic. It is the backbone of triglycerides.' },
  [PARTICLE_TYPES.FATTY_ACID]: { size: 96, name: 'Fatty Acid', category: 'Lipid Component', description: 'A carboxylic acid with a long aliphatic chain, which is either saturated or unsaturated.' },
  [PARTICLE_TYPES.LIPID]: { size: 128, name: 'Triglyceride', category: 'Lipid', description: 'An ester derived from glycerol and three fatty acids. Triglycerides are the main constituents of body fat in humans and other vertebrates.' },
};

export const PARTICLE_COLOR_MAP = {
  'yellow-400': '#fbbf24',
  'indigo-400': '#818cf8',
  'purple-500': '#a855f7',
  'green-500': '#22c55e',
  'cyan-500': '#06b6d4',
  'gray-700': '#374151',
  'blue-600': '#2563eb',
  'gray-400': '#9ca3af',
  'yellow-300': '#fde047',
  'black': '#000000',
  'orange-500': '#f97316',
  'red-700': '#b91c1c',
  'red-500': '#ef4444',
  'pink-500': '#ec4899',
  'teal-500': '#14b8a6',
  'sky-600': '#0284c7',
  'violet-600': '#7c3aed',
  'orange-300': '#fdba74',
  'fuchsia-500': '#d946ef',
  'lime-500': '#84cc16',
  'rose-500': '#f43f5e',
  'gray-800': '#1f2937',
  'sky-500': '#0ea5e9',
  'red-600': '#dc2626',
  'emerald-500': '#10b981',
  'orange-600': '#ea580c',
  'violet-500': '#8b5cf6',
  'lime-400': '#a3e635',
  'slate-400': '#94a3b8',
  'stone-500': '#78716c',
  'red-400': '#f87171',
  'yellow-500': '#eab308',
  'green-400': '#4ade80',
  'cyan-400': '#22d3ee',
  'violet-400': '#a78bfa',
  'slate-200': '#e2e8f0',
  'cyan-300': '#67e8f9',
  'slate-500': '#64748b',
  'blue-300': '#93c5fd',
  'rose-300': '#fecdd3',
  'orange-900': '#7c2d12',
  'blue-800': '#1e40af',
  'lime-300': '#bef264',
  'orange-400': '#fb923c',
  'sky-200': '#bae6fd',
  'fuchsia-400': '#e879f9',
  'stone-400': '#a8a29e',
  'slate-300': '#cbd5e1',
  'red-800': '#991b1b',
  'violet-300': '#c4b5fd',
  'yellow-600': '#d97706',
  'indigo-600': '#4f46e5',
  'rose-400': '#fb7185',
  'rose-600': '#e11d48',
  'orange-700': '#c2410c',
  'gray-600': '#4b5563',
  'sky-400': '#38bdf8',
  'cyan-600': '#0891b2',
  'slate-300': '#cbd5e1',
  'blue-400': '#60a5fa',
  'gray-500': '#6b7280',
  'pink-400': '#f472b6',
  'gray-200': '#e5e7eb',
  'cyan-200': '#a5f3fc',
  'lime-300': '#bef264',
  'sky-200': '#bae6fd',
  'purple-700': '#7e22ce',
  'green-700': '#15803d',
  'violet-700': '#6d28d9',
  'sky-300': '#7dd3fc',
  'indigo-300': '#a5b4fc',
  'stone-300': '#d6d3d1',
  'purple-600': '#9333ea',
  'teal-600': '#0d9488',
  'fuchsia-700': '#a21caf',
  'green-600': '#16a34a',
  'rose-700': '#be123c',
  'indigo-500': '#6366f1',
  'lime-600': '#4d7c0f',
  'yellow-700': '#a16207',
  'teal-400': '#2dd4bf',
};


export const CODEX_PARTICLES_BY_CATEGORY = [
  { name: 'Quarks', particles: [PARTICLE_TYPES.UP_QUARK, PARTICLE_TYPES.DOWN_QUARK, PARTICLE_TYPES.CHARM_QUARK, PARTICLE_TYPES.STRANGE_QUARK, PARTICLE_TYPES.TOP_QUARK, PARTICLE_TYPES.BOTTOM_QUARK] },
  { name: 'Anti-Quarks', particles: [PARTICLE_TYPES.ANTI_UP_QUARK, PARTICLE_TYPES.ANTI_DOWN_QUARK, PARTICLE_TYPES.ANTI_CHARM_QUARK] },
  { name: 'Leptons', particles: [PARTICLE_TYPES.ELECTRON, PARTICLE_TYPES.ELECTRON_NEUTRINO] },
  { name: 'Anti-Leptons', particles: [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO] },
  { name: 'Bosons', particles: [PARTICLE_TYPES.PHOTON, PARTICLE_TYPES.GLUON, PARTICLE_TYPES.W_BOSON, PARTICLE_TYPES.Z_BOSON] },
  {
    name: 'Hadrons & Secondary',
    particles: [
      PARTICLE_TYPES.PROTON,
      PARTICLE_TYPES.NEUTRON,
      PARTICLE_TYPES.PION_PLUS,
      PARTICLE_TYPES.PION_MINUS,
      PARTICLE_TYPES.LAMBDA_BARYON,
      PARTICLE_TYPES.J_PSI_MESON,
      PARTICLE_TYPES.EXCITED_ELECTRON,
      PARTICLE_TYPES.DECAYING_NEUTRON,
    ]
  },
  {
    name: 'Atoms',
    particles: [
      PARTICLE_TYPES.HYDROGEN,
      PARTICLE_TYPES.DEUTERIUM,
      PARTICLE_TYPES.TRITIUM,
      PARTICLE_TYPES.HELIUM,
      PARTICLE_TYPES.LITHIUM,
      PARTICLE_TYPES.BERYLLIUM,
      PARTICLE_TYPES.BORON,
      PARTICLE_TYPES.CARBON,
      PARTICLE_TYPES.NITROGEN,
      PARTICLE_TYPES.OXYGEN,
      PARTICLE_TYPES.FLUORINE,
      PARTICLE_TYPES.NEON,
      PARTICLE_TYPES.SODIUM,
      PARTICLE_TYPES.MAGNESIUM,
      PARTICLE_TYPES.ALUMINIUM,
      PARTICLE_TYPES.SILICON,
      PARTICLE_TYPES.PHOSPHORUS,
      PARTICLE_TYPES.SULFUR,
      PARTICLE_TYPES.CHLORINE,
      PARTICLE_TYPES.ARGON,
      PARTICLE_TYPES.POTASSIUM,
      PARTICLE_TYPES.CALCIUM,
      PARTICLE_TYPES.SCANDIUM,
      PARTICLE_TYPES.TITANIUM,
      PARTICLE_TYPES.VANADIUM,
      PARTICLE_TYPES.CHROMIUM,
      PARTICLE_TYPES.MANGANESE,
      PARTICLE_TYPES.IRON,
      PARTICLE_TYPES.COBALT,
      PARTICLE_TYPES.NICKEL,
      PARTICLE_TYPES.COPPER,
      PARTICLE_TYPES.ZINC,
      PARTICLE_TYPES.GALLIUM,
      PARTICLE_TYPES.GERMANIUM,
      PARTICLE_TYPES.ARSENIC,
      PARTICLE_TYPES.SELENIUM,
      PARTICLE_TYPES.BROMINE,
      PARTICLE_TYPES.KRYPTON,
    ]
  },
  {
    name: 'Molecules',
    particles: [
      PARTICLE_TYPES.WATER,
      PARTICLE_TYPES.METHANE,
      PARTICLE_TYPES.AMMONIA,
      PARTICLE_TYPES.CARBON_DIOXIDE,
      PARTICLE_TYPES.OZONE,
      PARTICLE_TYPES.HYDROGEN_PEROXIDE,
      PARTICLE_TYPES.HYDROCHLORIC_ACID,
      PARTICLE_TYPES.HYDROGEN_SULFIDE,
      PARTICLE_TYPES.NITROUS_OXIDE,
      PARTICLE_TYPES.CARBON_MONOXIDE,
      PARTICLE_TYPES.SODIUM_CHLORIDE,
      PARTICLE_TYPES.SILICON_DIOXIDE,
      PARTICLE_TYPES.ETHANOL,
      PARTICLE_TYPES.SULFURIC_ACID,
      PARTICLE_TYPES.GLUCOSE,
      PARTICLE_TYPES.ADENINE,
      PARTICLE_TYPES.GUANINE,
      PARTICLE_TYPES.CYTOSINE,
      PARTICLE_TYPES.THYMINE,
      PARTICLE_TYPES.NITROGEN_GAS,
      PARTICLE_TYPES.OXYGEN_GAS,
      PARTICLE_TYPES.ACETIC_ACID,
      PARTICLE_TYPES.URACIL,
      PARTICLE_TYPES.DEOXYRIBOSE,
      PARTICLE_TYPES.RIBOSE,
      PARTICLE_TYPES.PHOSPHATE,
      PARTICLE_TYPES.GLYCEROL,
      PARTICLE_TYPES.FATTY_ACID,
    ]
  },
  {
    name: 'Nucleic Acids',
    particles: [
      PARTICLE_TYPES.DNA,
      PARTICLE_TYPES.RNA,
    ]
  },
  {
    name: 'Amino Acids & Polypeptides',
    particles: [
      PARTICLE_TYPES.GLYCINE,
      PARTICLE_TYPES.SERINE,
      PARTICLE_TYPES.ALANINE,
      PARTICLE_TYPES.VALINE,
      PARTICLE_TYPES.LEUCINE,
      PARTICLE_TYPES.GLYCYLGLYCINE,
      PARTICLE_TYPES.GLYCYL_ALANINE,
    ]
  },
  {
    name: 'Nucleotides',
    particles: [
      PARTICLE_TYPES.ATP,
      PARTICLE_TYPES.NUCLEOTIDE_A,
      PARTICLE_TYPES.NUCLEOTIDE_T,
      PARTICLE_TYPES.NUCLEOTIDE_G,
      PARTICLE_TYPES.NUCLEOTIDE_C,
      PARTICLE_TYPES.NUCLEOTIDE_U,
    ]
  },
  {
    name: 'Lipids',
    particles: [
      PARTICLE_TYPES.LIPID,
    ]
  },
];

export const elementaryParticleGroups = {
  Quarks: [
    { id: 'up-1', type: PARTICLE_TYPES.UP_QUARK },
    { id: 'down-1', type: PARTICLE_TYPES.DOWN_QUARK },
    { id: 'charm-1', type: PARTICLE_TYPES.CHARM_QUARK },
    { id: 'strange-1', type: PARTICLE_TYPES.STRANGE_QUARK },
    { id: 'top-1', type: PARTICLE_TYPES.TOP_QUARK },
    { id: 'bottom-1', type: PARTICLE_TYPES.BOTTOM_QUARK },
  ],
  'Anti-Quarks': [
    { id: 'anti-up-1', type: PARTICLE_TYPES.ANTI_UP_QUARK },
    { id: 'anti-down-1', type: PARTICLE_TYPES.ANTI_DOWN_QUARK },
    { id: 'anti-charm-1', type: PARTICLE_TYPES.ANTI_CHARM_QUARK },
  ],
  Leptons: [
    { id: 'electron-1', type: PARTICLE_TYPES.ELECTRON },
    { id: 'electron-neutrino-1', type: PARTICLE_TYPES.ELECTRON_NEUTRINO },
  ],
  'Anti-Leptons': [
    { id: 'e-antineutrino-1', type: PARTICLE_TYPES.ELECTRON_ANTINEUTRINO },
  ],
  Bosons: [
    { id: 'photon-1', type: PARTICLE_TYPES.PHOTON },
    { id: 'gluon-1', type: PARTICLE_TYPES.GLUON },
    { id: 'w-boson-1', type: PARTICLE_TYPES.W_BOSON },
    { id: 'z-boson-1', type: PARTICLE_TYPES.Z_BOSON },
  ]
};
