import { PARTICLE_TYPES } from './particles.js';

// Map atomic number to particle type for easy lookup
export const ATOMIC_NUMBER_TO_TYPE = {
  1: PARTICLE_TYPES.HYDROGEN,
  2: PARTICLE_TYPES.HELIUM,
  3: PARTICLE_TYPES.LITHIUM,
  4: PARTICLE_TYPES.BERYLLIUM,
  5: PARTICLE_TYPES.BORON,
  6: PARTICLE_TYPES.CARBON,
  7: PARTICLE_TYPES.NITROGEN,
  8: PARTICLE_TYPES.OXYGEN,
  9: PARTICLE_TYPES.FLUORINE,
  10: PARTICLE_TYPES.NEON,
  11: PARTICLE_TYPES.SODIUM,
  12: PARTICLE_TYPES.MAGNESIUM,
  13: PARTICLE_TYPES.ALUMINIUM,
  14: PARTICLE_TYPES.SILICON,
  15: PARTICLE_TYPES.PHOSPHORUS,
  16: PARTICLE_TYPES.SULFUR,
  17: PARTICLE_TYPES.CHLORINE,
  18: PARTICLE_TYPES.ARGON,
  19: PARTICLE_TYPES.POTASSIUM,
  20: PARTICLE_TYPES.CALCIUM,
  21: PARTICLE_TYPES.SCANDIUM,
  22: PARTICLE_TYPES.TITANIUM,
  23: PARTICLE_TYPES.VANADIUM,
  24: PARTICLE_TYPES.CHROMIUM,
  25: PARTICLE_TYPES.MANGANESE,
  26: PARTICLE_TYPES.IRON,
  27: PARTICLE_TYPES.COBALT,
  28: PARTICLE_TYPES.NICKEL,
  29: PARTICLE_TYPES.COPPER,
  30: PARTICLE_TYPES.ZINC,
  31: PARTICLE_TYPES.GALLIUM,
  32: PARTICLE_TYPES.GERMANIUM,
  33: PARTICLE_TYPES.ARSENIC,
  34: PARTICLE_TYPES.SELENIUM,
  35: PARTICLE_TYPES.BROMINE,
  36: PARTICLE_TYPES.KRYPTON,
  47: PARTICLE_TYPES.SILVER,
  50: PARTICLE_TYPES.TIN,
  79: PARTICLE_TYPES.GOLD,
  82: PARTICLE_TYPES.LEAD,
};

// Defines the grid layout of the periodic table. 0 is an empty spacer.
// -1 is the Lanthanide series placeholder, -2 is the Actinide series placeholder.
export const PERIODIC_TABLE_LAYOUT = [
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2], // Period 1
  [3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9, 10], // Period 2
  [11, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 14, 15, 16, 17, 18], // Period 3
  [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36], // Period 4
  [0, 0, 0, 0, 0, 0, 0, 47, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0], // Period 5 (Custom/Partial)
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
  [0, 0, 0, 0, 0, 0, 0, 79, 0, 0, 82, 0, 0, 0, 0, 0, 0, 0], // Period 6 (Custom/Partial)
];

// Lanthanide and Actinide series (using atomic numbers)
// The component will render placeholders for numbers not yet in ATOMIC_NUMBER_TO_TYPE
export const LANTHANIDE_SERIES = Array.from({ length: 15 }, (_, i) => 57 + i); // 57-71
export const ACTINIDE_SERIES = Array.from({ length: 15 }, (_, i) => 89 + i); // 89-103

// A separate list for isotopes and other special secondary particles
export const ISOTOPE_AND_SPECIAL_LIST = [
  PARTICLE_TYPES.PROTON,
  PARTICLE_TYPES.NEUTRON,
  PARTICLE_TYPES.ANTI_PROTON,
  PARTICLE_TYPES.ANTI_NEUTRON,
  PARTICLE_TYPES.MUON,
  PARTICLE_TYPES.TAU,
  PARTICLE_TYPES.HIGGS_BOSON,
  PARTICLE_TYPES.PION_PLUS,
  PARTICLE_TYPES.PION_MINUS,
  PARTICLE_TYPES.LAMBDA_BARYON,
  PARTICLE_TYPES.J_PSI_MESON,
  PARTICLE_TYPES.DEUTERIUM,
  PARTICLE_TYPES.TRITIUM,
  PARTICLE_TYPES.HELIUM_3,
  PARTICLE_TYPES.CARBON_14,
  PARTICLE_TYPES.URANIUM_235,
  PARTICLE_TYPES.URANIUM_238,
];