import { PARTICLE_TYPES } from '../particles';

const {
  DNA, RNA, ATP, GLUCOSE, AMINO_ACID, PROTEIN, LIPID, PHOSPHOLIPID,
  MEMBRANE, RIBOSOME, MITOCHONDRION, NUCLEUS,
  POLYMERASE, LIPASE, WATER,
  NUCLEOTIDE_A, NUCLEOTIDE_T, NUCLEOTIDE_G, NUCLEOTIDE_C, NUCLEOTIDE_U,
  CARBON, HYDROGEN, NITROGEN, OXYGEN, SULFUR
} = PARTICLE_TYPES;

export const BIOLOGICAL_MATTER = {
  [AMINO_ACID]: { parents: [CARBON, HYDROGEN, NITROGEN, OXYGEN] },
  [PROTEIN]: { parents: [AMINO_ACID, ATP] },
  [DNA]: { parents: [NUCLEOTIDE_A, NUCLEOTIDE_T, NUCLEOTIDE_G, NUCLEOTIDE_C] },
  [RNA]: { parents: [NUCLEOTIDE_A, NUCLEOTIDE_U, NUCLEOTIDE_G, NUCLEOTIDE_C] },
  [MEMBRANE]: { parents: [PHOSPHOLIPID, PROTEIN] },
  [RIBOSOME]: { parents: [RNA, PROTEIN] },
  [MITOCHONDRION]: { parents: [MEMBRANE, ATP, DNA] },
  [NUCLEUS]: { parents: [MEMBRANE, DNA, PROTEIN] },
  [POLYMERASE]: { parents: [PROTEIN, ATP] }, // Biological Catalyst
  [LIPASE]: { parents: [PROTEIN, WATER] }, // Biological Catalyst
};
