// Centralized constants for particle types, colors and names.
// Extracted from your original file for easy maintenance.

export const PARTICLE_TYPES = {
  UP_QUARK: 'up-quark',
  DOWN_QUARK: 'down-quark',
  CHARM_QUARK: 'charm-quark',
  STRANGE_QUARK: 'strange-quark',
  TOP_QUARK: 'top-quark',
  BOTTOM_QUARK: 'bottom-quark',
  ELECTRON: 'electron',
  ELECTRON_NEUTRINO: 'electron-neutrino',
  PHOTON: 'photon',
  GLUON: 'gluon',
  W_BOSON: 'w-boson',
  Z_BOSON: 'z-boson',
  PROTON: 'proton',
  NEUTRON: 'neutron',
  HYDROGEN: 'hydrogen',
  DEUTERIUM: 'deuterium',
  TRITIUM: 'tritium',
  HELIUM: 'helium',
  LITHIUM: 'lithium',
  BERYLLIUM: 'beryllium',
  BORON: 'boron',
  CARBON: 'carbon',
  NITROGEN: 'nitrogen',
  OXYGEN: 'oxygen',
  FLUORINE: 'fluorine',
  NEON: 'neon',
  SODIUM: 'sodium',
  MAGNESIUM: 'magnesium',
  ALUMINIUM: 'aluminium',
  SILICON: 'silicon',
  PHOSPHORUS: 'phosphorus',
  SULFUR: 'sulfur',
  CHLORINE: 'chlorine',
  ARGON: 'argon',
  POTASSIUM: 'potassium',
  CALCIUM: 'calcium',
  SCANDIUM: 'scandium',
  TITANIUM: 'titanium',
  VANADIUM: 'vanadium',
  CHROMIUM: 'chromium',
  MANGANESE: 'manganese',
  IRON: 'iron',
  COBALT: 'cobalt',
  NICKEL: 'nickel',
  COPPER: 'copper',
  ZINC: 'zinc',
  GALLIUM: 'gallium',
  GERMANIUM: 'germanium',
  ARSENIC: 'arsenic',
  SELENIUM: 'selenium',
  BROMINE: 'bromine',
  KRYPTON: 'krypton',
  ANTI_UP_QUARK: 'anti-up-quark',
  ANTI_DOWN_QUARK: 'anti-down-quark',
  PION_PLUS: 'pion-plus',
  PION_MINUS: 'pion-minus',
  WATER: 'water',
  METHANE: 'methane',
  AMMONIA: 'ammonia',
  EXCITED_ELECTRON: 'excited-electron',
  ELECTRON_ANTINEUTRINO: 'electron-antineutrino',
  DECAYING_NEUTRON: 'decaying-neutron',
  CARBON_DIOXIDE: 'carbon-dioxide',
  SODIUM_CHLORIDE: 'sodium-chloride',
  SODIUM_HYDROXIDE: 'sodium-hydroxide',
  HYDROCHLORIC_ACID: 'hydrochloric-acid',
  NITRIC_ACID: 'nitric-acid',
  IRON_OXIDE: 'iron-oxide',
  IRON_SULFIDE: 'iron-sulfide',
  CARBON_MONOXIDE: 'carbon-monoxide',
  HYDROGEN_SULFIDE: 'hydrogen-sulfide',
  HYDROGEN_PEROXIDE: 'hydrogen-peroxide',
  ANTI_CHARM_QUARK: 'anti-charm-quark',
  LAMBDA_BARYON: 'lambda-baryon',
  J_PSI_MESON: 'j-psi-meson',
  OZONE: 'ozone',
  NITROUS_OXIDE: 'nitrous-oxide',
  SILICON_DIOXIDE: 'silicon-dioxide',
  GLYCINE: 'glycine',
  AYOUB: 'ayoub',
  GLYCYLGLYCINE: 'glycylglycine',
  INSULIN_FRAGMENT: 'insulin-fragment',
  HEMOGLOBIN_POCKET: 'hemoglobin-pocket',
  SERINE: 'serine',
  ALANINE: 'alanine',
  GLYCYL_ALANINE: 'glycyl-alanine',
  ETHANOL: 'ethanol',
  ETHYLENE: 'ethylene',
  BAKING_SODA: 'baking-soda',
  CARBONIC_ACID: 'carbonic-acid',
  AMMONIUM_HYDROXIDE: 'ammonium-hydroxide',
  ACETONE: 'acetone',
  METHANOL: 'methanol',
  PROPANE: 'propane',
  BUTANE: 'butane',
  SULFURIC_ACID: 'sulfuric-acid',
  ADENINE: 'adenine',
  GUANINE: 'guanine',
  CYTOSINE: 'cytosine',
  THYMINE: 'thymine',
  NITROGEN_GAS: 'nitrogen-gas',
  OXYGEN_GAS: 'oxygen-gas',
  ACETIC_ACID: 'acetic-acid',
  GLUCOSE: 'glucose',
  URACIL: 'uracil',
  VALINE: 'valine',
  LEUCINE: 'leucine',
  DNA: 'dna',
  RNA: 'rna',
  DEOXYRIBOSE: 'deoxyribose',
  RIBOSE: 'ribose',
  PHOSPHATE: 'phosphate',
  NUCLEOTIDE_A: 'nucleotide-a',
  NUCLEOTIDE_T: 'nucleotide-t',
  NUCLEOTIDE_G: 'nucleotide-g',
  NUCLEOTIDE_C: 'nucleotide-c',
  NUCLEOTIDE_U: 'nucleotide-u',
  ATP: 'atp',
  GLYCEROL: 'glycerol',
  FATTY_ACID: 'fatty-acid',
  LIPID: 'lipid',
  MEMBRANE: 'membrane',
  RIBOSOME: 'ribosome',
  MITOCHONDRION: 'mitochondrion',
  NUCLEUS: 'nucleus',
  BENZENE: 'benzene',
  CYSTEINE: 'cysteine',
  PHENYLALANINE: 'phenylalanine',
  HISTIDINE: 'histidine',
  ISOLEUCINE: 'isoleucine',
  LYSINE: 'lysine',
  METHIONINE: 'methionine',
  THREONINE: 'threonine',
  TRYPTOPHAN: 'tryptophan',
  ARGININE: 'arginine',
  ASPARAGINE: 'asparagine',
  ASPARTIC_ACID: 'aspartic-acid',
  GLUTAMIC_ACID: 'glutamic-acid',
  GLUTAMINE: 'glutamine',
  PROLINE: 'proline',
  TYROSINE: 'tyrosine',
  PHOSPHORIC_ACID: 'phosphoric-acid',
  CITRIC_ACID: 'citric-acid',
  UREA: 'urea',
  PYRUVATE: 'pyruvate',
  PHOSPHOLIPID: 'phospholipid',
  CELLULOSE: 'cellulose',
  NADH: 'nadh',
  CHOLESTEROL: 'cholesterol',
  HEME: 'heme',
  FRUCTOSE: 'fructose',
  FORMALDEHYDE: 'formaldehyde',
  ACETYLENE: 'acetylene',
  HYDROGEN_CYANIDE: 'hydrogen-cyanide',
  SULFUR_DIOXIDE: 'sulfur-dioxide',
  NITROGEN_DIOXIDE: 'nitrogen-dioxide',
  ETHYL_ACETATE: 'ethyl-acetate',
  POLYETHYLENE: 'polyethylene',
  POTASSIUM_PERMANGANATE: 'potassium-permanganate',
  HYDROGEN_FLUORIDE: 'hydrogen-fluoride',
  STEEL: 'steel',
  VINEGAR: 'vinegar',
  UNIVERSAL_INDICATOR: 'universal-indicator',
  HELIUM_3: 'helium-3',
  CARBON_14: 'carbon-14',
  URANIUM_235: 'uranium-235',
  URANIUM_238: 'uranium-238',
  HIGGS_BOSON: 'higgs-boson',
  MUON: 'muon',
  POSITRON: 'positron',
  TAU: 'tau',
  ANTI_PROTON: 'anti-proton',
  ANTI_NEUTRON: 'anti-neutron',
  SILVER: 'silver',
  GOLD: 'gold',
  LEAD: 'lead',
  TIN: 'tin',
  BRONZE: 'bronze',
  ALPHA_PARTICLE: 'alpha-particle',
  BETA_PARTICLE: 'beta-particle',
  GAMMA_RAY: 'gamma-ray',
  THORIUM: 'thorium',
  PROTACTINIUM: 'protactinium',
  THORIUM_231: 'thorium-231',
  THORIUM_234: 'thorium-234',
  PROTACTINIUM_231: 'protactinium-231',
  PROTACTINIUM_234: 'protactinium-234',
  URANIUM_234: 'uranium-234',
  THORIUM_230: 'thorium-230',
  ACTINIUM_227: 'actinium-227',
  RADIUM_226: 'radium-226',
  RADON_222: 'radon-222',
  POLONIUM_210: 'polonium-210',
  LEAD_206: 'lead-206',
  LEAD_207: 'lead-207',
  RADIUM: 'radium',
  RADON: 'radon',
  POLONIUM: 'polonium',
  PROTACTINIUM: 'protactinium',
  URANIUM: 'uranium',
  POLYMERASE: 'polymerase',
  LIPASE: 'lipase',
  AMINO_ACID: 'amino-acid',
  PROTEIN: 'protein',
  };

  export const PARTICLE_COLORS = {  [PARTICLE_TYPES.UP_QUARK]: '#22d3ee',
  [PARTICLE_TYPES.DOWN_QUARK]: '#a855f7',
  [PARTICLE_TYPES.CHARM_QUARK]: '#4ade80',
  [PARTICLE_TYPES.STRANGE_QUARK]: '#fbbf24',
  [PARTICLE_TYPES.TOP_QUARK]: '#ef4444',
  [PARTICLE_TYPES.BOTTOM_QUARK]: '#3b82f6',
  [PARTICLE_TYPES.ELECTRON]: '#2563eb',
  [PARTICLE_TYPES.POSITRON]: '#60a5fa',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: '#9ca3af',
  [PARTICLE_TYPES.PHOTON]: '#fde047',
  [PARTICLE_TYPES.GLUON]: '#000000',
  [PARTICLE_TYPES.W_BOSON]: '#f97316',
  [PARTICLE_TYPES.Z_BOSON]: '#b91c1c',
  [PARTICLE_TYPES.HIGGS_BOSON]: '#f472b6',
  [PARTICLE_TYPES.MUON]: '#3b82f6',
  [PARTICLE_TYPES.PROTON]: '#ef4444',
  [PARTICLE_TYPES.NEUTRON]: '#ec4899',
  [PARTICLE_TYPES.HYDROGEN]: '#ef4444',
  [PARTICLE_TYPES.DEUTERIUM]: '#0284c7',
  [PARTICLE_TYPES.TRITIUM]: '#7c3aed',
  [PARTICLE_TYPES.HELIUM]: '#f59e0b',
  [PARTICLE_TYPES.HELIUM_3]: '#fbbf24',
  [PARTICLE_TYPES.LITHIUM]: '#d946ef',
  [PARTICLE_TYPES.BERYLLIUM]: '#65a30d',
  [PARTICLE_TYPES.BORON]: '#e11d48',
  [PARTICLE_TYPES.CARBON]: '#1f2937',
  [PARTICLE_TYPES.CARBON_14]: '#374151',
  [PARTICLE_TYPES.NITROGEN]: '#4f46e5',
  [PARTICLE_TYPES.OXYGEN]: '#2563eb',
  [PARTICLE_TYPES.FLUORINE]: '#84cc16',
  [PARTICLE_TYPES.NEON]: '#ea580c',
  [PARTICLE_TYPES.SODIUM]: '#7c3aed',
  [PARTICLE_TYPES.MAGNESIUM]: '#4b5563',
  [PARTICLE_TYPES.ALUMINIUM]: '#64748b',
  [PARTICLE_TYPES.SILICON]: '#44403c',
  [PARTICLE_TYPES.PHOSPHORUS]: '#dc2626',
  [PARTICLE_TYPES.SULFUR]: '#ca8a04',
  [PARTICLE_TYPES.CHLORINE]: '#65a30d',
  [PARTICLE_TYPES.ARGON]: '#0891b2',
  [PARTICLE_TYPES.POTASSIUM]: '#8b5cf6',
  [PARTICLE_TYPES.CALCIUM]: '#475569',
  [PARTICLE_TYPES.SCANDIUM]: '#06b6d4',
  [PARTICLE_TYPES.TITANIUM]: '#334155',
  [PARTICLE_TYPES.VANADIUM]: '#71717a',
  [PARTICLE_TYPES.CHROMIUM]: '#1d4ed8',
  [PARTICLE_TYPES.MANGANESE]: '#db2777',
  [PARTICLE_TYPES.IRON]: '#374151',
  [PARTICLE_TYPES.COBALT]: '#1e3a8a',
  [PARTICLE_TYPES.NICKEL]: '#15803d',
  [PARTICLE_TYPES.COPPER]: '#c2410c',
  [PARTICLE_TYPES.ZINC]: '#0369a1',
  [PARTICLE_TYPES.GALLIUM]: '#c026d3',
  [PARTICLE_TYPES.GERMANIUM]: '#57534e',
  [PARTICLE_TYPES.ARSENIC]: '#7e22ce',
  [PARTICLE_TYPES.SELENIUM]: '#3f3f46',
  [PARTICLE_TYPES.BROMINE]: '#7f1d1d',
  [PARTICLE_TYPES.KRYPTON]: '#6d28d9',
  [PARTICLE_TYPES.SILVER]: '#94a3b8',
  [PARTICLE_TYPES.GOLD]: '#d97706',
  [PARTICLE_TYPES.LEAD]: '#475569',
  [PARTICLE_TYPES.TIN]: '#94a3b8',
  [PARTICLE_TYPES.BRONZE]: '#cd7f32',
  [PARTICLE_TYPES.URANIUM_235]: '#166534',
  [PARTICLE_TYPES.URANIUM_238]: '#064e3b',
  [PARTICLE_TYPES.ANTI_UP_QUARK]: '#0891b2',

  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: '#7e22ce',
  [PARTICLE_TYPES.PION_PLUS]: '#fb7185',
  [PARTICLE_TYPES.PION_MINUS]: '#e11d48',
  [PARTICLE_TYPES.WATER]: '#1d4ed8',
  [PARTICLE_TYPES.METHANE]: '#64748b',
  [PARTICLE_TYPES.AMMONIA]: '#0284c7',
  [PARTICLE_TYPES.EXCITED_ELECTRON]: '#3b82f6',
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: '#4b5563',
  [PARTICLE_TYPES.DECAYING_NEUTRON]: '#db2777',
  [PARTICLE_TYPES.CARBON_DIOXIDE]: '#4b5563',
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: '#475569',
  [PARTICLE_TYPES.SODIUM_HYDROXIDE]: '#4338ca',
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: '#15803d',
  [PARTICLE_TYPES.NITRIC_ACID]: '#a16207',
  [PARTICLE_TYPES.IRON_OXIDE]: '#7f1d1d',
  [PARTICLE_TYPES.IRON_SULFIDE]: '#1f2937',
  [PARTICLE_TYPES.CARBON_MONOXIDE]: '#1f2937',
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: '#4d7c0f',
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: '#0369a1',
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: '#7e22ce',
  [PARTICLE_TYPES.LAMBDA_BARYON]: '#15803d',
  [PARTICLE_TYPES.J_PSI_MESON]: '#6d28d9',
  [PARTICLE_TYPES.OZONE]: '#0369a1',
  [PARTICLE_TYPES.NITROUS_OXIDE]: '#4338ca',
  [PARTICLE_TYPES.SILICON_DIOXIDE]: '#57534e',
  [PARTICLE_TYPES.GLYCINE]: '#be185d',
  [PARTICLE_TYPES.AYOUB]: '#0d9488',
  [PARTICLE_TYPES.GLYCYLGLYCINE]: '#701a75',
  [PARTICLE_TYPES.SERINE]: '#be185d',
  [PARTICLE_TYPES.ALANINE]: '#15803d',
  [PARTICLE_TYPES.GLYCYL_ALANINE]: '#9f1239',
  [PARTICLE_TYPES.INSULIN_FRAGMENT]: '#3b82f6',
  [PARTICLE_TYPES.HEMOGLOBIN_POCKET]: '#b91c1c',
  [PARTICLE_TYPES.ETHANOL]: '#4b5563',
  [PARTICLE_TYPES.SULFURIC_ACID]: '#b45309',
  [PARTICLE_TYPES.GLUCOSE]: '#d97706',
  [PARTICLE_TYPES.ADENINE]: '#1d4ed8',
  [PARTICLE_TYPES.GUANINE]: '#15803d',
  [PARTICLE_TYPES.CYTOSINE]: '#c2410c',
  [PARTICLE_TYPES.THYMINE]: '#b91c1c',
  [PARTICLE_TYPES.NITROGEN_GAS]: '#1e3a8a',
  [PARTICLE_TYPES.OXYGEN_GAS]: '#7f1d1d',
  [PARTICLE_TYPES.ACETIC_ACID]: '#57534e',
  [PARTICLE_TYPES.VALINE]: '#92400e',
  [PARTICLE_TYPES.LEUCINE]: '#854d0e',
  [PARTICLE_TYPES.URACIL]: '#0d9488',
  [PARTICLE_TYPES.DNA]: '#1e40af', 
  [PARTICLE_TYPES.RNA]: '#c2410c',
  [PARTICLE_TYPES.DEOXYRIBOSE]: '#b45309',
  [PARTICLE_TYPES.RIBOSE]: '#ca8a04',
  [PARTICLE_TYPES.PHOSPHATE]: '#c2410c',
  [PARTICLE_TYPES.NUCLEOTIDE_A]: '#1e40af',
  [PARTICLE_TYPES.NUCLEOTIDE_T]: '#b91c1c',
  [PARTICLE_TYPES.NUCLEOTIDE_G]: '#15803d',
  [PARTICLE_TYPES.NUCLEOTIDE_C]: '#c2410c',
  [PARTICLE_TYPES.NUCLEOTIDE_U]: '#0d9488',
  [PARTICLE_TYPES.ATP]: '#ca8a04',
  [PARTICLE_TYPES.GLYCEROL]: '#0891b2',
  [PARTICLE_TYPES.FATTY_ACID]: '#57534e',
  [PARTICLE_TYPES.LIPID]: '#c2410c',
  [PARTICLE_TYPES.MEMBRANE]: '#9a3412',
  [PARTICLE_TYPES.RIBOSOME]: '#dc2626',
  [PARTICLE_TYPES.MITOCHONDRION]: '#9a3412',
  [PARTICLE_TYPES.NUCLEUS]: '#4338ca',
  [PARTICLE_TYPES.BENZENE]: '#3f3f46',
  [PARTICLE_TYPES.CYSTEINE]: '#854d0e',
  [PARTICLE_TYPES.PHENYLALANINE]: '#5b21b6',
  [PARTICLE_TYPES.HISTIDINE]: '#3730a3',
  [PARTICLE_TYPES.ISOLEUCINE]: '#854d0e',
  [PARTICLE_TYPES.LYSINE]: '#1e40af',
  [PARTICLE_TYPES.METHIONINE]: '#065f46',
  [PARTICLE_TYPES.THREONINE]: '#9f1239',
  [PARTICLE_TYPES.TRYPTOPHAN]: '#4c1d95',
  [PARTICLE_TYPES.ARGININE]: '#1e40af',
  [PARTICLE_TYPES.ASPARAGINE]: '#155e75',
  [PARTICLE_TYPES.ASPARTIC_ACID]: '#991b1b',
  [PARTICLE_TYPES.GLUTAMIC_ACID]: '#9f1239',
  [PARTICLE_TYPES.GLUTAMINE]: '#075985',
  [PARTICLE_TYPES.PROLINE]: '#065f46',
  [PARTICLE_TYPES.TYROSINE]: '#3730a3',
  [PARTICLE_TYPES.PHOSPHORIC_ACID]: '#c2410c',
  [PARTICLE_TYPES.CITRIC_ACID]: '#ca8a04',
  [PARTICLE_TYPES.UREA]: '#44403c',
  [PARTICLE_TYPES.PYRUVATE]: '#b45309',
  [PARTICLE_TYPES.PHOSPHOLIPID]: '#c2410c',
  [PARTICLE_TYPES.CELLULOSE]: '#065f46',
  [PARTICLE_TYPES.NADH]: '#3730a3',
  [PARTICLE_TYPES.CHOLESTEROL]: '#854d0e',
  [PARTICLE_TYPES.HEME]: '#450a0a',
  [PARTICLE_TYPES.FRUCTOSE]: '#db2777',
  [PARTICLE_TYPES.FORMALDEHYDE]: '#52525b',
  [PARTICLE_TYPES.ACETYLENE]: '#3f3f46',
  [PARTICLE_TYPES.HYDROGEN_CYANIDE]: '#164e63',
  [PARTICLE_TYPES.SULFUR_DIOXIDE]: '#ca8a04',
  [PARTICLE_TYPES.NITROGEN_DIOXIDE]: '#7c2d12',
  [PARTICLE_TYPES.ETHYL_ACETATE]: '#4b5563',
  [PARTICLE_TYPES.POLYETHYLENE]: '#64748b',
  [PARTICLE_TYPES.POTASSIUM_PERMANGANATE]: '#581c87',
  [PARTICLE_TYPES.HYDROGEN_FLUORIDE]: '#166534',
  [PARTICLE_TYPES.STEEL]: '#334155',
  [PARTICLE_TYPES.VINEGAR]: '#b45309',
  [PARTICLE_TYPES.UNIVERSAL_INDICATOR]: '#15803d',
  [PARTICLE_TYPES.ALPHA_PARTICLE]: '#f59e0b',
  [PARTICLE_TYPES.BETA_PARTICLE]: '#2563eb',
  [PARTICLE_TYPES.GAMMA_RAY]: '#ffffff',
  [PARTICLE_TYPES.THORIUM]: '#065f46',
  [PARTICLE_TYPES.PROTACTINIUM]: '#064e3b',
  [PARTICLE_TYPES.THORIUM_231]: '#065f46',
  [PARTICLE_TYPES.THORIUM_234]: '#065f46',
  [PARTICLE_TYPES.PROTACTINIUM_231]: '#064e3b',
  [PARTICLE_TYPES.PROTACTINIUM_234]: '#064e3b',
  [PARTICLE_TYPES.URANIUM_234]: '#166534',
  [PARTICLE_TYPES.THORIUM_230]: '#065f46',
  [PARTICLE_TYPES.ACTINIUM_227]: '#10b981',
  [PARTICLE_TYPES.RADIUM]: '#86efac',
  [PARTICLE_TYPES.RADIUM_226]: '#86efac',
  [PARTICLE_TYPES.RADON]: '#c084fc',
  [PARTICLE_TYPES.RADON_222]: '#c084fc',
  [PARTICLE_TYPES.POLONIUM]: '#cbd5e1',
  [PARTICLE_TYPES.POLONIUM_210]: '#cbd5e1',
  [PARTICLE_TYPES.LEAD_206]: '#475569',
  [PARTICLE_TYPES.LEAD_207]: '#475569',
  [PARTICLE_TYPES.POLYMERASE]: '#d946ef',
  [PARTICLE_TYPES.LIPASE]: '#2dd4bf',
};

export const PARTICLE_NAMES = {
  [PARTICLE_TYPES.UP_QUARK]: 'Up',
  [PARTICLE_TYPES.DOWN_QUARK]: 'Down',
  [PARTICLE_TYPES.CHARM_QUARK]: 'Charm',
  [PARTICLE_TYPES.STRANGE_QUARK]: 'Strange',
  [PARTICLE_TYPES.TOP_QUARK]: 'Top',
  [PARTICLE_TYPES.BOTTOM_QUARK]: 'Bottom',
  [PARTICLE_TYPES.ELECTRON]: 'Electron',
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: 'e-Neutrino',
  [PARTICLE_TYPES.PHOTON]: 'Photon',
  [PARTICLE_TYPES.GLUON]: 'Gluon',
  [PARTICLE_TYPES.W_BOSON]: 'W Boson',
  [PARTICLE_TYPES.Z_BOSON]: 'Z Boson',
  [PARTICLE_TYPES.PROTON]: 'Proton',
  [PARTICLE_TYPES.NEUTRON]: 'Neutron',
  [PARTICLE_TYPES.HYDROGEN]: 'Hydrogen',
  [PARTICLE_TYPES.DEUTERIUM]: 'Deuterium',
  [PARTICLE_TYPES.TRITIUM]: 'Tritium',
  [PARTICLE_TYPES.HELIUM]: 'Helium',
  [PARTICLE_TYPES.LITHIUM]: 'Lithium',
  [PARTICLE_TYPES.BERYLLIUM]: 'Beryllium',
  [PARTICLE_TYPES.BORON]: 'Boron',
  [PARTICLE_TYPES.CARBON]: 'Carbon',
  [PARTICLE_TYPES.NITROGEN]: 'Nitrogen',
  [PARTICLE_TYPES.OXYGEN]: 'Oxygen',
  [PARTICLE_TYPES.FLUORINE]: 'Fluorine',
  [PARTICLE_TYPES.NEON]: 'Neon',
  [PARTICLE_TYPES.SODIUM]: 'Sodium',
  [PARTICLE_TYPES.MAGNESIUM]: 'Magnesium',
  [PARTICLE_TYPES.ALUMINIUM]: 'Aluminium',
  [PARTICLE_TYPES.SILICON]: 'Silicon',
  [PARTICLE_TYPES.PHOSPHORUS]: 'Phosphorus',
  [PARTICLE_TYPES.SULFUR]: 'Sulfur',
  [PARTICLE_TYPES.CHLORINE]: 'Chlorine',
  [PARTICLE_TYPES.ARGON]: 'Argon',
  [PARTICLE_TYPES.POTASSIUM]: 'Potassium',
  [PARTICLE_TYPES.CALCIUM]: 'Calcium',
  [PARTICLE_TYPES.SCANDIUM]: 'Scandium',
  [PARTICLE_TYPES.TITANIUM]: 'Titanium',
  [PARTICLE_TYPES.VANADIUM]: 'Vanadium',
  [PARTICLE_TYPES.CHROMIUM]: 'Chromium',
  [PARTICLE_TYPES.MANGANESE]: 'Manganese',
  [PARTICLE_TYPES.IRON]: 'Iron',
  [PARTICLE_TYPES.COBALT]: 'Cobalt',
  [PARTICLE_TYPES.NICKEL]: 'Nickel',
  [PARTICLE_TYPES.COPPER]: 'Copper',
  [PARTICLE_TYPES.ZINC]: 'Zinc',
  [PARTICLE_TYPES.GALLIUM]: 'Gallium',
  [PARTICLE_TYPES.GERMANIUM]: 'Germanium',
  [PARTICLE_TYPES.ARSENIC]: 'Arsenic',
  [PARTICLE_TYPES.SELENIUM]: 'Selenium',
  [PARTICLE_TYPES.BROMINE]: 'Bromine',
  [PARTICLE_TYPES.KRYPTON]: 'Krypton',
  [PARTICLE_TYPES.ANTI_UP_QUARK]: 'Anti-Up',
  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: 'Anti-Down',
  [PARTICLE_TYPES.PION_PLUS]: 'Pion+',
  [PARTICLE_TYPES.PION_MINUS]: 'Pion-',
  [PARTICLE_TYPES.WATER]: 'Water',
  [PARTICLE_TYPES.METHANE]: 'Methane',
  [PARTICLE_TYPES.AMMONIA]: 'Ammonia',
  [PARTICLE_TYPES.EXCITED_ELECTRON]: 'Excited e⁻',
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: 'e-Antineutrino',
  [PARTICLE_TYPES.DECAYING_NEUTRON]: 'Decaying Neutron',
  [PARTICLE_TYPES.CARBON_DIOXIDE]: 'Carbon Dioxide',
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: 'Salt',
  [PARTICLE_TYPES.SODIUM_HYDROXIDE]: 'Sodium Hydroxide',
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: 'HCl',
  [PARTICLE_TYPES.NITRIC_ACID]: 'Nitric Acid',
  [PARTICLE_TYPES.IRON_OXIDE]: 'Iron Oxide',
  [PARTICLE_TYPES.IRON_SULFIDE]: 'Iron Sulfide',
  [PARTICLE_TYPES.CARBON_MONOXIDE]: 'Carbon Monoxide',
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: 'H₂S',
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: 'H₂O₂',
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: 'Anti-Charm',
  [PARTICLE_TYPES.LAMBDA_BARYON]: 'Lambda (Λ)',
  [PARTICLE_TYPES.J_PSI_MESON]: 'J/ψ Meson',
  [PARTICLE_TYPES.OZONE]: 'Ozone',
  [PARTICLE_TYPES.NITROUS_OXIDE]: 'Nitrous Oxide',
  [PARTICLE_TYPES.SILICON_DIOXIDE]: 'Silica (SiO₂)',
  [PARTICLE_TYPES.GLYCINE]: 'Glycine',
  [PARTICLE_TYPES.AYOUB]: 'Ayoub',
  [PARTICLE_TYPES.GLYCYLGLYCINE]: 'Glycylglycine',
  [PARTICLE_TYPES.SERINE]: 'Serine',
  [PARTICLE_TYPES.ALANINE]: 'Alanine',
  [PARTICLE_TYPES.GLYCYL_ALANINE]: 'Glycyl-Alanine',
  [PARTICLE_TYPES.ETHANOL]: 'Ethanol',
  [PARTICLE_TYPES.SULFURIC_ACID]: 'Sulfuric Acid',
  [PARTICLE_TYPES.GLUCOSE]: 'Glucose',
  [PARTICLE_TYPES.ADENINE]: 'Adenine',
  [PARTICLE_TYPES.GUANINE]: 'Guanine',
  [PARTICLE_TYPES.CYTOSINE]: 'Cytosine',
  [PARTICLE_TYPES.THYMINE]: 'Thymine',
  [PARTICLE_TYPES.NITROGEN_GAS]: 'Nitrogen Gas',
  [PARTICLE_TYPES.OXYGEN_GAS]: 'Oxygen Gas',
  [PARTICLE_TYPES.ACETIC_ACID]: 'Acetic Acid',
  [PARTICLE_TYPES.VALINE]: 'Valine',
  [PARTICLE_TYPES.LEUCINE]: 'Leucine',
  [PARTICLE_TYPES.URACIL]: 'Uracil',
  [PARTICLE_TYPES.DNA]: 'DNA',
  [PARTICLE_TYPES.RNA]: 'RNA',
  [PARTICLE_TYPES.DEOXYRIBOSE]: 'Deoxyribose',
  [PARTICLE_TYPES.RIBOSE]: 'Ribose',
  [PARTICLE_TYPES.PHOSPHATE]: 'Phosphate',
  [PARTICLE_TYPES.NUCLEOTIDE_A]: 'dAMP',
  [PARTICLE_TYPES.NUCLEOTIDE_T]: 'dTMP',
  [PARTICLE_TYPES.NUCLEOTIDE_G]: 'dGMP',
  [PARTICLE_TYPES.NUCLEOTIDE_C]: 'dCMP',
  [PARTICLE_TYPES.NUCLEOTIDE_U]: 'UMP',
  [PARTICLE_TYPES.ATP]: 'ATP',
  [PARTICLE_TYPES.GLYCEROL]: 'Glycerol',
  [PARTICLE_TYPES.FATTY_ACID]: 'Fatty Acid',
  [PARTICLE_TYPES.LIPID]: 'Lipid',
  [PARTICLE_TYPES.MEMBRANE]: 'Cell Membrane',
  [PARTICLE_TYPES.RIBOSOME]: 'Ribosome',
  [PARTICLE_TYPES.MITOCHONDRION]: 'Mitochondrion',
  [PARTICLE_TYPES.NUCLEUS]: 'Cell Nucleus',
  [PARTICLE_TYPES.BENZENE]: 'Benzene',
  [PARTICLE_TYPES.CYSTEINE]: 'Cysteine',
  [PARTICLE_TYPES.PHENYLALANINE]: 'Phenylalanine',
  [PARTICLE_TYPES.HISTIDINE]: 'Histidine',
  [PARTICLE_TYPES.ISOLEUCINE]: 'Isoleucine',
  [PARTICLE_TYPES.LYSINE]: 'Lysine',
  [PARTICLE_TYPES.METHIONINE]: 'Methionine',
  [PARTICLE_TYPES.THREONINE]: 'Threonine',
  [PARTICLE_TYPES.TRYPTOPHAN]: 'Tryptophan',
  [PARTICLE_TYPES.ARGININE]: 'Arginine',
  [PARTICLE_TYPES.ASPARAGINE]: 'Asparagine',
  [PARTICLE_TYPES.ASPARTIC_ACID]: 'Aspartic Acid',
  [PARTICLE_TYPES.GLUTAMIC_ACID]: 'Glutamic Acid',
  [PARTICLE_TYPES.GLUTAMINE]: 'Glutamine',
  [PARTICLE_TYPES.PROLINE]: 'Proline',
  [PARTICLE_TYPES.TYROSINE]: 'Tyrosine',
  [PARTICLE_TYPES.PHOSPHORIC_ACID]: 'Phosphoric Acid',
  [PARTICLE_TYPES.CITRIC_ACID]: 'Citric Acid',
  [PARTICLE_TYPES.UREA]: 'Urea',
  [PARTICLE_TYPES.PYRUVATE]: 'Pyruvate',
  [PARTICLE_TYPES.PHOSPHOLIPID]: 'Phospholipid',
  [PARTICLE_TYPES.CELLULOSE]: 'Cellulose',
  [PARTICLE_TYPES.NADH]: 'NADH',
  [PARTICLE_TYPES.CHOLESTEROL]: 'Cholesterol',
  [PARTICLE_TYPES.HEME]: 'Heme',
  [PARTICLE_TYPES.FRUCTOSE]: 'Fructose',
  [PARTICLE_TYPES.FORMALDEHYDE]: 'Formaldehyde',
  [PARTICLE_TYPES.ACETYLENE]: 'Acetylene',
  [PARTICLE_TYPES.HYDROGEN_CYANIDE]: 'Hydrogen Cyanide',
  [PARTICLE_TYPES.SULFUR_DIOXIDE]: 'Sulfur Dioxide',
  [PARTICLE_TYPES.NITROGEN_DIOXIDE]: 'Nitrogen Dioxide',
  [PARTICLE_TYPES.STEEL]: 'Steel',
  [PARTICLE_TYPES.VINEGAR]: 'Vinegar',
  [PARTICLE_TYPES.UNIVERSAL_INDICATOR]: 'Universal Indicator',
  [PARTICLE_TYPES.HELIUM_3]: 'Helium-3',
  [PARTICLE_TYPES.CARBON_14]: 'Carbon-14',
  [PARTICLE_TYPES.URANIUM_235]: 'Uranium-235',
  [PARTICLE_TYPES.URANIUM_238]: 'Uranium-238',
  [PARTICLE_TYPES.HIGGS_BOSON]: 'Higgs Boson',
  [PARTICLE_TYPES.MUON]: 'Muon',
  [PARTICLE_TYPES.POSITRON]: 'Positron',
  [PARTICLE_TYPES.TAU]: 'Tau Lepton',
  [PARTICLE_TYPES.ANTI_PROTON]: 'Anti-Proton',
  [PARTICLE_TYPES.ANTI_NEUTRON]: 'Anti-Neutron',
  [PARTICLE_TYPES.SILVER]: 'Silver',
  [PARTICLE_TYPES.GOLD]: 'Gold',
  [PARTICLE_TYPES.LEAD]: 'Lead',
  [PARTICLE_TYPES.TIN]: 'Tin',
  [PARTICLE_TYPES.BRONZE]: 'Bronze',
  [PARTICLE_TYPES.ALPHA_PARTICLE]: 'Alpha Particle',
  [PARTICLE_TYPES.BETA_PARTICLE]: 'Beta Particle',
  [PARTICLE_TYPES.GAMMA_RAY]: 'Gamma Ray',
  [PARTICLE_TYPES.THORIUM]: 'Thorium',
  [PARTICLE_TYPES.PROTACTINIUM]: 'Protactinium',
  [PARTICLE_TYPES.THORIUM_231]: 'Thorium-231',
  [PARTICLE_TYPES.THORIUM_234]: 'Thorium-234',
  [PARTICLE_TYPES.PROTACTINIUM_231]: 'Protactinium-231',
  [PARTICLE_TYPES.PROTACTINIUM_234]: 'Protactinium-234',
  [PARTICLE_TYPES.URANIUM_234]: 'Uranium-234',
  [PARTICLE_TYPES.THORIUM_230]: 'Thorium-230',
  [PARTICLE_TYPES.ACTINIUM_227]: 'Actinium-227',
  [PARTICLE_TYPES.RADIUM]: 'Radium',
  [PARTICLE_TYPES.RADIUM_226]: 'Radium-226',
  [PARTICLE_TYPES.RADON]: 'Radon',
  [PARTICLE_TYPES.RADON_222]: 'Radon-222',
  [PARTICLE_TYPES.POLONIUM]: 'Polonium',
  [PARTICLE_TYPES.POLONIUM_210]: 'Polonium-210',
  [PARTICLE_TYPES.LEAD_206]: 'Lead-206',
  [PARTICLE_TYPES.LEAD_207]: 'Lead-207',
  [PARTICLE_TYPES.ACTINIUM]: 'Actinium',
  [PARTICLE_TYPES.THORIUM]: 'Thorium',
  [PARTICLE_TYPES.PROTACTINIUM]: 'Protactinium',
  [PARTICLE_TYPES.URANIUM]: 'Uranium',
};

export const ELEMENTARY_IDS = [
  'water', 'sodium-chloride', 'vinegar', 'baking-soda', 
  'carbon', 'sulfur', 'iron', 'ethanol', 
  'oxygen', 'hydrogen', 'nitrogen',
  'magnesium', 'potassium-permanganate', 'universal-indicator',
  'muon', 'higgs-boson', 'positron', 'tau', 'anti-proton', 'anti-neutron',
  'tin'
];

export const PARTICLE_INFO = {
  [PARTICLE_TYPES.UP_QUARK]: { size: 35, name: 'Up Quark', category: 'Quark (Fermion)', mass: '2.2 MeV/c²', charge: '+2/3 e', spin: '1/2', description: 'One of the fundamental building blocks of matter.' },
  [PARTICLE_TYPES.DOWN_QUARK]: { size: 35, name: 'Down Quark', category: 'Quark (Fermion)', mass: '4.7 MeV/c²', charge: '-1/3 e', spin: '1/2', description: ' constituent of protons and neutrons.' },
  [PARTICLE_TYPES.CHARM_QUARK]: { size: 35, name: 'Charm Quark', category: 'Quark (Fermion)', mass: '1.27 GeV/c²', charge: '+2/3 e', spin: '1/2', description: 'A heavier type of quark.' },
  [PARTICLE_TYPES.STRANGE_QUARK]: { size: 35, name: 'Strange Quark', category: 'Quark (Fermion)', mass: '95 MeV/c²', charge: '-1/3 e', spin: '1/2', description: 'A third type of quark.' },
  [PARTICLE_TYPES.TOP_QUARK]: { size: 35, name: 'Top Quark', category: 'Quark (Fermion)', mass: '173.1 GeV/c²', charge: '+2/3 e', spin: '1/2', description: 'The most massive elementary particle.' },
  [PARTICLE_TYPES.BOTTOM_QUARK]: { size: 35, name: 'Bottom Quark', category: 'Quark (Fermion)', mass: '4.18 GeV/c²', charge: '-1/3 e', spin: '1/2', description: 'The second-heaviest quark.' },
  [PARTICLE_TYPES.ELECTRON]: { size: 60, name: 'Electron', category: 'Lepton (Fermion)', mass: '0.511 MeV/c²', charge: '-1 e', spin: '1/2', description: 'orbits the nucleus of an atom.' },
  [PARTICLE_TYPES.POSITRON]: { size: 60, name: 'Positron', category: 'Lepton (Antimatter)', mass: '0.511 MeV/c²', charge: '+1 e', spin: '1/2', description: 'Antimatter counterpart of the electron.' },
  [PARTICLE_TYPES.MUON]: { size: 60, name: 'Muon', category: 'Lepton (Fermion)', mass: '105.66 MeV/c²', charge: '-1 e', spin: '1/2', description: 'A heavier cousin of the electron.' },
  [PARTICLE_TYPES.TAU]: { size: 60, name: 'Tau', category: 'Lepton (Fermion)', mass: '1776.8 MeV/c²', charge: '-1 e', spin: '1/2', description: 'The heaviest known lepton.' },
  [PARTICLE_TYPES.ELECTRON_NEUTRINO]: { size: 60, name: 'Electron Neutrino', category: 'Lepton (Fermion)', mass: '< 1 eV/c²', charge: '0 e', spin: '1/2', description: 'very light, neutral particle.' },
  [PARTICLE_TYPES.ELECTRON_ANTINEUTRINO]: { size: 60, name: 'Electron Antineutrino', category: 'Lepton (Fermion)', mass: '< 1 eV/c²', charge: '0 e', spin: '1/2', description: 'antimatter counterpart of neutrino.' },
  [PARTICLE_TYPES.EXCITED_ELECTRON]: { size: 60, name: 'Excited Electron', category: 'Excited State', charge: '-1 e', spin: '1/2', composition: 'Electron + Photon', description: 'unstable state.' },
  [PARTICLE_TYPES.ANTI_UP_QUARK]: { size: 35, name: 'Anti-Up Quark', category: 'Antiquark (Fermion)', mass: '2.2 MeV/c²', charge: '-2/3 e', spin: '1/2', description: 'antimatter counterpart of up quark.' },
  [PARTICLE_TYPES.ANTI_DOWN_QUARK]: { size: 35, name: 'Anti-Down Quark', category: 'Antiquark (Fermion)', mass: '4.7 MeV/c²', charge: '+1/3 e', spin: '1/2', description: 'antimatter counterpart of down quark.' },
  [PARTICLE_TYPES.ANTI_CHARM_QUARK]: { size: 35, name: 'Anti-Charm Quark', category: 'Antiquark (Fermion)', mass: '1.27 GeV/c²', charge: '-2/3 e', spin: '1/2', description: 'antimatter counterpart of charm quark.' },
  [PARTICLE_TYPES.PHOTON]: { size: 60, name: 'Photon', category: 'Gauge Boson', mass: '0', charge: '0 e', spin: '1', description: 'Quantum of light.' },
  [PARTICLE_TYPES.HIGGS_BOSON]: { size: 65, name: 'Higgs Boson', category: 'Scalar Boson', mass: '125.1 GeV/c²', charge: '0 e', spin: '0', description: 'Grants mass to other particles.' },
  [PARTICLE_TYPES.PROTON]: { size: 50, name: 'Proton', category: 'Baryon (Hadron)', mass: '938.3 MeV/c²', charge: '+1 e', spin: '1/2', composition: '2 Up, 1 Down Quark', description: 'Found in atomic nucleus.', iconType: 'cloud' },
  [PARTICLE_TYPES.NEUTRON]: { size: 50, name: 'Neutron', category: 'Baryon (Hadron)', mass: '939.6 MeV/c²', charge: '0 e', spin: '1/2', composition: '1 Up, 2 Down Quarks', description: 'Neutral nucleus component.', iconType: 'cloud' },
  [PARTICLE_TYPES.ANTI_PROTON]: { size: 50, name: 'Anti-Proton', category: 'Baryon (Antimatter)', mass: '938.3 MeV/c²', charge: '-1 e', spin: '1/2', composition: '2 Anti-Up, 1 Anti-Down Quark', description: 'Antimatter counterpart of the proton.', iconType: 'cloud' },
  [PARTICLE_TYPES.ANTI_NEUTRON]: { size: 50, name: 'Anti-Neutron', category: 'Baryon (Antimatter)', mass: '939.6 MeV/c²', charge: '0 e', spin: '1/2', composition: '1 Anti-Up, 2 Anti-Down Quarks', description: 'Antimatter counterpart of the neutron.', iconType: 'cloud' },
  [PARTICLE_TYPES.DECAYING_NEUTRON]: { size: 50, name: 'Decaying Neutron', category: 'Unstable State', charge: '0 e', spin: '1/2', composition: 'Neutron + W Boson', description: 'Temporary high-energy state.', iconType: 'cloud' },
  [PARTICLE_TYPES.PION_PLUS]: { size: 50, name: 'Pion+', category: 'Meson', mass: '139.6 MeV/c²', charge: '+1 e', spin: '0', composition: '1 Up, 1 Anti-Down Quark', description: 'Lightest meson.', iconType: 'cloud' },
  [PARTICLE_TYPES.PION_MINUS]: { size: 50, name: 'Pion-', category: 'Meson', mass: '139.6 MeV/c²', charge: '-1 e', spin: '0', composition: '1 Down, 1 Anti-Up Quark', description: 'Antiparticle of Pion+.', iconType: 'cloud' },
  [PARTICLE_TYPES.LAMBDA_BARYON]: { size: 50, name: 'Lambda (Λ) Baryon', category: 'Baryon (Hadron)', mass: '1115.7 MeV/c²', charge: '0 e', spin: '1/2', composition: '1 Up, 1 Down, 1 Strange Quark', description: 'Strange baryon.', iconType: 'cloud' },
  [PARTICLE_TYPES.J_PSI_MESON]: { size: 50, name: 'J/ψ Meson', category: 'Meson (Quarkonium)', mass: '3096.9 MeV/c²', charge: '0 e', spin: '1', composition: '1 Charm, 1 Anti-Charm Quark', description: 'Proved existence of charm quark.', iconType: 'cloud' },
  [PARTICLE_TYPES.W_BOSON]: { size: 60, name: 'W Boson', category: 'Gauge Boson', mass: '80.4 GeV/c²', charge: '±1 e', spin: '1', description: 'Mediates weak force.' },
  [PARTICLE_TYPES.GLUON]: { size: 60, name: 'Gluon', category: 'Gauge Boson', mass: '0', charge: '0 e', spin: '1', description: 'Glues quarks together.' },
  [PARTICLE_TYPES.Z_BOSON]: { size: 60, name: 'Z Boson', category: 'Gauge Boson', mass: '91.2 GeV/c²', charge: '0 e', spin: '1', description: 'Neutral weak force mediator.' },
  [PARTICLE_TYPES.HYDROGEN]: { size: 80, name: 'Hydrogen', formula: 'H₂', state: 'gas', density: 0.00008, boilingPoint: -252, meltingPoint: -259, ph: 7.0, iconType: 'cylinder', category: 'Atom', atomicNumber: 1, mass: '1.008 u', charge: '0 e', composition: '1 Proton, 1 Electron', description: 'Lightest element.' },
  [PARTICLE_TYPES.DEUTERIUM]: { size: 80, name: 'Deuterium', category: 'Isotope', atomicNumber: 1, mass: '2.014 u', charge: '0 e', composition: '1 Proton, 1 Neutron, 1 Electron', description: 'Heavy hydrogen.', iconType: 'cylinder' },
  [PARTICLE_TYPES.TRITIUM]: { size: 80, name: 'Tritium', category: 'Isotope', atomicNumber: 1, mass: '3.016 u', charge: '0 e', composition: '1 Proton, 2 Neutrons, 1 Electron', description: 'Radioactive hydrogen.', iconType: 'cylinder' },
  [PARTICLE_TYPES.HELIUM]: { size: 80, name: 'Helium', formula: 'He', state: 'gas', density: 0.0001, boilingPoint: -268, meltingPoint: -272, ph: 7.0, iconType: 'cylinder', category: 'Atom', atomicNumber: 2, mass: '4.0026 u', charge: '0 e', composition: '2 Protons, 2 Neutrons, 2 Electrons', description: 'Noble gas.' },
  [PARTICLE_TYPES.HELIUM_3]: { size: 80, name: 'Helium-3', category: 'Isotope', atomicNumber: 2, mass: '3.016 u', charge: '0 e', composition: '2 Protons, 1 Neutron, 2 Electrons', description: 'Rare helium isotope, potential fusion fuel.', iconType: 'cylinder' },
  [PARTICLE_TYPES.LITHIUM]: { size: 80, name: 'Lithium', category: 'Atom', atomicNumber: 3, mass: '6.94 u', charge: '0 e', composition: '3 Protons, 4 Neutrons, 3 Electrons', description: 'Lightest metal.', iconType: 'bar' },
  [PARTICLE_TYPES.BERYLLIUM]: { size: 80, name: 'Beryllium', category: 'Atom', atomicNumber: 4, mass: '9.012 u', charge: '0 e', composition: '4 Protons, 5 Neutrons, 4 Electrons', description: 'Strong lightweight metal.', iconType: 'bar' },
  [PARTICLE_TYPES.BORON]: { size: 80, name: 'Boron', category: 'Atom', atomicNumber: 5, mass: '10.81 u', charge: '0 e', composition: '5 Protons, 6 Neutrons, 5 Electrons', description: 'High-strength metalloid.', iconType: 'rock' },
  [PARTICLE_TYPES.CARBON]: { size: 80, name: 'Carbon', formula: 'C', state: 'solid', density: 2.26, boilingPoint: 4827, meltingPoint: 3550, ph: 7.0, solubility: 0, iconType: 'rock', category: 'Atom', atomicNumber: 6, mass: '12.011 u', charge: '0 e', composition: '6 Protons, 6 Neutrons, 6 Electrons', description: 'Basis of life.' },
  [PARTICLE_TYPES.CARBON_14]: { size: 80, name: 'Carbon-14', category: 'Isotope', atomicNumber: 6, mass: '14.003 u', charge: '0 e', composition: '6 Protons, 8 Neutrons, 6 Electrons', description: 'Radioactive carbon used for dating.', iconType: 'rock' },
  [PARTICLE_TYPES.NITROGEN]: { size: 80, name: 'Nitrogen', formula: 'N₂', state: 'gas', density: 0.0012, boilingPoint: -195, meltingPoint: -210, ph: 7.0, iconType: 'cylinder', category: 'Atom', atomicNumber: 7, mass: '14.007 u', charge: '0 e', composition: '7 Protons, 7 Neutrons, 7 Electrons', description: 'Atmospheric gas.' },
  [PARTICLE_TYPES.OXYGEN]: { size: 80, name: 'Oxygen', formula: 'O₂', state: 'gas', density: 0.0014, boilingPoint: -183, meltingPoint: -218, ph: 7.0, iconType: 'cylinder', category: 'Atom', atomicNumber: 8, mass: '15.999 u', charge: '0 e', composition: '8 Protons, 8 Neutrons, 8 Electrons', description: 'Reactive gas for respiration.' },
  [PARTICLE_TYPES.FLUORINE]: { size: 80, name: 'Fluorine', formula: 'F₂', state: 'gas', density: 0.0017, boilingPoint: -188, meltingPoint: -219, ph: 7.0, iconType: 'cylinder', category: 'Atom', atomicNumber: 9, mass: '18.998 u', charge: '0 e', composition: '9 Protons, 10 Neutrons, 9 Electrons', description: 'Most reactive nonmetal.' },
  [PARTICLE_TYPES.NEON]: { size: 80, name: 'Neon', category: 'Atom', atomicNumber: 10, mass: '20.180 u', charge: '0 e', composition: '10 Protons, 10 Neutrons, 10 Electrons', description: 'Noble gas glow.', iconType: 'cylinder' },
  [PARTICLE_TYPES.SODIUM]: { size: 80, name: 'Sodium', formula: 'Na', state: 'solid', density: 0.97, boilingPoint: 883, meltingPoint: 98, ph: 7.0, solubility: 0, iconType: 'bar', category: 'Atom', atomicNumber: 11, mass: '22.990 u', charge: '0 e', composition: '11 Protons, 12 Neutrons, 11 Electrons', description: 'Reactive alkali metal.' },
  [PARTICLE_TYPES.MAGNESIUM]: { size: 80, name: 'Magnesium', formula: 'Mg', state: 'solid', density: 1.74, boilingPoint: 1090, meltingPoint: 650, ph: 7.0, solubility: 0, iconType: 'bar', category: 'Atom', atomicNumber: 12, mass: '24.305 u', charge: '0 e', composition: '12 Protons, 12 Neutrons, 12 Electrons', description: 'Flammable metal.' },
  [PARTICLE_TYPES.ALUMINIUM]: { size: 80, name: 'Aluminium', category: 'Atom', atomicNumber: 13, mass: '26.982 u', charge: '0 e', composition: '13 Protons, 14 Neutrons, 13 Electrons', description: 'Lightweight metal.', iconType: 'bar' },
  [PARTICLE_TYPES.SILICON]: { size: 80, name: 'Silicon', formula: 'Si', state: 'solid', density: 2.33, boilingPoint: 3265, meltingPoint: 1414, ph: 7.0, solubility: 0, iconType: 'rock', category: 'Atom', atomicNumber: 14, mass: '28.085 u', charge: '0 e', composition: '14 Protons, 14 Neutrons, 14 Electrons', description: 'Basis of electronics.' },
  [PARTICLE_TYPES.PHOSPHORUS]: { size: 80, name: 'Phosphorus', formula: 'P', state: 'solid', density: 1.82, boilingPoint: 280, meltingPoint: 44, ph: 7.0, solubility: 0, iconType: 'powder', category: 'Atom', atomicNumber: 15, mass: '30.974 u', charge: '0 e', composition: '15 Protons, 16 Neutrons, 15 Electrons', description: 'Essential for DNA.' },
  [PARTICLE_TYPES.SULFUR]: { size: 80, name: 'Sulfur', formula: 'S', state: 'solid', density: 2.07, boilingPoint: 444, meltingPoint: 115, ph: 7.0, solubility: 0, iconType: 'powder', category: 'Atom', atomicNumber: 16, mass: '32.06 u', charge: '0 e', composition: '16 Protons, 16 Neutrons, 16 Electrons', description: 'Yellow crystalline solid.' },
  [PARTICLE_TYPES.CHLORINE]: { size: 80, name: 'Chlorine', formula: 'Cl₂', state: 'gas', density: 0.0032, boilingPoint: -34, meltingPoint: -101, ph: 4.0, iconType: 'cloud', category: 'Atom', atomicNumber: 17, mass: '35.45 u', charge: '0 e', composition: '17 Protons, 18 Neutrons, 17 Electrons', description: 'Toxic halogen gas.' },
  [PARTICLE_TYPES.ARGON]: { size: 80, name: 'Argon', category: 'Atom', atomicNumber: 18, mass: '39.948 u', charge: '0 e', composition: '18 Protons, 22 Neutrons, 18 Electrons', description: 'Inert atmospheric gas.', iconType: 'cylinder' },
  [PARTICLE_TYPES.POTASSIUM]: { size: 80, name: 'Potassium', formula: 'K', state: 'solid', density: 0.86, boilingPoint: 759, meltingPoint: 63, ph: 7.0, solubility: 0, iconType: 'bar', category: 'Atom', atomicNumber: 19, mass: '39.098 u', charge: '0 e', composition: '19 Protons, 20 Neutrons, 19 Electrons', description: 'Soft alkali metal.' },
  [PARTICLE_TYPES.CALCIUM]: { size: 80, name: 'Calcium', category: 'Atom', atomicNumber: 20, mass: '40.078 u', charge: '0 e', composition: '20 Protons, 20 Neutrons, 20 Electrons', description: 'Essential for bone health.', iconType: 'rock' },
  [PARTICLE_TYPES.SCANDIUM]: { size: 80, name: 'Scandium', category: 'Atom', atomicNumber: 21, mass: '44.956 u', charge: '0 e', composition: '21 Protons, 24 Neutrons, 21 Electrons', description: 'Transition metal.', iconType: 'bar' },
  [PARTICLE_TYPES.TITANIUM]: { size: 80, name: 'Titanium', category: 'Atom', atomicNumber: 22, mass: '47.867 u', charge: '0 e', composition: '22 Protons, 26 Neutrons, 22 Electrons', description: 'High strength lustrous metal.', iconType: 'bar' },
  [PARTICLE_TYPES.VANADIUM]: { size: 80, name: 'Vanadium', category: 'Atom', atomicNumber: 23, mass: '50.942 u', charge: '0 e', composition: '23 Protons, 28 Neutrons, 23 Electrons', description: 'Hard transition metal.', iconType: 'bar' },
  [PARTICLE_TYPES.CHROMIUM]: { size: 80, name: 'Chromium', category: 'Atom', atomicNumber: 24, mass: '51.996 u', charge: '0 e', composition: '24 Protons, 28 Neutrons, 24 Electrons', description: 'Lustrous steely-grey metal.', iconType: 'bar' },
  [PARTICLE_TYPES.MANGANESE]: { size: 80, name: 'Manganese', formula: 'Mn', state: 'solid', density: 7.21, boilingPoint: 2061, meltingPoint: 1246, ph: 7.0, solubility: 0, iconType: 'bar', category: 'Atom', atomicNumber: 25, mass: '54.938 u', charge: '0 e', composition: '25 Protons, 30 Neutrons, 25 Electrons', description: 'Industrial alloy component.' },
  [PARTICLE_TYPES.IRON]: { size: 80, name: 'Iron', formula: 'Fe', state: 'solid', density: 7.87, boilingPoint: 2862, meltingPoint: 1538, ph: 7.0, solubility: 0, iconType: 'bar', category: 'Atom', atomicNumber: 26, mass: '55.845 u', charge: '0 e', composition: '26 Protons, 30 Neutrons, 26 Electrons', description: 'Most common element by mass.' },
  [PARTICLE_TYPES.COBALT]: { size: 80, name: 'Cobalt', category: 'Atom', atomicNumber: 27, mass: '58.933 u', charge: '0 e', composition: '27 Protons, 32 Neutrons, 27 Electrons', description: 'Hard lustrous metal.', iconType: 'bar' },
  [PARTICLE_TYPES.NICKEL]: { size: 80, name: 'Nickel', category: 'Atom', atomicNumber: 28, mass: '58.693 u', charge: '0 e', composition: '28 Protons, 31 Neutrons, 28 Electrons', description: 'Silvery-white metal.', iconType: 'bar' },
  [PARTICLE_TYPES.COPPER]: { size: 80, name: 'Copper', category: 'Atom', atomicNumber: 29, mass: '63.546 u', charge: '0 e', composition: '29 Protons, 34 Neutrons, 29 Electrons', description: 'High conductivity metal.', iconType: 'bar' },
  [PARTICLE_TYPES.ZINC]: { size: 80, name: 'Zinc', category: 'Atom', atomicNumber: 30, mass: '65.38 u', charge: '0 e', composition: '30 Protons, 35 Neutrons, 30 Electrons', description: 'Bluish-silvery metal.', iconType: 'bar' },
  [PARTICLE_TYPES.GALLIUM]: { size: 80, name: 'Gallium', category: 'Atom', atomicNumber: 31, mass: '69.723 u', charge: '0 e', composition: '31 Protons, 39 Neutrons, 31 Electrons', description: 'Low melting point metal.', iconType: 'bar' },
  [PARTICLE_TYPES.GERMANIUM]: { size: 80, name: 'Germanium', category: 'Atom', atomicNumber: 32, mass: '72.63 u', charge: '0 e', composition: '32 Protons, 41 Neutrons, 32 Electrons', description: 'Hard-brittle metalloid.', iconType: 'rock' },
  [PARTICLE_TYPES.ARSENIC]: { size: 80, name: 'Arsenic', formula: 'As', state: 'solid', density: 5.72, boilingPoint: 614, meltingPoint: 817, ph: 7.0, solubility: 0, iconType: 'rock', category: 'Atom', atomicNumber: 33, mass: '74.922 u', charge: '0 e', composition: '33 Protons, 42 Neutrons, 33 Electrons', description: 'Toxic metalloid.' },
  [PARTICLE_TYPES.SELENIUM]: { size: 80, name: 'Selenium', category: 'Atom', atomicNumber: 34, mass: '78.971 u', charge: '0 e', composition: '34 Protons, 45 Neutrons, 34 Electrons', description: 'Photovoltaic nonmetal.', iconType: 'rock' },
  [PARTICLE_TYPES.BROMINE]: { size: 80, name: 'Bromine', category: 'Atom', atomicNumber: 35, mass: '79.904 u', charge: '0 e', composition: '35 Protons, 45 Neutrons, 35 Electrons', description: 'Liquid halogen.', iconType: 'liquid' },
  [PARTICLE_TYPES.KRYPTON]: { size: 80, name: 'Krypton', category: 'Atom', atomicNumber: 36, mass: '83.798 u', charge: '0 e', composition: '36 Protons, 48 Neutrons, 36 Electrons', description: 'Noble atmospheric gas.', iconType: 'cylinder' },
  [PARTICLE_TYPES.SILVER]: { size: 80, name: 'Silver', category: 'Atom', atomicNumber: 47, mass: '107.87 u', charge: '0 e', composition: '47 Protons, 61 Neutrons, 47 Electrons', description: 'Lustrous transition metal.', iconType: 'bar' },
  [PARTICLE_TYPES.GOLD]: { size: 80, name: 'Gold', category: 'Atom', atomicNumber: 79, mass: '196.97 u', charge: '0 e', composition: '79 Protons, 118 Neutrons, 79 Electrons', description: 'Noble heavy metal.', iconType: 'bar' },
  [PARTICLE_TYPES.LEAD]: { size: 80, name: 'Lead', category: 'Atom', atomicNumber: 82, mass: '207.2 u', charge: '0 e', composition: '82 Protons, 125 Neutrons, 82 Electrons', description: 'Dense stable heavy metal.', iconType: 'bar' },
  [PARTICLE_TYPES.TIN]: { size: 80, name: 'Tin', category: 'Atom', atomicNumber: 50, mass: '118.71 u', charge: '0 e', composition: '50 Protons, 69 Neutrons, 50 Electrons', description: 'Silvery-white post-transition metal.', iconType: 'bar' },
  [PARTICLE_TYPES.BRONZE]: { size: 90, name: 'Bronze', category: 'Alloy', composition: 'Copper, Tin', description: 'Durable ancient alloy.', iconType: 'bar' },
  [PARTICLE_TYPES.URANIUM_235]: { size: 80, name: 'Uranium-235', category: 'Isotope', atomicNumber: 92, mass: '235.04 u', charge: '0 e', composition: '92 Protons, 143 Neutrons, 92 Electrons', description: 'Fissile isotope of uranium.', iconType: 'bar' },
  [PARTICLE_TYPES.URANIUM_238]: { size: 80, name: 'Uranium-238', category: 'Isotope', atomicNumber: 92, mass: '238.05 u', charge: '0 e', composition: '92 Protons, 146 Neutrons, 92 Electrons', description: 'Most common isotope of uranium.', iconType: 'bar' },
  [PARTICLE_TYPES.WATER]: { size: 96, name: 'Water', formula: 'H₂O', state: 'liquid', density: 1.0, boilingPoint: 100, meltingPoint: 0, ph: 7.0, iconType: 'liquid', category: 'Molecule', mass: '18.015 u', charge: '0 e', composition: '2 Hydrogen, 1 Oxygen', description: 'Universal solvent.', isChemical: true },
  [PARTICLE_TYPES.METHANE]: { size: 96, name: 'Methane', formula: 'CH₄', state: 'gas', density: 0.0006, boilingPoint: -161, meltingPoint: -182, ph: 7.0, iconType: 'cylinder', category: 'Molecule', mass: '16.04 u', charge: '0 e', composition: '1 Carbon, 4 Hydrogen', description: 'Simplest alkane.', isChemical: true },
  [PARTICLE_TYPES.AMMONIA]: { size: 96, name: 'Ammonia', formula: 'NH₃', state: 'gas', density: 0.0007, boilingPoint: -33, meltingPoint: -77, ph: 11.5, iconType: 'cloud', category: 'Molecule', mass: '17.031 u', charge: '0 e', composition: '1 Nitrogen, 3 Hydrogen', description: 'Pungent gas.', isChemical: true },
  [PARTICLE_TYPES.CARBON_DIOXIDE]: { size: 96, name: 'Carbon Dioxide', formula: 'CO₂', state: 'gas', density: 0.0019, boilingPoint: -78, ph: 5.5, iconType: 'cloud', category: 'Molecule', mass: '44.01 u', charge: '0 e', composition: '1 Carbon, 2 Oxygen', description: 'Greenhouse gas.', isChemical: true },
  [PARTICLE_TYPES.SODIUM_CHLORIDE]: { size: 96, name: 'Salt (NaCl)', formula: 'NaCl', state: 'solid', density: 2.16, boilingPoint: 1465, meltingPoint: 801, ph: 7.0, solubility: 36, iconType: 'crystal', category: 'Ionic Compound', mass: '58.44 u', charge: '0 e', composition: '1 Sodium, 1 Chlorine', description: 'Table salt.', isChemical: true },
  [PARTICLE_TYPES.SODIUM_HYDROXIDE]: { size: 96, name: 'Sodium Hydroxide', formula: 'NaOH', state: 'solid', density: 2.13, boilingPoint: 1388, meltingPoint: 318, ph: 14.0, solubility: 100, iconType: 'crystal', category: 'Ionic Compound', mass: '40.0 u', charge: '0 e', composition: '1 Sodium, 1 Oxygen, 1 Hydrogen', description: 'Caustic soda.', isChemical: true },
  [PARTICLE_TYPES.HYDROCHLORIC_ACID]: { size: 96, name: 'Hydrochloric Acid', formula: 'HCl', state: 'liquid', density: 1.18, boilingPoint: 48, meltingPoint: -27, ph: 1.0, iconType: 'vial', category: 'Molecule / Acid', mass: '36.46 u', charge: '0 e', composition: '1 Hydrogen, 1 Chlorine', description: 'Strong acid.', isChemical: true },
  [PARTICLE_TYPES.NITRIC_ACID]: { size: 96, name: 'Nitric Acid', formula: 'HNO₃', state: 'liquid', density: 1.51, boilingPoint: 83, meltingPoint: -42, ph: 1.0, iconType: 'vial', category: 'Molecule / Acid', mass: '63.01 g/mol', charge: '0 e', composition: '1 Hydrogen, 1 Nitrogen, 3 Oxygen', description: 'Highly corrosive mineral acid.', isChemical: true },
  [PARTICLE_TYPES.IRON_OXIDE]: { size: 96, name: 'Iron Oxide', formula: 'Fe₂O₃', state: 'solid', density: 5.24, boilingPoint: 1987, meltingPoint: 1566, ph: 7.0, solubility: 0, iconType: 'powder', category: 'Ionic Compound', mass: '159.69 g/mol', charge: '0 e', composition: '2 Iron, 3 Oxygen', description: 'Rust.', isChemical: true },
  [PARTICLE_TYPES.IRON_SULFIDE]: { size: 96, name: 'Iron Sulfide', formula: 'FeS', state: 'solid', density: 4.84, boilingPoint: 1194, meltingPoint: 1194, ph: 7.0, solubility: 0, iconType: 'rock', category: 'Ionic Compound', mass: '87.91 g/mol', charge: '0 e', composition: '1 Iron, 1 Sulfur', description: 'Pyrite-like.', isChemical: true },
  [PARTICLE_TYPES.CARBON_MONOXIDE]: { size: 96, name: 'Carbon Monoxide', formula: 'CO', state: 'gas', density: 0.0012, boilingPoint: -191, meltingPoint: -205, ph: 7.0, iconType: 'cylinder', category: 'Molecule', mass: '28.01 u', charge: '0 e', composition: '1 Carbon, 1 Oxygen', description: 'Toxic gas.', isChemical: true },
  [PARTICLE_TYPES.HYDROGEN_SULFIDE]: { size: 96, name: 'Hydrogen Sulfide', formula: 'H₂S', category: 'Molecule', mass: '34.08 u', charge: '0 e', composition: '2 Hydrogen, 1 Sulfur', description: 'Foul odor gas.', isChemical: true, iconType: 'cloud' },
  [PARTICLE_TYPES.HYDROGEN_PEROXIDE]: { size: 96, name: 'Hydrogen Peroxide', formula: 'H₂O₂', category: 'Molecule', mass: '34.01 u', charge: '0 e', composition: '2 Hydrogen, 2 Oxygen', description: 'Oxidizer.', isChemical: true, iconType: 'bottle' },
  [PARTICLE_TYPES.OZONE]: { size: 96, name: 'Ozone', formula: 'O₃', category: 'Molecule', mass: '48.00 u', charge: '0 e', composition: '3 Oxygen', description: 'UV protector.', isChemical: true, iconType: 'cloud' },
  [PARTICLE_TYPES.NITROUS_OXIDE]: { size: 96, name: 'Nitrous Oxide', formula: 'N₂O', category: 'Molecule', mass: '44.013 u', charge: '0 e', composition: '2 Nitrogen, 1 Oxygen', description: 'Laughing gas.', isChemical: true, iconType: 'cylinder' },
  [PARTICLE_TYPES.SILICON_DIOXIDE]: { size: 96, name: 'Silicon Dioxide (Silica)', formula: 'SiO₂', category: 'Molecule', mass: '60.08 u', charge: '0 e', composition: '1 Silicon, 2 Oxygen', description: 'Sand.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.HYDROGEN_FLUORIDE]: { size: 96, name: 'Hydrogen Fluoride', formula: 'HF', category: 'Molecule / Acid', mass: '20.01 u', charge: '0 e', composition: '1 Hydrogen, 1 Fluorine', description: 'Corrosive gas/liquid.', isChemical: true },
  [PARTICLE_TYPES.GLYCINE]: { size: 112, name: 'Glycine', formula: 'C₂H₅NO₂', state: 'solid', density: 1.16, boilingPoint: 233, meltingPoint: 233, ph: 6.0, solubility: 25, iconType: 'amino', category: 'Amino Acid', mass: '75.07 g/mol', charge: '0 e', composition: '2 Carbon, 5 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'Simplest amino acid.', isChemical: true },
  [PARTICLE_TYPES.ALANINE]: { size: 112, name: 'Alanine', formula: 'C₃H₇NO₂', state: 'solid', density: 1.42, boilingPoint: 258, meltingPoint: 258, ph: 6.0, solubility: 16, iconType: 'amino', category: 'Amino Acid', mass: '89.09 g/mol', charge: '0 e', composition: '3 Carbon, 7 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'Simple amino acid.', isChemical: true },
  [PARTICLE_TYPES.SERINE]: { size: 112, name: 'Serine', formula: 'C₃H₇NO₃', state: 'solid', density: 1.6, boilingPoint: 228, meltingPoint: 228, ph: 5.7, solubility: 25, iconType: 'amino', category: 'Amino Acid', mass: '105.09 g/mol', charge: '0 e', composition: '3 Carbon, 7 Hydrogen, 1 Nitrogen, 3 Oxygen', description: 'Polar amino acid.', isChemical: true },
  [PARTICLE_TYPES.VALINE]: { size: 112, name: 'Valine', formula: 'C₅H₁₁NO₂', state: 'solid', density: 1.23, boilingPoint: 298, meltingPoint: 298, ph: 6.0, solubility: 8, iconType: 'amino', category: 'Amino Acid', mass: '117.15 g/mol', charge: '0 e', composition: '5 Carbon, 11 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'Essential amino acid.', isChemical: true },
  [PARTICLE_TYPES.LEUCINE]: { size: 112, name: 'Leucine', formula: 'C₆H₁₃NO₂', state: 'solid', density: 1.29, boilingPoint: 293, meltingPoint: 293, ph: 6.0, solubility: 2, iconType: 'amino', category: 'Amino Acid', mass: '131.17 g/mol', charge: '0 e', composition: '6 Carbon, 13 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'BCAA amino acid.', isChemical: true },
  [PARTICLE_TYPES.GLYCYLGLYCINE]: { size: 112, name: 'Glycylglycine', formula: 'C₄H₈N₂O₃', category: 'Dipeptide', mass: '132.12 g/mol', charge: '0 e', composition: 'Two Glycine molecules', description: 'Simplest dipeptide.', isChemical: true, iconType: 'protein' },
  [PARTICLE_TYPES.GLYCYL_ALANINE]: { size: 112, name: 'Glycyl-Alanine', formula: 'C₅H₁₀N₂O₃', category: 'Dipeptide', mass: '146.14 g/mol', charge: '0 e', composition: 'Glycine + Alanine', description: 'Dipeptide block.', isChemical: true, iconType: 'protein' },
  [PARTICLE_TYPES.INSULIN_FRAGMENT]: { size: 130, name: 'Insulin (Chain A)', category: 'Polypeptide', mass: 'Variable', charge: '0 e', composition: 'Gly-Ile-Val-Glu-Gln', description: 'Fragment of hormone.', isChemical: true, iconType: 'protein' },
  [PARTICLE_TYPES.HEMOGLOBIN_POCKET]: { size: 130, name: 'Heme Pocket', category: 'Polypeptide', mass: 'Variable', charge: '0 e', composition: 'His-Val-Leu-His', description: 'Oxygen binding site.', isChemical: true, iconType: 'protein' },
  [PARTICLE_TYPES.ETHANOL]: { size: 96, name: 'Ethanol', formula: 'C₂H₅OH', state: 'liquid', density: 0.78, boilingPoint: 78, meltingPoint: -114, ph: 7.33, iconType: 'bottle', category: 'Molecule / Alcohol', mass: '46.07 g/mol', charge: '0 e', composition: '2 Carbon, 6 Hydrogen, 1 Oxygen', description: 'Drinking alcohol.', isChemical: true },
  [PARTICLE_TYPES.ETHYLENE]: { size: 96, name: 'Ethylene', formula: 'C₂H₄', state: 'gas', density: 0.0012, boilingPoint: -103, meltingPoint: -169, ph: 7.0, iconType: 'cloud', category: 'Molecule / Alkene', mass: '28.05 g/mol', charge: '0 e', composition: '2 Carbon, 4 Hydrogen', description: 'Plant hormone and plastic precursor.', isChemical: true },
  [PARTICLE_TYPES.METHANOL]: { size: 96, name: 'Methanol', formula: 'CH₃OH', state: 'liquid', density: 0.79, boilingPoint: 64, meltingPoint: -97, ph: 7.0, iconType: 'bottle', category: 'Molecule / Alcohol', mass: '32.04 g/mol', charge: '0 e', composition: '1 Carbon, 4 Hydrogen, 1 Oxygen', description: 'Wood alcohol.', isChemical: true },
  [PARTICLE_TYPES.ACETONE]: { size: 96, name: 'Acetone', formula: 'CH₃COCH₃', state: 'liquid', density: 0.79, boilingPoint: 56, meltingPoint: -95, ph: 7.0, iconType: 'bottle', category: 'Molecule / Ketone', mass: '58.08 g/mol', charge: '0 e', composition: '3 Carbon, 6 Hydrogen, 1 Oxygen', description: 'Organic solvent.', isChemical: true },
  [PARTICLE_TYPES.BAKING_SODA]: { size: 96, name: 'Baking Soda', formula: 'NaHCO₃', state: 'solid', density: 2.2, boilingPoint: 851, meltingPoint: 50, ph: 8.3, solubility: 9.6, iconType: 'powder', category: 'Ionic Compound', mass: '84.0 u', charge: '0 e', composition: '1 Na, 1 H, 1 C, 3 O', description: 'Sodium bicarbonate.', isChemical: true },
  [PARTICLE_TYPES.CARBONIC_ACID]: { size: 96, name: 'Carbonic Acid', formula: 'H₂CO₃', state: 'liquid', density: 1.0, boilingPoint: 100, meltingPoint: 0, ph: 4.18, iconType: 'vial', category: 'Molecule / Acid', mass: '62.03 g/mol', charge: '0 e', composition: '2 H, 1 C, 3 O', description: 'Weak acid.', isChemical: true },
  [PARTICLE_TYPES.AMMONIUM_HYDROXIDE]: { size: 96, name: 'Ammonium Hydroxide', formula: 'NH₄OH', state: 'liquid', density: 0.91, boilingPoint: 25, meltingPoint: -77, ph: 11.6, iconType: 'bottle', category: 'Solution', mass: '35.04 g/mol', charge: '0 e', composition: 'NH3 in H2O', description: 'Ammonia solution.', isChemical: true },
  [PARTICLE_TYPES.SULFURIC_ACID]: { size: 96, name: 'Sulfuric Acid', formula: 'H₂SO₄', state: 'liquid', density: 1.83, boilingPoint: 337, meltingPoint: 10, ph: 0.5, iconType: 'vial', category: 'Molecule / Acid', mass: '98.079 g/mol', charge: '0 e', composition: '2 Hydrogen, 1 Sulfur, 4 Oxygen', description: 'Corrosive mineral acid.', isChemical: true },
  [PARTICLE_TYPES.GLUCOSE]: { size: 96, name: 'Glucose', formula: 'C₆H₁₂O₆', state: 'solid', density: 1.54, boilingPoint: 527, meltingPoint: 146, ph: 7.0, solubility: 90, iconType: 'crystal', category: 'Molecule / Carbohydrate', mass: '180.156 g/mol', charge: '0 e', composition: '6 Carbon, 12 Hydrogen, 6 Oxygen', description: 'Energy sugar.', isChemical: true },
  [PARTICLE_TYPES.ADENINE]: { size: 96, name: 'Adenine', formula: 'C₅H₅N₅', category: 'Nucleobase (Purine)', mass: '135.13 g/mol', charge: '0 e', composition: '5 Carbon, 5 Hydrogen, 5 Nitrogen', description: 'Purine base.', isChemical: true, iconType: 'crystal' },
  [PARTICLE_TYPES.GUANINE]: { size: 96, name: 'Guanine', formula: 'C₅H₅N₅O', category: 'Nucleobase (Purine)', mass: '151.13 g/mol', charge: '0 e', composition: '5 Carbon, 5 Hydrogen, 5 Nitrogen, 1 Oxygen', description: 'Purine base.', isChemical: true, iconType: 'crystal' },
  [PARTICLE_TYPES.CYTOSINE]: { size: 96, name: 'Cytosine', formula: 'C₄H₅N₃O', category: 'Nucleobase (Pyrimidine)', mass: '111.10 g/mol', charge: '0 e', composition: '4 Carbon, 5 Hydrogen, 3 Nitrogen, 1 Oxygen', description: 'Pyrimidine base.', isChemical: true, iconType: 'crystal' },
  [PARTICLE_TYPES.THYMINE]: { size: 96, name: 'Thymine', formula: 'C₅H₆N₂O₂', category: 'Nucleobase (Pyrimidine)', mass: '126.11 g/mol', charge: '0 e', composition: '5 Carbon, 6 Hydrogen, 2 Nitrogen, 2 Oxygen', description: 'Pyrimidine base.', isChemical: true, iconType: 'crystal' },
  [PARTICLE_TYPES.NITROGEN_GAS]: { size: 96, name: 'Nitrogen Gas (N₂)', formula: 'N₂', category: 'Diatomic Molecule', mass: '28.014 u', charge: '0 e', composition: '2 Nitrogen', description: 'Atmospheric gas.', isChemical: true, iconType: 'cylinder' },
  [PARTICLE_TYPES.OXYGEN_GAS]: { size: 96, name: 'Oxygen Gas (O₂)', formula: 'O₂', category: 'Diatomic Molecule', mass: '31.998 u', charge: '0 e', composition: '2 Oxygen', description: 'Respiratory gas.', isChemical: true, iconType: 'cylinder' },
  [PARTICLE_TYPES.ACETIC_ACID]: { size: 96, name: 'Acetic Acid', formula: 'CH₃COOH', state: 'liquid', density: 1.01, boilingPoint: 118, meltingPoint: 16, ph: 2.5, iconType: 'bottle', category: 'Molecule / Carboxylic Acid', mass: '60.052 g/mol', charge: '0 e', composition: '2 Carbon, 4 Hydrogen, 2 Oxygen', description: 'Vinegar component.', isChemical: true },
  [PARTICLE_TYPES.URACIL]: { size: 96, name: 'Uracil', formula: 'C₄H₄N₂O₂', category: 'Nucleobase (Pyrimidine)', mass: '112.08 g/mol', charge: '0 e', composition: '4 Carbon, 4 Hydrogen, 2 Nitrogen, 2 Oxygen', description: 'RNA base.', isChemical: true, iconType: 'crystal' },
  [PARTICLE_TYPES.DNA]: { size: 180, name: 'DNA', formula: 'Polymer', category: 'Nucleic Acid', mass: 'Variable', charge: 'Negative', composition: 'A,T,G,C + Backbone', description: 'Genetic instructions.', isChemical: true, iconType: 'strand' },
  [PARTICLE_TYPES.RNA]: { size: 180, name: 'RNA', formula: 'Polymer', category: 'Nucleic Acid', mass: 'Variable', charge: 'Negative', composition: 'A,U,G,C + Backbone', description: 'Messenger instructions.', isChemical: true, iconType: 'strand' },
  [PARTICLE_TYPES.DEOXYRIBOSE]: { size: 96, name: 'Deoxyribose', formula: 'C₅H₁₀O₄', category: 'Sugar', description: 'DNA sugar.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.RIBOSE]: { size: 96, name: 'Ribose', formula: 'C₅H₁₀O₅', category: 'Sugar', description: 'RNA sugar.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.PHOSPHATE]: { size: 96, name: 'Phosphate Group', formula: 'PO₄³⁻', category: 'Functional Group', description: 'Backbone energy.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.NUCLEOTIDE_A]: { size: 112, name: 'dAMP', category: 'Nucleotide', description: 'DNA nucleotide.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.NUCLEOTIDE_T]: { size: 112, name: 'dTMP', category: 'Nucleotide', description: 'DNA nucleotide.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.NUCLEOTIDE_G]: { size: 112, name: 'dGMP', category: 'Nucleotide', description: 'DNA nucleotide.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.NUCLEOTIDE_C]: { size: 112, name: 'dCMP', category: 'Nucleotide', description: 'DNA nucleotide.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.NUCLEOTIDE_U]: { size: 112, name: 'UMP', category: 'Nucleotide', description: 'RNA nucleotide.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.ATP]: { size: 128, name: 'Adenosine Triphosphate', formula: 'C₁₀H₁₆N₅O₁₃P₃', category: 'Energy Carrier', description: 'Energy currency.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.GLYCEROL]: { size: 96, name: 'Glycerol', formula: 'C₃H₈O₃', category: 'Polyol', description: 'Lipid backbone.', isChemical: true, iconType: 'liquid' },
  [PARTICLE_TYPES.FATTY_ACID]: { size: 96, name: 'Fatty Acid', formula: 'R-COOH', category: 'Lipid Component', description: 'Chain component.', isChemical: true, iconType: 'liquid' },
  [PARTICLE_TYPES.LIPID]: { size: 128, name: 'Triglyceride', category: 'Lipid', description: 'Body fat.', isChemical: true, iconType: 'solid' },
  [PARTICLE_TYPES.MEMBRANE]: { size: 160, name: 'Cell Membrane', category: 'Organelle', description: 'Phospholipid bilayer.', iconType: 'solid' },
  [PARTICLE_TYPES.RIBOSOME]: { size: 160, name: 'Ribosome', category: 'Organelle', description: 'Protein synthesis site.', iconType: 'solid' },
  [PARTICLE_TYPES.MITOCHONDRION]: { size: 200, name: 'Mitochondrion', category: 'Organelle', description: 'Powerhouse.', iconType: 'solid' },
  [PARTICLE_TYPES.NUCLEUS]: { size: 240, name: 'Cell Nucleus', category: 'Organelle', description: 'Activity controller.', iconType: 'solid' },
  [PARTICLE_TYPES.BENZENE]: { size: 96, name: 'Benzene', formula: 'C₆H₆', category: 'Molecule', mass: '78.11 g/mol', charge: '0 e', composition: '6 Carbon, 6 Hydrogen', description: 'Organic constituent.', isChemical: true, iconType: 'liquid' },
  [PARTICLE_TYPES.CYSTEINE]: { size: 112, name: 'Cysteine', formula: 'C₃H₇NO₂S', state: 'solid', density: 1.5, boilingPoint: 240, meltingPoint: 240, ph: 5.0, solubility: 100, iconType: 'amino', category: 'Amino Acid', mass: '121.16 g/mol', charge: '0 e', composition: '3 Carbon, 7 Hydrogen, 1 Nitrogen, 2 Oxygen, 1 Sulfur', description: 'Sulfur amino acid.', isChemical: true },
  [PARTICLE_TYPES.PHENYLALANINE]: { size: 112, name: 'Phenylalanine', formula: 'C₉H₁₁NO₂', state: 'solid', density: 1.29, boilingPoint: 283, meltingPoint: 283, ph: 5.5, solubility: 3, iconType: 'amino', category: 'Amino Acid', mass: '165.19 g/mol', charge: '0 e', composition: '9 Carbon, 11 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'Essential amino acid.', isChemical: true },
  [PARTICLE_TYPES.HISTIDINE]: { size: 112, name: 'Histidine', formula: 'C₆H₉N₃O₂', state: 'solid', density: 1.44, boilingPoint: 287, meltingPoint: 287, ph: 7.6, solubility: 4, iconType: 'amino', category: 'Amino Acid', mass: '155.15 g/mol', charge: '0 e', composition: '6 Carbon, 9 Hydrogen, 3 Nitrogen, 2 Oxygen', description: 'Imidazole amino acid.', isChemical: true },
  [PARTICLE_TYPES.ISOLEUCINE]: { size: 112, name: 'Isoleucine', formula: 'C₆H₁₃NO₂', state: 'solid', density: 1.04, boilingPoint: 284, meltingPoint: 284, ph: 6.0, solubility: 4, iconType: 'amino', category: 'Amino Acid', mass: '131.17 g/mol', charge: '0 e', composition: '6 Carbon, 13 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'BCAA isomer.', isChemical: true },
  [PARTICLE_TYPES.LYSINE]: { size: 112, name: 'Lysine', formula: 'C₆H₁₄N₂O₂', state: 'solid', density: 1.1, boilingPoint: 224, meltingPoint: 224, ph: 9.7, solubility: 100, iconType: 'amino', category: 'Amino Acid', mass: '146.19 g/mol', charge: '0 e', composition: '6 Carbon, 14 Hydrogen, 2 Nitrogen, 2 Oxygen', description: 'Essential basic amino acid.', isChemical: true },
  [PARTICLE_TYPES.METHIONINE]: { size: 112, name: 'Methionine', formula: 'C₅H₁₁NO₂S', state: 'solid', density: 1.34, boilingPoint: 281, meltingPoint: 281, ph: 5.7, solubility: 3, iconType: 'amino', category: 'Amino Acid', mass: '149.21 g/mol', charge: '0 e', composition: '5 Carbon, 11 Hydrogen, 1 Nitrogen, 2 Oxygen, 1 Sulfur', description: 'Start amino acid.', isChemical: true },
  [PARTICLE_TYPES.THREONINE]: { size: 112, name: 'Threonine', formula: 'C₄H₉NO₃', state: 'solid', density: 1.07, boilingPoint: 255, meltingPoint: 255, ph: 5.6, solubility: 9, iconType: 'amino', category: 'Amino Acid', mass: '119.12 g/mol', charge: '0 e', composition: '4 Carbon, 9 Hydrogen, 1 Nitrogen, 3 Oxygen', description: 'Polar principal component.', isChemical: true },
  [PARTICLE_TYPES.TRYPTOPHAN]: { size: 112, name: 'Tryptophan', formula: 'C₁₁H₁₂N₂O₂', state: 'solid', density: 1.3, boilingPoint: 289, meltingPoint: 289, ph: 5.9, solubility: 1, iconType: 'amino', category: 'Amino Acid', mass: '204.23 g/mol', charge: '0 e', composition: '11 Carbon, 12 Hydrogen, 2 Nitrogen, 2 Oxygen', description: 'Largest amino acid.', isChemical: true },
  [PARTICLE_TYPES.ARGININE]: { size: 112, name: 'Arginine', formula: 'C₆H₁₄N₄O₂', state: 'solid', density: 1.1, boilingPoint: 244, meltingPoint: 244, ph: 10.8, solubility: 15, iconType: 'amino', category: 'Amino Acid', mass: '174.20 g/mol', charge: '+1 e', composition: '6 Carbon, 14 Hydrogen, 4 Nitrogen, 2 Oxygen', description: 'Complex basic amino acid.', isChemical: true },
  [PARTICLE_TYPES.ASPARAGINE]: { size: 112, name: 'Asparagine', formula: 'C₄H₈N₂O₃', state: 'solid', density: 1.54, boilingPoint: 234, meltingPoint: 234, ph: 5.4, solubility: 3, iconType: 'amino', category: 'Amino Acid', mass: '132.12 g/mol', charge: '0 e', composition: '4 Carbon, 8 Hydrogen, 2 Nitrogen, 3 Oxygen', description: 'Nitrogen transport amino acid.', isChemical: true },
  [PARTICLE_TYPES.ASPARTIC_ACID]: { size: 112, name: 'Aspartic Acid', formula: 'C₄H₇NO₄', state: 'solid', density: 1.66, boilingPoint: 270, meltingPoint: 270, ph: 2.8, solubility: 0.5, iconType: 'amino', category: 'Amino Acid', mass: '133.10 g/mol', charge: '-1 e', composition: '4 Carbon, 7 Hydrogen, 1 Nitrogen, 4 Oxygen', description: 'Acidic amino acid.', isChemical: true },
  [PARTICLE_TYPES.GLUTAMIC_ACID]: { size: 112, name: 'Glutamic Acid', formula: 'C₅H₉NO₄', state: 'solid', density: 1.46, boilingPoint: 199, meltingPoint: 199, ph: 3.2, solubility: 0.8, iconType: 'amino', category: 'Amino Acid', mass: '147.13 g/mol', charge: '-1 e', composition: '5 Carbon, 9 Hydrogen, 1 Nitrogen, 4 Oxygen', description: 'Key acidic amino acid.', isChemical: true },
  [PARTICLE_TYPES.GLUTAMINE]: { size: 112, name: 'Glutamine', formula: 'C₅H₁₀N₂O₃', state: 'solid', density: 1.47, boilingPoint: 185, meltingPoint: 185, ph: 5.7, solubility: 4, iconType: 'amino', category: 'Amino Acid', mass: '146.14 g/mol', charge: '0 e', composition: '5 Carbon, 10 Hydrogen, 2 Nitrogen, 3 Oxygen', description: 'Most abundant amino acid.', isChemical: true },
  [PARTICLE_TYPES.PROLINE]: { size: 112, name: 'Proline', formula: 'C₅H₉NO₂', state: 'solid', density: 1.35, boilingPoint: 228, meltingPoint: 228, ph: 6.3, solubility: 162, iconType: 'amino', category: 'Amino Acid', mass: '115.13 g/mol', charge: '0 e', composition: '5 Carbon, 9 Hydrogen, 1 Nitrogen, 2 Oxygen', description: 'Unique cyclic amino acid.', isChemical: true },
  [PARTICLE_TYPES.TYROSINE]: { size: 112, name: 'Tyrosine', formula: 'C₉H₁₁NO₃', state: 'solid', density: 1.46, boilingPoint: 295, meltingPoint: 295, ph: 5.7, solubility: 0.04, iconType: 'amino', category: 'Amino Acid', mass: '181.19 g/mol', charge: '0 e', composition: '9 Carbon, 11 Hydrogen, 1 Nitrogen, 3 Oxygen', description: 'Aromatic precursor.', isChemical: true },
  [PARTICLE_TYPES.PHOSPHORIC_ACID]: { size: 96, name: 'Phosphoric Acid', formula: 'H₃PO₄', state: 'liquid', density: 1.88, boilingPoint: 158, meltingPoint: 42, ph: 1.5, iconType: 'vial', category: 'Molecule / Acid', mass: '98.00 g/mol', charge: '0 e', composition: '1 Phosphorus, 4 Oxygen, 3 Hydrogen', description: 'Mineral acid source.', isChemical: true },
  [PARTICLE_TYPES.CITRIC_ACID]: { size: 112, name: 'Citric Acid', formula: 'C₆H₈O₇', state: 'solid', density: 1.66, boilingPoint: 310, meltingPoint: 153, ph: 2.2, iconType: 'crystal', category: 'Molecule / Acid', mass: '192.12 g/mol', charge: '0 e', composition: '6 Carbon, 8 Hydrogen, 7 Oxygen', description: 'Krebs intermediate.', isChemical: true },
  [PARTICLE_TYPES.UREA]: { size: 96, name: 'Urea', formula: 'CH₄N₂O', state: 'solid', density: 1.32, boilingPoint: 132, meltingPoint: 132, ph: 7.0, iconType: 'powder', category: 'Molecule', mass: '60.06 g/mol', charge: '0 e', composition: '1 Carbon, 4 Hydrogen, 2 Nitrogen, 1 Oxygen', description: 'Organic compound.', isChemical: true },
  [PARTICLE_TYPES.PYRUVATE]: { size: 96, name: 'Pyruvate', formula: 'C₃H₃O₃', state: 'liquid', density: 1.25, boilingPoint: 165, meltingPoint: 13, ph: 2.5, iconType: 'bottle', category: 'Molecule', mass: '88.06 g/mol', charge: '0 e', composition: '3 Carbon, 3 Hydrogen, 3 Oxygen', description: 'Metabolic intersection.', isChemical: true },
  [PARTICLE_TYPES.PHOSPHOLIPID]: { size: 140, name: 'Phospholipid', category: 'Complex Bio', mass: 'Variable', charge: 'Amphiphilic', composition: 'Glycerol + 2 Fatty Acids + 1 Phosphate', description: 'Membrane component.', isChemical: true, iconType: 'powder' },
  [PARTICLE_TYPES.CELLULOSE]: { size: 160, name: 'Cellulose', formula: '(C₆H₁₀O₅)n', state: 'solid', density: 1.5, boilingPoint: 500, meltingPoint: 500, ph: 7.0, solubility: 0, iconType: 'rock', category: 'Polymer', mass: 'Variable', charge: '0 e', composition: 'Glucose chain', description: 'Structural polysaccharide.', isChemical: true },
  [PARTICLE_TYPES.NADH]: { size: 140, name: 'NADH', formula: 'Carrier', state: 'solid', density: 1.6, boilingPoint: 600, meltingPoint: 600, ph: 7.0, iconType: 'powder', category: 'Complex Bio', mass: '663.4 g/mol', charge: '-1 e', composition: 'Carrier coenzyme', description: 'ATP coenzyme.', isChemical: true },
  [PARTICLE_TYPES.CHOLESTEROL]: { size: 120, name: 'Cholesterol', formula: 'C₂₇H₄₆O', state: 'solid', density: 1.05, boilingPoint: 360, meltingPoint: 148, ph: 7.0, solubility: 0, iconType: 'crystal', category: 'Complex Bio', mass: '386.6 g/mol', charge: '0 e', composition: '27 Carbon, 46 Hydrogen, 1 Oxygen', description: 'Membrane integrity.', isChemical: true },
  [PARTICLE_TYPES.HEME]: { size: 130, name: 'Heme', formula: 'C₃₄H₃₂FeN₄O₄', state: 'solid', density: 1.4, boilingPoint: 700, meltingPoint: 700, ph: 7.0, iconType: 'crystal', category: 'Complex Bio', mass: '616.5 g/mol', charge: 'Variable', composition: 'Porphyrin + Iron', description: 'Oxygen carrier.', isChemical: true },
  [PARTICLE_TYPES.FRUCTOSE]: { size: 96, name: 'Fructose', formula: 'C₆H₁₂O₆', category: 'Molecule / Carbohydrate', mass: '180.16 g/mol', charge: '0 e', composition: '6 Carbon, 12 Hydrogen, 6 Oxygen', description: 'Simple sugar.', isChemical: true, iconType: 'crystal' },
  [PARTICLE_TYPES.FORMALDEHYDE]: { size: 96, name: 'Formaldehyde', formula: 'CH₂O', category: 'Molecule', mass: '30.03 g/mol', charge: '0 e', composition: '1 Carbon, 2 Hydrogen, 1 Oxygen', description: 'Simple aldehyde.', isChemical: true, iconType: 'bottle' },
  [PARTICLE_TYPES.ACETYLENE]: { size: 96, name: 'Acetylene', formula: 'C₂H₂', category: 'Molecule', mass: '26.04 g/mol', charge: '0 e', composition: '2 Carbon, 2 Hydrogen', description: 'Simplest alkyne.', isChemical: true, iconType: 'cylinder' },
  [PARTICLE_TYPES.HYDROGEN_CYANIDE]: { size: 96, name: 'Hydrogen Cyanide', formula: 'HCN', category: 'Molecule', mass: '27.03 g/mol', charge: '0 e', composition: '1 Hydrogen, 1 Carbon, 1 Nitrogen', description: 'Toxic alkyne.', isChemical: true, iconType: 'cylinder' },
  [PARTICLE_TYPES.METHANOL]: { size: 96, name: 'Methanol', formula: 'CH₃OH', state: 'liquid', density: 0.79, boilingPoint: 64, meltingPoint: -97, ph: 7.0, iconType: 'bottle', category: 'Molecule / Alcohol', mass: '32.04 g/mol', charge: '0 e', composition: '1 Carbon, 4 Hydrogen, 1 Oxygen', description: 'Wood alcohol.', isChemical: true },
  [PARTICLE_TYPES.PROPANE]: { size: 96, name: 'Propane', formula: 'C₃H₈', category: 'Molecule / Alkane', mass: '44.1 g/mol', charge: '0 e', composition: '3 Carbon, 8 Hydrogen', description: 'Three-carbon alkane.', isChemical: true, iconType: 'cylinder' },
  [PARTICLE_TYPES.BUTANE]: { size: 96, name: 'Butane', formula: 'C₄H₁₀', category: 'Molecule / Alkane', mass: '58.12 g/mol', charge: '0 e', composition: '4 Carbon, 10 Hydrogen', description: 'Four-carbon alkane.', isChemical: true, iconType: 'cylinder' },
  [PARTICLE_TYPES.SULFUR_DIOXIDE]: { size: 96, name: 'Sulfur Dioxide', formula: 'SO₂', state: 'gas', density: 0.0029, boilingPoint: -10, meltingPoint: -72, ph: 4.5, iconType: 'cloud', category: 'Molecule', mass: '64.066 g/mol', charge: '0 e', composition: '1 Sulfur, 2 Oxygen', description: 'Toxic SO2.', isChemical: true },
  [PARTICLE_TYPES.NITROGEN_DIOXIDE]: { size: 96, name: 'Nitrogen Dioxide', formula: 'NO₂', category: 'Molecule', mass: '46.0055 g/mol', charge: '0 e', composition: '1 Nitrogen, 2 Oxygen', description: 'Acrid odor gas.', isChemical: true, iconType: 'cloud' },
  [PARTICLE_TYPES.ETHYL_ACETATE]: { size: 96, name: 'Ethyl Acetate', formula: 'Ester', state: 'liquid', density: 0.9, boilingPoint: 77, meltingPoint: -84, ph: 7.0, iconType: 'bottle', category: 'Molecule', mass: '88.11 g/mol', charge: '0 e', composition: '4 Carbon, 8 Hydrogen, 2 Oxygen', description: 'Sweet ester.', isChemical: true },
  [PARTICLE_TYPES.POLYETHYLENE]: { size: 112, name: 'Polyethylene', formula: 'Polymer', state: 'solid', density: 0.92, boilingPoint: 360, meltingPoint: 115, ph: 7.0, solubility: 0, iconType: 'rock', category: 'Polymer', mass: 'Variable', charge: '0 e', composition: 'Ethylene chain.', isChemical: true },
  [PARTICLE_TYPES.POTASSIUM_PERMANGANATE]: { size: 96, name: 'Potassium Permanganate', formula: 'KMnO₄', state: 'solid', density: 2.7, boilingPoint: 240, meltingPoint: 240, ph: 7.0, solubility: 6.4, iconType: 'crystal', category: 'Ionic Compound', mass: '158.034 g/mol', charge: '0 e', composition: 'K, Mn, 4O.', isChemical: true },
  [PARTICLE_TYPES.HYDROGEN_FLUORIDE]: { size: 96, name: 'Hydrogen Fluoride', formula: 'HF', category: 'Molecule / Acid', mass: '20.01 g/mol', charge: '0 e', composition: '1 Hydrogen, 1 Fluorine', description: 'Corrosive HF.', isChemical: true, iconType: 'vial' },
  [PARTICLE_TYPES.STEEL]: { size: 96, name: 'Steel', formula: 'Alloy', state: 'solid', density: 7.85, boilingPoint: 2800, meltingPoint: 1370, ph: 7.0, solubility: 0, iconType: 'bar', category: 'Alloy', mass: 'Variable', charge: '0 e', composition: 'Iron, Carbon.', isChemical: true },
  [PARTICLE_TYPES.VINEGAR]: { size: 96, name: 'Vinegar', formula: 'Mix', state: 'liquid', density: 1.01, boilingPoint: 118, meltingPoint: 16, ph: 2.5, iconType: 'bottle', category: 'Solution', mass: 'Variable', charge: '0 e', composition: 'Acetic Acid solution.', isChemical: true },
  [PARTICLE_TYPES.UNIVERSAL_INDICATOR]: { size: 96, name: 'Universal Indicator', formula: 'Solution', state: 'liquid', density: 1.0, boilingPoint: 100, meltingPoint: 0, ph: 7.0, iconType: 'bottle', category: 'Solution', mass: 'Variable', charge: '0 e', composition: 'Indicator.', isChemical: true },
  [PARTICLE_TYPES.ALPHA_PARTICLE]: { size: 50, name: 'Alpha Particle', category: 'Radiation', mass: '4.001 u', charge: '+2 e', composition: '2 Protons, 2 Neutrons', description: 'Highly ionizing helium nucleus emitted during decay.' },
  [PARTICLE_TYPES.BETA_PARTICLE]: { size: 40, name: 'Beta Particle', category: 'Radiation', mass: '0.0005 u', charge: '-1 e', composition: 'High-energy Electron', description: 'High-speed electron emitted from a nucleus.' },
  [PARTICLE_TYPES.GAMMA_RAY]: { size: 40, name: 'Gamma Ray', category: 'Radiation', mass: '0', charge: '0 e', composition: 'High-energy Photon', description: 'Extremely high-frequency electromagnetic radiation.' },
  [PARTICLE_TYPES.THORIUM]: { size: 80, name: 'Thorium', category: 'Atom', atomicNumber: 90, mass: '232.04 u', charge: '0 e', description: 'Silvery radioactive actinide metal.' },
  [PARTICLE_TYPES.PROTACTINIUM]: { size: 80, name: 'Protactinium', category: 'Atom', atomicNumber: 91, mass: '231.04 u', charge: '0 e', description: 'Dense, silvery-grey actinide metal.' },
  [PARTICLE_TYPES.THORIUM]: { size: 80, name: 'Thorium', category: 'Atom', atomicNumber: 90, mass: '232.03 u', charge: '0 e', description: 'Weakly radioactive actinide metal.' },
  [PARTICLE_TYPES.PROTACTINIUM]: { size: 80, name: 'Protactinium', category: 'Atom', atomicNumber: 91, mass: '231.03 u', charge: '0 e', description: 'Dense, silvery-grey actinide metal.' },
  [PARTICLE_TYPES.THORIUM_231]: { size: 80, name: 'Thorium-231', category: 'Isotope', atomicNumber: 90, mass: '231.03 u', charge: '0 e', composition: '90 Protons, 141 Neutrons', description: 'Decay product of Uranium-235.' },
  [PARTICLE_TYPES.THORIUM_234]: { size: 80, name: 'Thorium-234', category: 'Isotope', atomicNumber: 90, mass: '234.04 u', charge: '0 e', composition: '90 Protons, 144 Neutrons', description: 'Decay product of Uranium-238.' },
  [PARTICLE_TYPES.PROTACTINIUM_231]: { size: 80, name: 'Protactinium-231', category: 'Isotope', atomicNumber: 91, mass: '231.03 u', charge: '0 e', composition: '91 Protons, 140 Neutrons', description: 'Long-lived decay product in the U-235 chain.' },
  [PARTICLE_TYPES.PROTACTINIUM_234]: { size: 80, name: 'Protactinium-234', category: 'Isotope', atomicNumber: 91, mass: '234.04 u', charge: '0 e', composition: '91 Protons, 143 Neutrons', description: 'Short-lived decay product in the U-238 chain.' },
  [PARTICLE_TYPES.URANIUM_234]: { size: 80, name: 'Uranium-234', category: 'Isotope', atomicNumber: 92, mass: '234.04 u', charge: '0 e', composition: '92 Protons, 142 Neutrons', description: 'Indirect decay product of Uranium-238.' },
  [PARTICLE_TYPES.THORIUM_230]: { size: 80, name: 'Thorium-230', category: 'Isotope', atomicNumber: 90, mass: '230.03 u', charge: '0 e', composition: '90 Protons, 140 Neutrons', description: 'Decay product of Uranium-234.' },
  [PARTICLE_TYPES.ACTINIUM]: { size: 80, name: 'Actinium', category: 'Atom', atomicNumber: 89, mass: '227.03 u', charge: '0 e', description: 'Silvery-white radioactive metal.' },
  [PARTICLE_TYPES.ACTINIUM_227]: { size: 80, name: 'Actinium-227', category: 'Isotope', atomicNumber: 89, mass: '227.02 u', charge: '0 e', composition: '89 Protons, 138 Neutrons', description: 'Highly radioactive decay product.' },
  [PARTICLE_TYPES.URANIUM]: { size: 80, name: 'Uranium', category: 'Atom', atomicNumber: 92, mass: '238.03 u', charge: '0 e', description: 'Dense, silvery-white actinide metal.' },
  [PARTICLE_TYPES.RADIUM]: { size: 80, name: 'Radium', category: 'Atom', atomicNumber: 88, mass: '226.02 u', charge: '0 e', description: 'Luminescent alkaline earth metal.' },
  [PARTICLE_TYPES.RADIUM_226]: { size: 80, name: 'Radium-226', category: 'Isotope', atomicNumber: 88, mass: '226.02 u', charge: '0 e', composition: '88 Protons, 138 Neutrons', description: 'Decay product of Thorium-230.' },
  [PARTICLE_TYPES.RADON]: { size: 80, name: 'Radon', category: 'Atom', atomicNumber: 86, mass: '222.01 u', charge: '0 e', description: 'Radioactive noble gas.', state: 'gas' },
  [PARTICLE_TYPES.RADON_222]: { size: 80, name: 'Radon-222', category: 'Isotope', atomicNumber: 86, mass: '222.01 u', charge: '0 e', composition: '86 Protons, 136 Neutrons', description: 'Decay product of Radium-226.', state: 'gas' },
  [PARTICLE_TYPES.POLONIUM]: { size: 80, name: 'Polonium', category: 'Atom', atomicNumber: 84, mass: '209.98 u', charge: '0 e', description: 'Rare and highly radioactive semi-metal.' },
  [PARTICLE_TYPES.POLONIUM_210]: { size: 80, name: 'Polonium-210', category: 'Isotope', atomicNumber: 84, mass: '209.98 u', charge: '0 e', composition: '84 Protons, 126 Neutrons', description: 'Decay product of Radon-222 (via intermediates).' },
  [PARTICLE_TYPES.LEAD_206]: { size: 80, name: 'Lead-206', category: 'Isotope', atomicNumber: 82, mass: '205.97 u', charge: '0 e', composition: '82 Protons, 124 Neutrons', description: 'Stable endpoint of Uranium-238 chain.' },
  [PARTICLE_TYPES.LEAD_207]: { size: 80, name: 'Lead-207', category: 'Isotope', atomicNumber: 82, mass: '206.97 u', charge: '0 e', composition: '82 Protons, 125 Neutrons', description: 'Stable endpoint of Uranium-235 chain.' },
};

export const CODEX_PARTICLES_BY_CATEGORY = [
  {
    name: 'Fundamental',
    subcategories: [
      { name: 'Quarks', particles: [PARTICLE_TYPES.UP_QUARK, PARTICLE_TYPES.DOWN_QUARK, PARTICLE_TYPES.CHARM_QUARK, PARTICLE_TYPES.STRANGE_QUARK, PARTICLE_TYPES.TOP_QUARK, PARTICLE_TYPES.BOTTOM_QUARK] },
      { name: 'Anti-Quarks', particles: [PARTICLE_TYPES.ANTI_UP_QUARK, PARTICLE_TYPES.ANTI_DOWN_QUARK, PARTICLE_TYPES.ANTI_CHARM_QUARK] },
      { name: 'Leptons', particles: [PARTICLE_TYPES.ELECTRON, PARTICLE_TYPES.MUON, PARTICLE_TYPES.TAU, PARTICLE_TYPES.ELECTRON_NEUTRINO] },
      { name: 'Anti-Leptons', particles: [PARTICLE_TYPES.POSITRON, PARTICLE_TYPES.ELECTRON_ANTINEUTRINO] },
      { name: 'Bosons', particles: [PARTICLE_TYPES.PHOTON, PARTICLE_TYPES.GLUON, PARTICLE_TYPES.W_BOSON, PARTICLE_TYPES.Z_BOSON, PARTICLE_TYPES.HIGGS_BOSON] },
    ]
  },
  {
    name: 'Atomic',
    subcategories: [
      {
        name: 'Hadrons',
        particles: [
          PARTICLE_TYPES.PROTON,
          PARTICLE_TYPES.NEUTRON,
          PARTICLE_TYPES.ANTI_PROTON,
          PARTICLE_TYPES.ANTI_NEUTRON,
          PARTICLE_TYPES.PION_PLUS,
          PARTICLE_TYPES.PION_MINUS,
          PARTICLE_TYPES.LAMBDA_BARYON,
          PARTICLE_TYPES.J_PSI_MESON,
          PARTICLE_TYPES.EXCITED_ELECTRON,
          PARTICLE_TYPES.DECAYING_NEUTRON,
        ]
      },
      {
        name: 'Elements',
        particles: [
          PARTICLE_TYPES.HYDROGEN,
          PARTICLE_TYPES.HELIUM,
          PARTICLE_TYPES.LITHIUM,
          PARTICLE_TYPES.BERYLLIUM,
          PARTICLE_TYPES.BORON,
          PARTICLE_TYPES.CARBON,
          PARTICLE_TYPES.NITROGEN,
          PARTICLE_TYPES.OXYGEN,
          PARTICLE_TYPES.FLUORINE,
          PARTICLE_TYPES.NEON,
          PARTICLE_TYPES.SODIUM,
          PARTICLE_TYPES.MAGNESIUM,
          PARTICLE_TYPES.ALUMINIUM,
          PARTICLE_TYPES.SILICON,
          PARTICLE_TYPES.PHOSPHORUS,
          PARTICLE_TYPES.SULFUR,
          PARTICLE_TYPES.CHLORINE,
          PARTICLE_TYPES.ARGON,
          PARTICLE_TYPES.POTASSIUM,
          PARTICLE_TYPES.CALCIUM,
          PARTICLE_TYPES.SCANDIUM,
          PARTICLE_TYPES.TITANIUM,
          PARTICLE_TYPES.VANADIUM,
          PARTICLE_TYPES.CHROMIUM,
          PARTICLE_TYPES.MANGANESE,
          PARTICLE_TYPES.IRON,
          PARTICLE_TYPES.COBALT,
          PARTICLE_TYPES.NICKEL,
          PARTICLE_TYPES.COPPER,
          PARTICLE_TYPES.ZINC,
          PARTICLE_TYPES.GALLIUM,
          PARTICLE_TYPES.GERMANIUM,
          PARTICLE_TYPES.ARSENIC,
          PARTICLE_TYPES.SELENIUM,
          PARTICLE_TYPES.BROMINE,
          PARTICLE_TYPES.KRYPTON,
          PARTICLE_TYPES.TIN,
          PARTICLE_TYPES.SILVER,
          PARTICLE_TYPES.GOLD,
          PARTICLE_TYPES.LEAD,
        ]
      },
      {
        name: 'Isotopes',
        particles: [
          PARTICLE_TYPES.DEUTERIUM,
          PARTICLE_TYPES.TRITIUM,
          PARTICLE_TYPES.HELIUM_3,
          PARTICLE_TYPES.CARBON_14,
        ]
      },
      {
        name: 'Radioactive Isotopes',
        particles: [
          PARTICLE_TYPES.URANIUM_235,
          PARTICLE_TYPES.URANIUM_238,
          PARTICLE_TYPES.URANIUM_234,
          PARTICLE_TYPES.THORIUM_231,
          PARTICLE_TYPES.THORIUM_234,
          PARTICLE_TYPES.THORIUM_230,
          PARTICLE_TYPES.PROTACTINIUM_231,
          PARTICLE_TYPES.PROTACTINIUM_234,
          PARTICLE_TYPES.ACTINIUM_227,
          PARTICLE_TYPES.RADIUM_226,
          PARTICLE_TYPES.RADON_222,
          PARTICLE_TYPES.POLONIUM_210,
          PARTICLE_TYPES.LEAD_206,
          PARTICLE_TYPES.LEAD_207,
        ]
      },
      {
        name: 'Radiation',
        particles: [
          PARTICLE_TYPES.ALPHA_PARTICLE,
          PARTICLE_TYPES.BETA_PARTICLE,
          PARTICLE_TYPES.GAMMA_RAY,
        ]
      }
    ]
  },
  {
    name: 'Molecular',
    subcategories: [
      {
        name: 'Simple Molecules',
        particles: [
          PARTICLE_TYPES.WATER,
          PARTICLE_TYPES.METHANE,
          PARTICLE_TYPES.AMMONIA,
          PARTICLE_TYPES.CARBON_DIOXIDE,
          PARTICLE_TYPES.OZONE,
          PARTICLE_TYPES.HYDROGEN_PEROXIDE,
          PARTICLE_TYPES.HYDROCHLORIC_ACID,
          PARTICLE_TYPES.HYDROGEN_SULFIDE,
          PARTICLE_TYPES.NITROUS_OXIDE,
          PARTICLE_TYPES.CARBON_MONOXIDE,
          PARTICLE_TYPES.SODIUM_CHLORIDE,
          PARTICLE_TYPES.SILICON_DIOXIDE,
          PARTICLE_TYPES.NITROGEN_GAS,
          PARTICLE_TYPES.OXYGEN_GAS,
          PARTICLE_TYPES.SULFUR_DIOXIDE,
          PARTICLE_TYPES.NITROGEN_DIOXIDE,
          PARTICLE_TYPES.HYDROGEN_FLUORIDE,
          PARTICLE_TYPES.BAKING_SODA,
          PARTICLE_TYPES.UREA,
          PARTICLE_TYPES.PYRUVATE,
          PARTICLE_TYPES.IRON_OXIDE,
          PARTICLE_TYPES.IRON_SULFIDE,
          PARTICLE_TYPES.POTASSIUM_PERMANGANATE,
          PARTICLE_TYPES.UNIVERSAL_INDICATOR,
        ]
      },
      {
        name: 'Alloys',
        particles: [
          PARTICLE_TYPES.STEEL,
          PARTICLE_TYPES.BRONZE,
        ]
      },
      {
        name: 'Organic Solvents & Fuels',
        particles: [
          PARTICLE_TYPES.ETHANOL,
          PARTICLE_TYPES.METHANOL,
          PARTICLE_TYPES.ACETIC_ACID,
          PARTICLE_TYPES.VINEGAR,
          PARTICLE_TYPES.ACETONE,
          PARTICLE_TYPES.ETHYL_ACETATE,
          PARTICLE_TYPES.FORMALDEHYDE,
          PARTICLE_TYPES.ACETYLENE,
          PARTICLE_TYPES.HYDROGEN_CYANIDE,
          PARTICLE_TYPES.BENZENE,
          PARTICLE_TYPES.ETHYLENE,
          PARTICLE_TYPES.PROPANE,
          PARTICLE_TYPES.BUTANE,
        ]
      },
      {
        name: 'Acids',
        particles: [
          PARTICLE_TYPES.SULFURIC_ACID,
          PARTICLE_TYPES.NITRIC_ACID,
          PARTICLE_TYPES.CARBONIC_ACID,
          PARTICLE_TYPES.PHOSPHORIC_ACID,
          PARTICLE_TYPES.CITRIC_ACID,
        ]
      },
      {
        name: 'Polymers',
        particles: [
          PARTICLE_TYPES.POLYETHYLENE,
          PARTICLE_TYPES.CELLULOSE,
        ]
      }
    ]
  },
  {
    name: 'Biological',
    subcategories: [
      {
        name: 'Sugars',
        particles: [
          PARTICLE_TYPES.GLUCOSE,
          PARTICLE_TYPES.FRUCTOSE,
          PARTICLE_TYPES.DEOXYRIBOSE,
          PARTICLE_TYPES.RIBOSE,
        ]
      },
      {
        name: 'Amino Acids',
        particles: [
          PARTICLE_TYPES.GLYCINE,
          PARTICLE_TYPES.SERINE,
          PARTICLE_TYPES.ALANINE,
          PARTICLE_TYPES.VALINE,
          PARTICLE_TYPES.LEUCINE,
          PARTICLE_TYPES.ISOLEUCINE,
          PARTICLE_TYPES.THREONINE,
          PARTICLE_TYPES.METHIONINE,
          PARTICLE_TYPES.LYSINE,
          PARTICLE_TYPES.HISTIDINE,
          PARTICLE_TYPES.TRYPTOPHAN,
          PARTICLE_TYPES.ARGININE,
          PARTICLE_TYPES.ASPARAGINE,
          PARTICLE_TYPES.ASPARTIC_ACID,
          PARTICLE_TYPES.GLUTAMIC_ACID,
          PARTICLE_TYPES.GLUTAMINE,
          PARTICLE_TYPES.PROLINE,
          PARTICLE_TYPES.TYROSINE,
          PARTICLE_TYPES.CYSTEINE,
          PARTICLE_TYPES.PHENYLALANINE,
        ]
      },
      {
        name: 'Nucleotides',
        particles: [
          PARTICLE_TYPES.ATP,
          PARTICLE_TYPES.ADENINE,
          PARTICLE_TYPES.GUANINE,
          PARTICLE_TYPES.CYTOSINE,
          PARTICLE_TYPES.THYMINE,
          PARTICLE_TYPES.URACIL,
          PARTICLE_TYPES.NUCLEOTIDE_A,
          PARTICLE_TYPES.NUCLEOTIDE_T,
          PARTICLE_TYPES.NUCLEOTIDE_G,
          PARTICLE_TYPES.NUCLEOTIDE_C,
          PARTICLE_TYPES.NUCLEOTIDE_U,
          PARTICLE_TYPES.PHOSPHATE,
        ]
      },
      {
        name: 'Complex Bios',
        particles: [
          PARTICLE_TYPES.GLYCYLGLYCINE,
          PARTICLE_TYPES.GLYCYL_ALANINE,
          PARTICLE_TYPES.INSULIN_FRAGMENT,
          PARTICLE_TYPES.HEMOGLOBIN_POCKET,
          PARTICLE_TYPES.LIPID,
          PARTICLE_TYPES.PHOSPHOLIPID,
          PARTICLE_TYPES.CHOLESTEROL,
          PARTICLE_TYPES.NADH,
          PARTICLE_TYPES.HEME,
          PARTICLE_TYPES.GLYCEROL,
          PARTICLE_TYPES.FATTY_ACID,
          PARTICLE_TYPES.DNA,
          PARTICLE_TYPES.RNA,
        ]
      },
      {
        name: 'Organelles',
        particles: [
          PARTICLE_TYPES.MEMBRANE,
          PARTICLE_TYPES.RIBOSOME,
          PARTICLE_TYPES.MITOCHONDRION,
          PARTICLE_TYPES.NUCLEUS,
        ]
      },
    ]
  }
];

export const elementaryParticleGroups = {
  Quarks: [
    { id: 'up-1', type: PARTICLE_TYPES.UP_QUARK },
    { id: 'down-1', type: PARTICLE_TYPES.DOWN_QUARK },
    { id: 'charm-1', type: PARTICLE_TYPES.CHARM_QUARK },
    { id: 'strange-1', type: PARTICLE_TYPES.STRANGE_QUARK },
    { id: 'top-1', type: PARTICLE_TYPES.TOP_QUARK },
    { id: 'bottom-1', type: PARTICLE_TYPES.BOTTOM_QUARK },
  ],
  'Anti-Quarks': [
    { id: 'anti-up-1', type: PARTICLE_TYPES.ANTI_UP_QUARK },
    { id: 'anti-down-1', type: PARTICLE_TYPES.ANTI_DOWN_QUARK },
    { id: 'anti-charm-1', type: PARTICLE_TYPES.ANTI_CHARM_QUARK },
  ],
  Leptons: [
    { id: 'electron-1', type: PARTICLE_TYPES.ELECTRON },
    { id: 'electron-neutrino-1', type: PARTICLE_TYPES.ELECTRON_NEUTRINO },
  ],
  'Anti-Leptons': [
    { id: 'e-antineutrino-1', type: PARTICLE_TYPES.ELECTRON_ANTINEUTRINO },
  ],
  Bosons: [
    { id: 'photon-1', type: PARTICLE_TYPES.PHOTON },
    { id: 'gluon-1', type: PARTICLE_TYPES.GLUON },
    { id: 'w-boson-1', type: PARTICLE_TYPES.W_BOSON },
    { id: 'z-boson-1', type: PARTICLE_TYPES.Z_BOSON },
  ]
};

export const PARTICLE_COLOR_MAP = {
  'yellow-400': '#fbbf24',
  'indigo-400': '#818cf8',
  'purple-500': '#a855f7',
  'green-500': '#22c55e',
  'cyan-500': '#06b6d4',
  'gray-700': '#374151',
  'blue-600': '#2563eb',
  'gray-400': '#9ca3af',
  'yellow-300': '#fde047',
  'black': '#000000',
  'orange-500': '#f97316',
  'red-700': '#b91c1c',
  'red-500': '#ef4444',
  'pink-500': '#ec4899',
  'teal-500': '#14b8a6',
  'sky-600': '#0284c7',
  'violet-600': '#7c3aed',
  'orange-300': '#fdba74',
  'fuchsia-500': '#d946ef',
  'lime-500': '#84cc16',
  'rose-500': '#f43f5e',
  'gray-800': '#1f2937',
  'sky-500': '#0ea5e9',
  'red-600': '#dc2626',
  'emerald-500': '#10b981',
  'orange-600': '#ea580c',
  'violet-500': '#8b5cf6',
  'lime-400': '#a3e635',
  'slate-400': '#94a3b8',
  'stone-500': '#78716c',
  'red-400': '#f87171',
  'yellow-500': '#eab308',
  'green-400': '#4ade80',
  'cyan-400': '#22d3ee',
  'violet-400': '#a78bfa',
  'slate-200': '#e2e8f0',
  'cyan-300': '#67e8f9',
  'slate-500': '#64748b',
  'blue-300': '#93c5fd',
  'rose-300': '#fecdd3',
  'orange-900': '#7c2d12',
  'blue-800': '#1e40af',
  'lime-300': '#bef264',
  'orange-400': '#fb923c',
  'sky-200': '#bae6fd',
  'fuchsia-400': '#e879f9',
  'stone-400': '#a8a29e',
  'slate-300': '#cbd5e1',
  'red-800': '#991b1b',
  'violet-300': '#c4b5fd',
  'yellow-600': '#d97706',
  'indigo-600': '#4f46e5',
  'rose-400': '#fb7185',
  'rose-600': '#e11d48',
  'orange-700': '#c2410c',
  'gray-600': '#4b5563',
  'sky-400': '#38bdf8',
  'cyan-600': '#0891b2',
  'slate-300': '#cbd5e1',
  'blue-400': '#60a5fa',
  'gray-500': '#6b7280',
  'pink-400': '#f472b6',
  'gray-200': '#e5e7eb',
  'cyan-200': '#a5f3fc',
  'lime-300': '#bef264',
  'sky-200': '#bae6fd',
  'purple-700': '#7e22ce',
  'green-700': '#15803d',
  'violet-700': '#6d28d9',
  'sky-300': '#7dd3fc',
  'indigo-300': '#a5b4fc',
  'stone-300': '#d6d3d1',
  'purple-600': '#9333ea',
  'teal-600': '#0d9488',
  'fuchsia-700': '#a21caf',
  'green-600': '#16a34a',
  'rose-700': '#be123c',
  'indigo-500': '#6366f1',
  'lime-600': '#4d7c0f',
  'yellow-700': '#a16207',
  'teal-400': '#2dd4bf',
  'zinc-600': '#52525b',
  'fuchsia-600': '#c026d3',
  'orange-800': '#9a3412',
};
