import { PARTICLE_TYPES } from '../particles';

const {
  HYDROGEN, OXYGEN, CARBON, NITROGEN, PHOSPHORUS, SULFUR,
  WATER, METHANE, AMMONIA, CARBON_DIOXIDE, GLUCOSE, ATP, PHOSPHOLIPID
} = PARTICLE_TYPES;

export const MOLECULAR_MATTER = {
  [WATER]: { parents: [HYDROGEN, OXYGEN] },
  [METHANE]: { parents: [CARBON, HYDROGEN] },
  [AMMONIA]: { parents: [NITROGEN, HYDROGEN] },
  [CARBON_DIOXIDE]: { parents: [CARBON, OXYGEN] },
  [GLUCOSE]: { parents: [CARBON, HYDROGEN, OXYGEN] },
  [ATP]: { parents: [PHOSPHORUS, NITROGEN, CARBON, HYDROGEN, OXYGEN] },
  [PHOSPHOLIPID]: { parents: [PHOSPHORUS, CARBON, HYDROGEN, OXYGEN] },
};
